import type { CaresEvent } from '../types/event'

export const MOCK_EVENTS: CaresEvent[] = [
  {
    event_id: 1001,
    title: 'Community Clean-Up Drive',
    description:
      'Join volunteers for a coastal and barangay clean-up initiative. Bring gloves and reusable bags.',
    event_started: '2026-07-15T08:00:00.000Z',
    event_ended: '2026-07-15T12:00:00.000Z',
    location: 'Mandaue City Coastal Area',
    max_participants: 80,
    participants: 42,
    organizer_name: 'Maria Santos',
    category: 'Community',
    status: 'Upcoming',
    funds_donation: true,
    goods_donation: false,
    goods_types: [],
    beneficiary_applicable: false,
    event_image: undefined,
    geojson: null,
    area_sqm: null,
  },
  {
    event_id: 1002,
    title: 'Barangay Health Seminar',
    description:
      'Free health screening and nutrition seminar for local residents. Medical volunteers welcome.',
    event_started: '2026-07-22T09:00:00.000Z',
    event_ended: '2026-07-22T15:00:00.000Z',
    location: 'UCLM Gymnasium',
    max_participants: 120,
    participants: 67,
    organizer_name: 'Ana Lopez',
    category: 'Health',
    status: 'Upcoming',
    funds_donation: false,
    goods_donation: true,
    goods_types: ['medicine', 'hygiene'],
    beneficiary_applicable: true,
    max_beneficiaries: 50,
    event_image: undefined,
    geojson: null,
    area_sqm: null,
  },
  {
    event_id: 1003,
    title: 'Engineering Outreach Program',
    description:
      'STEM workshop for high school students. Hands-on robotics and coding sessions.',
    event_started: '2026-06-10T08:00:00.000Z',
    event_ended: '2026-06-10T17:00:00.000Z',
    location: 'College of Engineering Building',
    max_participants: 60,
    participants: 58,
    organizer_name: 'Juan Reyes',
    category: 'School',
    department: 'College of Engineering',
    status: 'Completed',
    funds_donation: false,
    goods_donation: false,
    goods_types: [],
    beneficiary_applicable: false,
    event_image: undefined,
    geojson: null,
    area_sqm: null,
  },
  {
    event_id: 1004,
    title: 'Typhoon Relief Distribution',
    description:
      'Emergency relief goods distribution for affected families. Volunteers needed for packing and delivery.',
    event_started: '2026-08-01T07:00:00.000Z',
    event_ended: '2026-08-01T18:00:00.000Z',
    location: 'Consolacion Evacuation Center',
    max_participants: 100,
    participants: 23,
    organizer_name: 'Maria Santos',
    category: 'Relief Program',
    status: 'Upcoming',
    funds_donation: true,
    goods_donation: true,
    goods_types: ['food', 'clothing', 'hygiene', 'supplies'],
    beneficiary_applicable: true,
    max_beneficiaries: 200,
    event_image: undefined,
    geojson: null,
    area_sqm: null,
  },
  {
    event_id: 1005,
    title: 'UC Blood Donation Drive',
    description:
      'Annual blood donation campaign open to students, faculty, and the public. Registration on-site.',
    event_started: '2026-07-02T02:00:00.000Z',
    event_ended: '2026-07-02T14:00:00.000Z',
    location: 'University of Cebu Main Campus',
    max_participants: 150,
    participants: 89,
    organizer_name: 'College of Nursing',
    category: 'Health',
    status: 'Ongoing',
    funds_donation: false,
    goods_donation: false,
    goods_types: [],
    beneficiary_applicable: false,
    event_image: undefined,
    geojson: null,
    area_sqm: null,
  },
  {
    event_id: 1006,
    title: 'Coastal Cleanup — Mactan (Cancelled)',
    description: 'Postponed due to weather advisory. Will be rescheduled.',
    event_started: '2026-07-10T06:00:00.000Z',
    event_ended: '2026-07-10T12:00:00.000Z',
    location: 'Mandaue Coastal Road',
    max_participants: 40,
    participants: 12,
    organizer_name: 'Ana Lopez',
    category: 'Community',
    status: 'Cancelled',
    funds_donation: false,
    goods_donation: false,
    goods_types: [],
    beneficiary_applicable: false,
    event_image: undefined,
    geojson: null,
    area_sqm: null,
  },
]
