/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CertificateTemplateAsset` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model CertificateTemplateAsset
 * A file a director imported onto a sheet. The bytes live in the private S3 bucket,
 * so `design` references the row by id and the portal reads the bytes back through
 * `GET /v1/certificate-templates/:id/assets/:assetId` — an `<img src>` pointed at the
 * stored object URL would render broken.
 */
export type CertificateTemplateAssetModel = runtime.Types.Result.DefaultSelection<Prisma.$CertificateTemplateAssetPayload>

export type AggregateCertificateTemplateAsset = {
  _count: CertificateTemplateAssetCountAggregateOutputType | null
  _avg: CertificateTemplateAssetAvgAggregateOutputType | null
  _sum: CertificateTemplateAssetSumAggregateOutputType | null
  _min: CertificateTemplateAssetMinAggregateOutputType | null
  _max: CertificateTemplateAssetMaxAggregateOutputType | null
}

export type CertificateTemplateAssetAvgAggregateOutputType = {
  byte_size: number | null
}

export type CertificateTemplateAssetSumAggregateOutputType = {
  byte_size: number | null
}

export type CertificateTemplateAssetMinAggregateOutputType = {
  certificate_template_asset_id: string | null
  certificate_template_id: string | null
  kind: $Enums.CertificateAssetKind | null
  storage_key: string | null
  file_name: string | null
  content_type: string | null
  byte_size: number | null
  createdAt: Date | null
}

export type CertificateTemplateAssetMaxAggregateOutputType = {
  certificate_template_asset_id: string | null
  certificate_template_id: string | null
  kind: $Enums.CertificateAssetKind | null
  storage_key: string | null
  file_name: string | null
  content_type: string | null
  byte_size: number | null
  createdAt: Date | null
}

export type CertificateTemplateAssetCountAggregateOutputType = {
  certificate_template_asset_id: number
  certificate_template_id: number
  kind: number
  storage_key: number
  file_name: number
  content_type: number
  byte_size: number
  createdAt: number
  _all: number
}


export type CertificateTemplateAssetAvgAggregateInputType = {
  byte_size?: true
}

export type CertificateTemplateAssetSumAggregateInputType = {
  byte_size?: true
}

export type CertificateTemplateAssetMinAggregateInputType = {
  certificate_template_asset_id?: true
  certificate_template_id?: true
  kind?: true
  storage_key?: true
  file_name?: true
  content_type?: true
  byte_size?: true
  createdAt?: true
}

export type CertificateTemplateAssetMaxAggregateInputType = {
  certificate_template_asset_id?: true
  certificate_template_id?: true
  kind?: true
  storage_key?: true
  file_name?: true
  content_type?: true
  byte_size?: true
  createdAt?: true
}

export type CertificateTemplateAssetCountAggregateInputType = {
  certificate_template_asset_id?: true
  certificate_template_id?: true
  kind?: true
  storage_key?: true
  file_name?: true
  content_type?: true
  byte_size?: true
  createdAt?: true
  _all?: true
}

export type CertificateTemplateAssetAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CertificateTemplateAsset to aggregate.
   */
  where?: Prisma.CertificateTemplateAssetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CertificateTemplateAssets to fetch.
   */
  orderBy?: Prisma.CertificateTemplateAssetOrderByWithRelationInput | Prisma.CertificateTemplateAssetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CertificateTemplateAssetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CertificateTemplateAssets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CertificateTemplateAssets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CertificateTemplateAssets
  **/
  _count?: true | CertificateTemplateAssetCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CertificateTemplateAssetAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CertificateTemplateAssetSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CertificateTemplateAssetMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CertificateTemplateAssetMaxAggregateInputType
}

export type GetCertificateTemplateAssetAggregateType<T extends CertificateTemplateAssetAggregateArgs> = {
      [P in keyof T & keyof AggregateCertificateTemplateAsset]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCertificateTemplateAsset[P]>
    : Prisma.GetScalarType<T[P], AggregateCertificateTemplateAsset[P]>
}




export type CertificateTemplateAssetGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CertificateTemplateAssetWhereInput
  orderBy?: Prisma.CertificateTemplateAssetOrderByWithAggregationInput | Prisma.CertificateTemplateAssetOrderByWithAggregationInput[]
  by: Prisma.CertificateTemplateAssetScalarFieldEnum[] | Prisma.CertificateTemplateAssetScalarFieldEnum
  having?: Prisma.CertificateTemplateAssetScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CertificateTemplateAssetCountAggregateInputType | true
  _avg?: CertificateTemplateAssetAvgAggregateInputType
  _sum?: CertificateTemplateAssetSumAggregateInputType
  _min?: CertificateTemplateAssetMinAggregateInputType
  _max?: CertificateTemplateAssetMaxAggregateInputType
}

export type CertificateTemplateAssetGroupByOutputType = {
  certificate_template_asset_id: string
  certificate_template_id: string
  kind: $Enums.CertificateAssetKind
  storage_key: string
  file_name: string
  content_type: string
  byte_size: number
  createdAt: Date
  _count: CertificateTemplateAssetCountAggregateOutputType | null
  _avg: CertificateTemplateAssetAvgAggregateOutputType | null
  _sum: CertificateTemplateAssetSumAggregateOutputType | null
  _min: CertificateTemplateAssetMinAggregateOutputType | null
  _max: CertificateTemplateAssetMaxAggregateOutputType | null
}

export type GetCertificateTemplateAssetGroupByPayload<T extends CertificateTemplateAssetGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CertificateTemplateAssetGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CertificateTemplateAssetGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CertificateTemplateAssetGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CertificateTemplateAssetGroupByOutputType[P]>
      }
    >
  >



export type CertificateTemplateAssetWhereInput = {
  AND?: Prisma.CertificateTemplateAssetWhereInput | Prisma.CertificateTemplateAssetWhereInput[]
  OR?: Prisma.CertificateTemplateAssetWhereInput[]
  NOT?: Prisma.CertificateTemplateAssetWhereInput | Prisma.CertificateTemplateAssetWhereInput[]
  certificate_template_asset_id?: Prisma.StringFilter<"CertificateTemplateAsset"> | string
  certificate_template_id?: Prisma.StringFilter<"CertificateTemplateAsset"> | string
  kind?: Prisma.EnumCertificateAssetKindFilter<"CertificateTemplateAsset"> | $Enums.CertificateAssetKind
  storage_key?: Prisma.StringFilter<"CertificateTemplateAsset"> | string
  file_name?: Prisma.StringFilter<"CertificateTemplateAsset"> | string
  content_type?: Prisma.StringFilter<"CertificateTemplateAsset"> | string
  byte_size?: Prisma.IntFilter<"CertificateTemplateAsset"> | number
  createdAt?: Prisma.DateTimeFilter<"CertificateTemplateAsset"> | Date | string
  template?: Prisma.XOR<Prisma.CertificateTemplateScalarRelationFilter, Prisma.CertificateTemplateWhereInput>
}

export type CertificateTemplateAssetOrderByWithRelationInput = {
  certificate_template_asset_id?: Prisma.SortOrder
  certificate_template_id?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  storage_key?: Prisma.SortOrder
  file_name?: Prisma.SortOrder
  content_type?: Prisma.SortOrder
  byte_size?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  template?: Prisma.CertificateTemplateOrderByWithRelationInput
}

export type CertificateTemplateAssetWhereUniqueInput = Prisma.AtLeast<{
  certificate_template_asset_id?: string
  AND?: Prisma.CertificateTemplateAssetWhereInput | Prisma.CertificateTemplateAssetWhereInput[]
  OR?: Prisma.CertificateTemplateAssetWhereInput[]
  NOT?: Prisma.CertificateTemplateAssetWhereInput | Prisma.CertificateTemplateAssetWhereInput[]
  certificate_template_id?: Prisma.StringFilter<"CertificateTemplateAsset"> | string
  kind?: Prisma.EnumCertificateAssetKindFilter<"CertificateTemplateAsset"> | $Enums.CertificateAssetKind
  storage_key?: Prisma.StringFilter<"CertificateTemplateAsset"> | string
  file_name?: Prisma.StringFilter<"CertificateTemplateAsset"> | string
  content_type?: Prisma.StringFilter<"CertificateTemplateAsset"> | string
  byte_size?: Prisma.IntFilter<"CertificateTemplateAsset"> | number
  createdAt?: Prisma.DateTimeFilter<"CertificateTemplateAsset"> | Date | string
  template?: Prisma.XOR<Prisma.CertificateTemplateScalarRelationFilter, Prisma.CertificateTemplateWhereInput>
}, "certificate_template_asset_id">

export type CertificateTemplateAssetOrderByWithAggregationInput = {
  certificate_template_asset_id?: Prisma.SortOrder
  certificate_template_id?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  storage_key?: Prisma.SortOrder
  file_name?: Prisma.SortOrder
  content_type?: Prisma.SortOrder
  byte_size?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.CertificateTemplateAssetCountOrderByAggregateInput
  _avg?: Prisma.CertificateTemplateAssetAvgOrderByAggregateInput
  _max?: Prisma.CertificateTemplateAssetMaxOrderByAggregateInput
  _min?: Prisma.CertificateTemplateAssetMinOrderByAggregateInput
  _sum?: Prisma.CertificateTemplateAssetSumOrderByAggregateInput
}

export type CertificateTemplateAssetScalarWhereWithAggregatesInput = {
  AND?: Prisma.CertificateTemplateAssetScalarWhereWithAggregatesInput | Prisma.CertificateTemplateAssetScalarWhereWithAggregatesInput[]
  OR?: Prisma.CertificateTemplateAssetScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CertificateTemplateAssetScalarWhereWithAggregatesInput | Prisma.CertificateTemplateAssetScalarWhereWithAggregatesInput[]
  certificate_template_asset_id?: Prisma.StringWithAggregatesFilter<"CertificateTemplateAsset"> | string
  certificate_template_id?: Prisma.StringWithAggregatesFilter<"CertificateTemplateAsset"> | string
  kind?: Prisma.EnumCertificateAssetKindWithAggregatesFilter<"CertificateTemplateAsset"> | $Enums.CertificateAssetKind
  storage_key?: Prisma.StringWithAggregatesFilter<"CertificateTemplateAsset"> | string
  file_name?: Prisma.StringWithAggregatesFilter<"CertificateTemplateAsset"> | string
  content_type?: Prisma.StringWithAggregatesFilter<"CertificateTemplateAsset"> | string
  byte_size?: Prisma.IntWithAggregatesFilter<"CertificateTemplateAsset"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CertificateTemplateAsset"> | Date | string
}

export type CertificateTemplateAssetCreateInput = {
  certificate_template_asset_id?: string
  kind: $Enums.CertificateAssetKind
  storage_key: string
  file_name: string
  content_type: string
  byte_size: number
  createdAt?: Date | string
  template: Prisma.CertificateTemplateCreateNestedOneWithoutAssetsInput
}

export type CertificateTemplateAssetUncheckedCreateInput = {
  certificate_template_asset_id?: string
  certificate_template_id: string
  kind: $Enums.CertificateAssetKind
  storage_key: string
  file_name: string
  content_type: string
  byte_size: number
  createdAt?: Date | string
}

export type CertificateTemplateAssetUpdateInput = {
  certificate_template_asset_id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumCertificateAssetKindFieldUpdateOperationsInput | $Enums.CertificateAssetKind
  storage_key?: Prisma.StringFieldUpdateOperationsInput | string
  file_name?: Prisma.StringFieldUpdateOperationsInput | string
  content_type?: Prisma.StringFieldUpdateOperationsInput | string
  byte_size?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  template?: Prisma.CertificateTemplateUpdateOneRequiredWithoutAssetsNestedInput
}

export type CertificateTemplateAssetUncheckedUpdateInput = {
  certificate_template_asset_id?: Prisma.StringFieldUpdateOperationsInput | string
  certificate_template_id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumCertificateAssetKindFieldUpdateOperationsInput | $Enums.CertificateAssetKind
  storage_key?: Prisma.StringFieldUpdateOperationsInput | string
  file_name?: Prisma.StringFieldUpdateOperationsInput | string
  content_type?: Prisma.StringFieldUpdateOperationsInput | string
  byte_size?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CertificateTemplateAssetCreateManyInput = {
  certificate_template_asset_id?: string
  certificate_template_id: string
  kind: $Enums.CertificateAssetKind
  storage_key: string
  file_name: string
  content_type: string
  byte_size: number
  createdAt?: Date | string
}

export type CertificateTemplateAssetUpdateManyMutationInput = {
  certificate_template_asset_id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumCertificateAssetKindFieldUpdateOperationsInput | $Enums.CertificateAssetKind
  storage_key?: Prisma.StringFieldUpdateOperationsInput | string
  file_name?: Prisma.StringFieldUpdateOperationsInput | string
  content_type?: Prisma.StringFieldUpdateOperationsInput | string
  byte_size?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CertificateTemplateAssetUncheckedUpdateManyInput = {
  certificate_template_asset_id?: Prisma.StringFieldUpdateOperationsInput | string
  certificate_template_id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumCertificateAssetKindFieldUpdateOperationsInput | $Enums.CertificateAssetKind
  storage_key?: Prisma.StringFieldUpdateOperationsInput | string
  file_name?: Prisma.StringFieldUpdateOperationsInput | string
  content_type?: Prisma.StringFieldUpdateOperationsInput | string
  byte_size?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CertificateTemplateAssetListRelationFilter = {
  every?: Prisma.CertificateTemplateAssetWhereInput
  some?: Prisma.CertificateTemplateAssetWhereInput
  none?: Prisma.CertificateTemplateAssetWhereInput
}

export type CertificateTemplateAssetOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CertificateTemplateAssetCountOrderByAggregateInput = {
  certificate_template_asset_id?: Prisma.SortOrder
  certificate_template_id?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  storage_key?: Prisma.SortOrder
  file_name?: Prisma.SortOrder
  content_type?: Prisma.SortOrder
  byte_size?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CertificateTemplateAssetAvgOrderByAggregateInput = {
  byte_size?: Prisma.SortOrder
}

export type CertificateTemplateAssetMaxOrderByAggregateInput = {
  certificate_template_asset_id?: Prisma.SortOrder
  certificate_template_id?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  storage_key?: Prisma.SortOrder
  file_name?: Prisma.SortOrder
  content_type?: Prisma.SortOrder
  byte_size?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CertificateTemplateAssetMinOrderByAggregateInput = {
  certificate_template_asset_id?: Prisma.SortOrder
  certificate_template_id?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  storage_key?: Prisma.SortOrder
  file_name?: Prisma.SortOrder
  content_type?: Prisma.SortOrder
  byte_size?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CertificateTemplateAssetSumOrderByAggregateInput = {
  byte_size?: Prisma.SortOrder
}

export type CertificateTemplateAssetCreateNestedManyWithoutTemplateInput = {
  create?: Prisma.XOR<Prisma.CertificateTemplateAssetCreateWithoutTemplateInput, Prisma.CertificateTemplateAssetUncheckedCreateWithoutTemplateInput> | Prisma.CertificateTemplateAssetCreateWithoutTemplateInput[] | Prisma.CertificateTemplateAssetUncheckedCreateWithoutTemplateInput[]
  connectOrCreate?: Prisma.CertificateTemplateAssetCreateOrConnectWithoutTemplateInput | Prisma.CertificateTemplateAssetCreateOrConnectWithoutTemplateInput[]
  createMany?: Prisma.CertificateTemplateAssetCreateManyTemplateInputEnvelope
  connect?: Prisma.CertificateTemplateAssetWhereUniqueInput | Prisma.CertificateTemplateAssetWhereUniqueInput[]
}

export type CertificateTemplateAssetUncheckedCreateNestedManyWithoutTemplateInput = {
  create?: Prisma.XOR<Prisma.CertificateTemplateAssetCreateWithoutTemplateInput, Prisma.CertificateTemplateAssetUncheckedCreateWithoutTemplateInput> | Prisma.CertificateTemplateAssetCreateWithoutTemplateInput[] | Prisma.CertificateTemplateAssetUncheckedCreateWithoutTemplateInput[]
  connectOrCreate?: Prisma.CertificateTemplateAssetCreateOrConnectWithoutTemplateInput | Prisma.CertificateTemplateAssetCreateOrConnectWithoutTemplateInput[]
  createMany?: Prisma.CertificateTemplateAssetCreateManyTemplateInputEnvelope
  connect?: Prisma.CertificateTemplateAssetWhereUniqueInput | Prisma.CertificateTemplateAssetWhereUniqueInput[]
}

export type CertificateTemplateAssetUpdateManyWithoutTemplateNestedInput = {
  create?: Prisma.XOR<Prisma.CertificateTemplateAssetCreateWithoutTemplateInput, Prisma.CertificateTemplateAssetUncheckedCreateWithoutTemplateInput> | Prisma.CertificateTemplateAssetCreateWithoutTemplateInput[] | Prisma.CertificateTemplateAssetUncheckedCreateWithoutTemplateInput[]
  connectOrCreate?: Prisma.CertificateTemplateAssetCreateOrConnectWithoutTemplateInput | Prisma.CertificateTemplateAssetCreateOrConnectWithoutTemplateInput[]
  upsert?: Prisma.CertificateTemplateAssetUpsertWithWhereUniqueWithoutTemplateInput | Prisma.CertificateTemplateAssetUpsertWithWhereUniqueWithoutTemplateInput[]
  createMany?: Prisma.CertificateTemplateAssetCreateManyTemplateInputEnvelope
  set?: Prisma.CertificateTemplateAssetWhereUniqueInput | Prisma.CertificateTemplateAssetWhereUniqueInput[]
  disconnect?: Prisma.CertificateTemplateAssetWhereUniqueInput | Prisma.CertificateTemplateAssetWhereUniqueInput[]
  delete?: Prisma.CertificateTemplateAssetWhereUniqueInput | Prisma.CertificateTemplateAssetWhereUniqueInput[]
  connect?: Prisma.CertificateTemplateAssetWhereUniqueInput | Prisma.CertificateTemplateAssetWhereUniqueInput[]
  update?: Prisma.CertificateTemplateAssetUpdateWithWhereUniqueWithoutTemplateInput | Prisma.CertificateTemplateAssetUpdateWithWhereUniqueWithoutTemplateInput[]
  updateMany?: Prisma.CertificateTemplateAssetUpdateManyWithWhereWithoutTemplateInput | Prisma.CertificateTemplateAssetUpdateManyWithWhereWithoutTemplateInput[]
  deleteMany?: Prisma.CertificateTemplateAssetScalarWhereInput | Prisma.CertificateTemplateAssetScalarWhereInput[]
}

export type CertificateTemplateAssetUncheckedUpdateManyWithoutTemplateNestedInput = {
  create?: Prisma.XOR<Prisma.CertificateTemplateAssetCreateWithoutTemplateInput, Prisma.CertificateTemplateAssetUncheckedCreateWithoutTemplateInput> | Prisma.CertificateTemplateAssetCreateWithoutTemplateInput[] | Prisma.CertificateTemplateAssetUncheckedCreateWithoutTemplateInput[]
  connectOrCreate?: Prisma.CertificateTemplateAssetCreateOrConnectWithoutTemplateInput | Prisma.CertificateTemplateAssetCreateOrConnectWithoutTemplateInput[]
  upsert?: Prisma.CertificateTemplateAssetUpsertWithWhereUniqueWithoutTemplateInput | Prisma.CertificateTemplateAssetUpsertWithWhereUniqueWithoutTemplateInput[]
  createMany?: Prisma.CertificateTemplateAssetCreateManyTemplateInputEnvelope
  set?: Prisma.CertificateTemplateAssetWhereUniqueInput | Prisma.CertificateTemplateAssetWhereUniqueInput[]
  disconnect?: Prisma.CertificateTemplateAssetWhereUniqueInput | Prisma.CertificateTemplateAssetWhereUniqueInput[]
  delete?: Prisma.CertificateTemplateAssetWhereUniqueInput | Prisma.CertificateTemplateAssetWhereUniqueInput[]
  connect?: Prisma.CertificateTemplateAssetWhereUniqueInput | Prisma.CertificateTemplateAssetWhereUniqueInput[]
  update?: Prisma.CertificateTemplateAssetUpdateWithWhereUniqueWithoutTemplateInput | Prisma.CertificateTemplateAssetUpdateWithWhereUniqueWithoutTemplateInput[]
  updateMany?: Prisma.CertificateTemplateAssetUpdateManyWithWhereWithoutTemplateInput | Prisma.CertificateTemplateAssetUpdateManyWithWhereWithoutTemplateInput[]
  deleteMany?: Prisma.CertificateTemplateAssetScalarWhereInput | Prisma.CertificateTemplateAssetScalarWhereInput[]
}

export type EnumCertificateAssetKindFieldUpdateOperationsInput = {
  set?: $Enums.CertificateAssetKind
}

export type CertificateTemplateAssetCreateWithoutTemplateInput = {
  certificate_template_asset_id?: string
  kind: $Enums.CertificateAssetKind
  storage_key: string
  file_name: string
  content_type: string
  byte_size: number
  createdAt?: Date | string
}

export type CertificateTemplateAssetUncheckedCreateWithoutTemplateInput = {
  certificate_template_asset_id?: string
  kind: $Enums.CertificateAssetKind
  storage_key: string
  file_name: string
  content_type: string
  byte_size: number
  createdAt?: Date | string
}

export type CertificateTemplateAssetCreateOrConnectWithoutTemplateInput = {
  where: Prisma.CertificateTemplateAssetWhereUniqueInput
  create: Prisma.XOR<Prisma.CertificateTemplateAssetCreateWithoutTemplateInput, Prisma.CertificateTemplateAssetUncheckedCreateWithoutTemplateInput>
}

export type CertificateTemplateAssetCreateManyTemplateInputEnvelope = {
  data: Prisma.CertificateTemplateAssetCreateManyTemplateInput | Prisma.CertificateTemplateAssetCreateManyTemplateInput[]
  skipDuplicates?: boolean
}

export type CertificateTemplateAssetUpsertWithWhereUniqueWithoutTemplateInput = {
  where: Prisma.CertificateTemplateAssetWhereUniqueInput
  update: Prisma.XOR<Prisma.CertificateTemplateAssetUpdateWithoutTemplateInput, Prisma.CertificateTemplateAssetUncheckedUpdateWithoutTemplateInput>
  create: Prisma.XOR<Prisma.CertificateTemplateAssetCreateWithoutTemplateInput, Prisma.CertificateTemplateAssetUncheckedCreateWithoutTemplateInput>
}

export type CertificateTemplateAssetUpdateWithWhereUniqueWithoutTemplateInput = {
  where: Prisma.CertificateTemplateAssetWhereUniqueInput
  data: Prisma.XOR<Prisma.CertificateTemplateAssetUpdateWithoutTemplateInput, Prisma.CertificateTemplateAssetUncheckedUpdateWithoutTemplateInput>
}

export type CertificateTemplateAssetUpdateManyWithWhereWithoutTemplateInput = {
  where: Prisma.CertificateTemplateAssetScalarWhereInput
  data: Prisma.XOR<Prisma.CertificateTemplateAssetUpdateManyMutationInput, Prisma.CertificateTemplateAssetUncheckedUpdateManyWithoutTemplateInput>
}

export type CertificateTemplateAssetScalarWhereInput = {
  AND?: Prisma.CertificateTemplateAssetScalarWhereInput | Prisma.CertificateTemplateAssetScalarWhereInput[]
  OR?: Prisma.CertificateTemplateAssetScalarWhereInput[]
  NOT?: Prisma.CertificateTemplateAssetScalarWhereInput | Prisma.CertificateTemplateAssetScalarWhereInput[]
  certificate_template_asset_id?: Prisma.StringFilter<"CertificateTemplateAsset"> | string
  certificate_template_id?: Prisma.StringFilter<"CertificateTemplateAsset"> | string
  kind?: Prisma.EnumCertificateAssetKindFilter<"CertificateTemplateAsset"> | $Enums.CertificateAssetKind
  storage_key?: Prisma.StringFilter<"CertificateTemplateAsset"> | string
  file_name?: Prisma.StringFilter<"CertificateTemplateAsset"> | string
  content_type?: Prisma.StringFilter<"CertificateTemplateAsset"> | string
  byte_size?: Prisma.IntFilter<"CertificateTemplateAsset"> | number
  createdAt?: Prisma.DateTimeFilter<"CertificateTemplateAsset"> | Date | string
}

export type CertificateTemplateAssetCreateManyTemplateInput = {
  certificate_template_asset_id?: string
  kind: $Enums.CertificateAssetKind
  storage_key: string
  file_name: string
  content_type: string
  byte_size: number
  createdAt?: Date | string
}

export type CertificateTemplateAssetUpdateWithoutTemplateInput = {
  certificate_template_asset_id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumCertificateAssetKindFieldUpdateOperationsInput | $Enums.CertificateAssetKind
  storage_key?: Prisma.StringFieldUpdateOperationsInput | string
  file_name?: Prisma.StringFieldUpdateOperationsInput | string
  content_type?: Prisma.StringFieldUpdateOperationsInput | string
  byte_size?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CertificateTemplateAssetUncheckedUpdateWithoutTemplateInput = {
  certificate_template_asset_id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumCertificateAssetKindFieldUpdateOperationsInput | $Enums.CertificateAssetKind
  storage_key?: Prisma.StringFieldUpdateOperationsInput | string
  file_name?: Prisma.StringFieldUpdateOperationsInput | string
  content_type?: Prisma.StringFieldUpdateOperationsInput | string
  byte_size?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CertificateTemplateAssetUncheckedUpdateManyWithoutTemplateInput = {
  certificate_template_asset_id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumCertificateAssetKindFieldUpdateOperationsInput | $Enums.CertificateAssetKind
  storage_key?: Prisma.StringFieldUpdateOperationsInput | string
  file_name?: Prisma.StringFieldUpdateOperationsInput | string
  content_type?: Prisma.StringFieldUpdateOperationsInput | string
  byte_size?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CertificateTemplateAssetSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  certificate_template_asset_id?: boolean
  certificate_template_id?: boolean
  kind?: boolean
  storage_key?: boolean
  file_name?: boolean
  content_type?: boolean
  byte_size?: boolean
  createdAt?: boolean
  template?: boolean | Prisma.CertificateTemplateDefaultArgs<ExtArgs>
}, ExtArgs["result"]["certificateTemplateAsset"]>

export type CertificateTemplateAssetSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  certificate_template_asset_id?: boolean
  certificate_template_id?: boolean
  kind?: boolean
  storage_key?: boolean
  file_name?: boolean
  content_type?: boolean
  byte_size?: boolean
  createdAt?: boolean
  template?: boolean | Prisma.CertificateTemplateDefaultArgs<ExtArgs>
}, ExtArgs["result"]["certificateTemplateAsset"]>

export type CertificateTemplateAssetSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  certificate_template_asset_id?: boolean
  certificate_template_id?: boolean
  kind?: boolean
  storage_key?: boolean
  file_name?: boolean
  content_type?: boolean
  byte_size?: boolean
  createdAt?: boolean
  template?: boolean | Prisma.CertificateTemplateDefaultArgs<ExtArgs>
}, ExtArgs["result"]["certificateTemplateAsset"]>

export type CertificateTemplateAssetSelectScalar = {
  certificate_template_asset_id?: boolean
  certificate_template_id?: boolean
  kind?: boolean
  storage_key?: boolean
  file_name?: boolean
  content_type?: boolean
  byte_size?: boolean
  createdAt?: boolean
}

export type CertificateTemplateAssetOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"certificate_template_asset_id" | "certificate_template_id" | "kind" | "storage_key" | "file_name" | "content_type" | "byte_size" | "createdAt", ExtArgs["result"]["certificateTemplateAsset"]>
export type CertificateTemplateAssetInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  template?: boolean | Prisma.CertificateTemplateDefaultArgs<ExtArgs>
}
export type CertificateTemplateAssetIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  template?: boolean | Prisma.CertificateTemplateDefaultArgs<ExtArgs>
}
export type CertificateTemplateAssetIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  template?: boolean | Prisma.CertificateTemplateDefaultArgs<ExtArgs>
}

export type $CertificateTemplateAssetPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CertificateTemplateAsset"
  objects: {
    template: Prisma.$CertificateTemplatePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    certificate_template_asset_id: string
    certificate_template_id: string
    kind: $Enums.CertificateAssetKind
    /**
     * S3 object key, not a URL — the bucket and region are configuration.
     */
    storage_key: string
    file_name: string
    content_type: string
    byte_size: number
    createdAt: Date
  }, ExtArgs["result"]["certificateTemplateAsset"]>
  composites: {}
}

export type CertificateTemplateAssetGetPayload<S extends boolean | null | undefined | CertificateTemplateAssetDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CertificateTemplateAssetPayload, S>

export type CertificateTemplateAssetCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CertificateTemplateAssetFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CertificateTemplateAssetCountAggregateInputType | true
  }

export interface CertificateTemplateAssetDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CertificateTemplateAsset'], meta: { name: 'CertificateTemplateAsset' } }
  /**
   * Find zero or one CertificateTemplateAsset that matches the filter.
   * @param {CertificateTemplateAssetFindUniqueArgs} args - Arguments to find a CertificateTemplateAsset
   * @example
   * // Get one CertificateTemplateAsset
   * const certificateTemplateAsset = await prisma.certificateTemplateAsset.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CertificateTemplateAssetFindUniqueArgs>(args: Prisma.SelectSubset<T, CertificateTemplateAssetFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CertificateTemplateAssetClient<runtime.Types.Result.GetResult<Prisma.$CertificateTemplateAssetPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CertificateTemplateAsset that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CertificateTemplateAssetFindUniqueOrThrowArgs} args - Arguments to find a CertificateTemplateAsset
   * @example
   * // Get one CertificateTemplateAsset
   * const certificateTemplateAsset = await prisma.certificateTemplateAsset.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CertificateTemplateAssetFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CertificateTemplateAssetFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CertificateTemplateAssetClient<runtime.Types.Result.GetResult<Prisma.$CertificateTemplateAssetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CertificateTemplateAsset that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CertificateTemplateAssetFindFirstArgs} args - Arguments to find a CertificateTemplateAsset
   * @example
   * // Get one CertificateTemplateAsset
   * const certificateTemplateAsset = await prisma.certificateTemplateAsset.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CertificateTemplateAssetFindFirstArgs>(args?: Prisma.SelectSubset<T, CertificateTemplateAssetFindFirstArgs<ExtArgs>>): Prisma.Prisma__CertificateTemplateAssetClient<runtime.Types.Result.GetResult<Prisma.$CertificateTemplateAssetPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CertificateTemplateAsset that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CertificateTemplateAssetFindFirstOrThrowArgs} args - Arguments to find a CertificateTemplateAsset
   * @example
   * // Get one CertificateTemplateAsset
   * const certificateTemplateAsset = await prisma.certificateTemplateAsset.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CertificateTemplateAssetFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CertificateTemplateAssetFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CertificateTemplateAssetClient<runtime.Types.Result.GetResult<Prisma.$CertificateTemplateAssetPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CertificateTemplateAssets that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CertificateTemplateAssetFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CertificateTemplateAssets
   * const certificateTemplateAssets = await prisma.certificateTemplateAsset.findMany()
   * 
   * // Get first 10 CertificateTemplateAssets
   * const certificateTemplateAssets = await prisma.certificateTemplateAsset.findMany({ take: 10 })
   * 
   * // Only select the `certificate_template_asset_id`
   * const certificateTemplateAssetWithCertificate_template_asset_idOnly = await prisma.certificateTemplateAsset.findMany({ select: { certificate_template_asset_id: true } })
   * 
   */
  findMany<T extends CertificateTemplateAssetFindManyArgs>(args?: Prisma.SelectSubset<T, CertificateTemplateAssetFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CertificateTemplateAssetPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CertificateTemplateAsset.
   * @param {CertificateTemplateAssetCreateArgs} args - Arguments to create a CertificateTemplateAsset.
   * @example
   * // Create one CertificateTemplateAsset
   * const CertificateTemplateAsset = await prisma.certificateTemplateAsset.create({
   *   data: {
   *     // ... data to create a CertificateTemplateAsset
   *   }
   * })
   * 
   */
  create<T extends CertificateTemplateAssetCreateArgs>(args: Prisma.SelectSubset<T, CertificateTemplateAssetCreateArgs<ExtArgs>>): Prisma.Prisma__CertificateTemplateAssetClient<runtime.Types.Result.GetResult<Prisma.$CertificateTemplateAssetPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CertificateTemplateAssets.
   * @param {CertificateTemplateAssetCreateManyArgs} args - Arguments to create many CertificateTemplateAssets.
   * @example
   * // Create many CertificateTemplateAssets
   * const certificateTemplateAsset = await prisma.certificateTemplateAsset.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CertificateTemplateAssetCreateManyArgs>(args?: Prisma.SelectSubset<T, CertificateTemplateAssetCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CertificateTemplateAssets and returns the data saved in the database.
   * @param {CertificateTemplateAssetCreateManyAndReturnArgs} args - Arguments to create many CertificateTemplateAssets.
   * @example
   * // Create many CertificateTemplateAssets
   * const certificateTemplateAsset = await prisma.certificateTemplateAsset.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CertificateTemplateAssets and only return the `certificate_template_asset_id`
   * const certificateTemplateAssetWithCertificate_template_asset_idOnly = await prisma.certificateTemplateAsset.createManyAndReturn({
   *   select: { certificate_template_asset_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CertificateTemplateAssetCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CertificateTemplateAssetCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CertificateTemplateAssetPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CertificateTemplateAsset.
   * @param {CertificateTemplateAssetDeleteArgs} args - Arguments to delete one CertificateTemplateAsset.
   * @example
   * // Delete one CertificateTemplateAsset
   * const CertificateTemplateAsset = await prisma.certificateTemplateAsset.delete({
   *   where: {
   *     // ... filter to delete one CertificateTemplateAsset
   *   }
   * })
   * 
   */
  delete<T extends CertificateTemplateAssetDeleteArgs>(args: Prisma.SelectSubset<T, CertificateTemplateAssetDeleteArgs<ExtArgs>>): Prisma.Prisma__CertificateTemplateAssetClient<runtime.Types.Result.GetResult<Prisma.$CertificateTemplateAssetPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CertificateTemplateAsset.
   * @param {CertificateTemplateAssetUpdateArgs} args - Arguments to update one CertificateTemplateAsset.
   * @example
   * // Update one CertificateTemplateAsset
   * const certificateTemplateAsset = await prisma.certificateTemplateAsset.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CertificateTemplateAssetUpdateArgs>(args: Prisma.SelectSubset<T, CertificateTemplateAssetUpdateArgs<ExtArgs>>): Prisma.Prisma__CertificateTemplateAssetClient<runtime.Types.Result.GetResult<Prisma.$CertificateTemplateAssetPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CertificateTemplateAssets.
   * @param {CertificateTemplateAssetDeleteManyArgs} args - Arguments to filter CertificateTemplateAssets to delete.
   * @example
   * // Delete a few CertificateTemplateAssets
   * const { count } = await prisma.certificateTemplateAsset.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CertificateTemplateAssetDeleteManyArgs>(args?: Prisma.SelectSubset<T, CertificateTemplateAssetDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CertificateTemplateAssets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CertificateTemplateAssetUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CertificateTemplateAssets
   * const certificateTemplateAsset = await prisma.certificateTemplateAsset.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CertificateTemplateAssetUpdateManyArgs>(args: Prisma.SelectSubset<T, CertificateTemplateAssetUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CertificateTemplateAssets and returns the data updated in the database.
   * @param {CertificateTemplateAssetUpdateManyAndReturnArgs} args - Arguments to update many CertificateTemplateAssets.
   * @example
   * // Update many CertificateTemplateAssets
   * const certificateTemplateAsset = await prisma.certificateTemplateAsset.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CertificateTemplateAssets and only return the `certificate_template_asset_id`
   * const certificateTemplateAssetWithCertificate_template_asset_idOnly = await prisma.certificateTemplateAsset.updateManyAndReturn({
   *   select: { certificate_template_asset_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CertificateTemplateAssetUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CertificateTemplateAssetUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CertificateTemplateAssetPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CertificateTemplateAsset.
   * @param {CertificateTemplateAssetUpsertArgs} args - Arguments to update or create a CertificateTemplateAsset.
   * @example
   * // Update or create a CertificateTemplateAsset
   * const certificateTemplateAsset = await prisma.certificateTemplateAsset.upsert({
   *   create: {
   *     // ... data to create a CertificateTemplateAsset
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CertificateTemplateAsset we want to update
   *   }
   * })
   */
  upsert<T extends CertificateTemplateAssetUpsertArgs>(args: Prisma.SelectSubset<T, CertificateTemplateAssetUpsertArgs<ExtArgs>>): Prisma.Prisma__CertificateTemplateAssetClient<runtime.Types.Result.GetResult<Prisma.$CertificateTemplateAssetPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CertificateTemplateAssets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CertificateTemplateAssetCountArgs} args - Arguments to filter CertificateTemplateAssets to count.
   * @example
   * // Count the number of CertificateTemplateAssets
   * const count = await prisma.certificateTemplateAsset.count({
   *   where: {
   *     // ... the filter for the CertificateTemplateAssets we want to count
   *   }
   * })
  **/
  count<T extends CertificateTemplateAssetCountArgs>(
    args?: Prisma.Subset<T, CertificateTemplateAssetCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CertificateTemplateAssetCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CertificateTemplateAsset.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CertificateTemplateAssetAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CertificateTemplateAssetAggregateArgs>(args: Prisma.Subset<T, CertificateTemplateAssetAggregateArgs>): Prisma.PrismaPromise<GetCertificateTemplateAssetAggregateType<T>>

  /**
   * Group by CertificateTemplateAsset.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CertificateTemplateAssetGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CertificateTemplateAssetGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CertificateTemplateAssetGroupByArgs['orderBy'] }
      : { orderBy?: CertificateTemplateAssetGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CertificateTemplateAssetGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCertificateTemplateAssetGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CertificateTemplateAsset model
 */
readonly fields: CertificateTemplateAssetFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CertificateTemplateAsset.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CertificateTemplateAssetClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  template<T extends Prisma.CertificateTemplateDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CertificateTemplateDefaultArgs<ExtArgs>>): Prisma.Prisma__CertificateTemplateClient<runtime.Types.Result.GetResult<Prisma.$CertificateTemplatePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CertificateTemplateAsset model
 */
export interface CertificateTemplateAssetFieldRefs {
  readonly certificate_template_asset_id: Prisma.FieldRef<"CertificateTemplateAsset", 'String'>
  readonly certificate_template_id: Prisma.FieldRef<"CertificateTemplateAsset", 'String'>
  readonly kind: Prisma.FieldRef<"CertificateTemplateAsset", 'CertificateAssetKind'>
  readonly storage_key: Prisma.FieldRef<"CertificateTemplateAsset", 'String'>
  readonly file_name: Prisma.FieldRef<"CertificateTemplateAsset", 'String'>
  readonly content_type: Prisma.FieldRef<"CertificateTemplateAsset", 'String'>
  readonly byte_size: Prisma.FieldRef<"CertificateTemplateAsset", 'Int'>
  readonly createdAt: Prisma.FieldRef<"CertificateTemplateAsset", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CertificateTemplateAsset findUnique
 */
export type CertificateTemplateAssetFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateTemplateAsset
   */
  select?: Prisma.CertificateTemplateAssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateTemplateAsset
   */
  omit?: Prisma.CertificateTemplateAssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateTemplateAssetInclude<ExtArgs> | null
  /**
   * Filter, which CertificateTemplateAsset to fetch.
   */
  where: Prisma.CertificateTemplateAssetWhereUniqueInput
}

/**
 * CertificateTemplateAsset findUniqueOrThrow
 */
export type CertificateTemplateAssetFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateTemplateAsset
   */
  select?: Prisma.CertificateTemplateAssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateTemplateAsset
   */
  omit?: Prisma.CertificateTemplateAssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateTemplateAssetInclude<ExtArgs> | null
  /**
   * Filter, which CertificateTemplateAsset to fetch.
   */
  where: Prisma.CertificateTemplateAssetWhereUniqueInput
}

/**
 * CertificateTemplateAsset findFirst
 */
export type CertificateTemplateAssetFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateTemplateAsset
   */
  select?: Prisma.CertificateTemplateAssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateTemplateAsset
   */
  omit?: Prisma.CertificateTemplateAssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateTemplateAssetInclude<ExtArgs> | null
  /**
   * Filter, which CertificateTemplateAsset to fetch.
   */
  where?: Prisma.CertificateTemplateAssetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CertificateTemplateAssets to fetch.
   */
  orderBy?: Prisma.CertificateTemplateAssetOrderByWithRelationInput | Prisma.CertificateTemplateAssetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CertificateTemplateAssets.
   */
  cursor?: Prisma.CertificateTemplateAssetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CertificateTemplateAssets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CertificateTemplateAssets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CertificateTemplateAssets.
   */
  distinct?: Prisma.CertificateTemplateAssetScalarFieldEnum | Prisma.CertificateTemplateAssetScalarFieldEnum[]
}

/**
 * CertificateTemplateAsset findFirstOrThrow
 */
export type CertificateTemplateAssetFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateTemplateAsset
   */
  select?: Prisma.CertificateTemplateAssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateTemplateAsset
   */
  omit?: Prisma.CertificateTemplateAssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateTemplateAssetInclude<ExtArgs> | null
  /**
   * Filter, which CertificateTemplateAsset to fetch.
   */
  where?: Prisma.CertificateTemplateAssetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CertificateTemplateAssets to fetch.
   */
  orderBy?: Prisma.CertificateTemplateAssetOrderByWithRelationInput | Prisma.CertificateTemplateAssetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CertificateTemplateAssets.
   */
  cursor?: Prisma.CertificateTemplateAssetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CertificateTemplateAssets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CertificateTemplateAssets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CertificateTemplateAssets.
   */
  distinct?: Prisma.CertificateTemplateAssetScalarFieldEnum | Prisma.CertificateTemplateAssetScalarFieldEnum[]
}

/**
 * CertificateTemplateAsset findMany
 */
export type CertificateTemplateAssetFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateTemplateAsset
   */
  select?: Prisma.CertificateTemplateAssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateTemplateAsset
   */
  omit?: Prisma.CertificateTemplateAssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateTemplateAssetInclude<ExtArgs> | null
  /**
   * Filter, which CertificateTemplateAssets to fetch.
   */
  where?: Prisma.CertificateTemplateAssetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CertificateTemplateAssets to fetch.
   */
  orderBy?: Prisma.CertificateTemplateAssetOrderByWithRelationInput | Prisma.CertificateTemplateAssetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CertificateTemplateAssets.
   */
  cursor?: Prisma.CertificateTemplateAssetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CertificateTemplateAssets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CertificateTemplateAssets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CertificateTemplateAssets.
   */
  distinct?: Prisma.CertificateTemplateAssetScalarFieldEnum | Prisma.CertificateTemplateAssetScalarFieldEnum[]
}

/**
 * CertificateTemplateAsset create
 */
export type CertificateTemplateAssetCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateTemplateAsset
   */
  select?: Prisma.CertificateTemplateAssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateTemplateAsset
   */
  omit?: Prisma.CertificateTemplateAssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateTemplateAssetInclude<ExtArgs> | null
  /**
   * The data needed to create a CertificateTemplateAsset.
   */
  data: Prisma.XOR<Prisma.CertificateTemplateAssetCreateInput, Prisma.CertificateTemplateAssetUncheckedCreateInput>
}

/**
 * CertificateTemplateAsset createMany
 */
export type CertificateTemplateAssetCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CertificateTemplateAssets.
   */
  data: Prisma.CertificateTemplateAssetCreateManyInput | Prisma.CertificateTemplateAssetCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CertificateTemplateAsset createManyAndReturn
 */
export type CertificateTemplateAssetCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateTemplateAsset
   */
  select?: Prisma.CertificateTemplateAssetSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateTemplateAsset
   */
  omit?: Prisma.CertificateTemplateAssetOmit<ExtArgs> | null
  /**
   * The data used to create many CertificateTemplateAssets.
   */
  data: Prisma.CertificateTemplateAssetCreateManyInput | Prisma.CertificateTemplateAssetCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateTemplateAssetIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CertificateTemplateAsset update
 */
export type CertificateTemplateAssetUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateTemplateAsset
   */
  select?: Prisma.CertificateTemplateAssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateTemplateAsset
   */
  omit?: Prisma.CertificateTemplateAssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateTemplateAssetInclude<ExtArgs> | null
  /**
   * The data needed to update a CertificateTemplateAsset.
   */
  data: Prisma.XOR<Prisma.CertificateTemplateAssetUpdateInput, Prisma.CertificateTemplateAssetUncheckedUpdateInput>
  /**
   * Choose, which CertificateTemplateAsset to update.
   */
  where: Prisma.CertificateTemplateAssetWhereUniqueInput
}

/**
 * CertificateTemplateAsset updateMany
 */
export type CertificateTemplateAssetUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CertificateTemplateAssets.
   */
  data: Prisma.XOR<Prisma.CertificateTemplateAssetUpdateManyMutationInput, Prisma.CertificateTemplateAssetUncheckedUpdateManyInput>
  /**
   * Filter which CertificateTemplateAssets to update
   */
  where?: Prisma.CertificateTemplateAssetWhereInput
  /**
   * Limit how many CertificateTemplateAssets to update.
   */
  limit?: number
}

/**
 * CertificateTemplateAsset updateManyAndReturn
 */
export type CertificateTemplateAssetUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateTemplateAsset
   */
  select?: Prisma.CertificateTemplateAssetSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateTemplateAsset
   */
  omit?: Prisma.CertificateTemplateAssetOmit<ExtArgs> | null
  /**
   * The data used to update CertificateTemplateAssets.
   */
  data: Prisma.XOR<Prisma.CertificateTemplateAssetUpdateManyMutationInput, Prisma.CertificateTemplateAssetUncheckedUpdateManyInput>
  /**
   * Filter which CertificateTemplateAssets to update
   */
  where?: Prisma.CertificateTemplateAssetWhereInput
  /**
   * Limit how many CertificateTemplateAssets to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateTemplateAssetIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CertificateTemplateAsset upsert
 */
export type CertificateTemplateAssetUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateTemplateAsset
   */
  select?: Prisma.CertificateTemplateAssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateTemplateAsset
   */
  omit?: Prisma.CertificateTemplateAssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateTemplateAssetInclude<ExtArgs> | null
  /**
   * The filter to search for the CertificateTemplateAsset to update in case it exists.
   */
  where: Prisma.CertificateTemplateAssetWhereUniqueInput
  /**
   * In case the CertificateTemplateAsset found by the `where` argument doesn't exist, create a new CertificateTemplateAsset with this data.
   */
  create: Prisma.XOR<Prisma.CertificateTemplateAssetCreateInput, Prisma.CertificateTemplateAssetUncheckedCreateInput>
  /**
   * In case the CertificateTemplateAsset was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CertificateTemplateAssetUpdateInput, Prisma.CertificateTemplateAssetUncheckedUpdateInput>
}

/**
 * CertificateTemplateAsset delete
 */
export type CertificateTemplateAssetDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateTemplateAsset
   */
  select?: Prisma.CertificateTemplateAssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateTemplateAsset
   */
  omit?: Prisma.CertificateTemplateAssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateTemplateAssetInclude<ExtArgs> | null
  /**
   * Filter which CertificateTemplateAsset to delete.
   */
  where: Prisma.CertificateTemplateAssetWhereUniqueInput
}

/**
 * CertificateTemplateAsset deleteMany
 */
export type CertificateTemplateAssetDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CertificateTemplateAssets to delete
   */
  where?: Prisma.CertificateTemplateAssetWhereInput
  /**
   * Limit how many CertificateTemplateAssets to delete.
   */
  limit?: number
}

/**
 * CertificateTemplateAsset without action
 */
export type CertificateTemplateAssetDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateTemplateAsset
   */
  select?: Prisma.CertificateTemplateAssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateTemplateAsset
   */
  omit?: Prisma.CertificateTemplateAssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateTemplateAssetInclude<ExtArgs> | null
}
