
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Donation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Donation
 * The donation ledger the portal's Donation Tracking works and the donor app's
 * Activity tab reads. A money row is opened by the gateway callback once a
 * checkout is paid; a goods row is opened when the donor pledges. Only CONFIRMED
 * rows count towards the donor board.
 */
export type DonationModel = runtime.Types.Result.DefaultSelection<Prisma.$DonationPayload>

export type AggregateDonation = {
  _count: DonationCountAggregateOutputType | null
  _avg: DonationAvgAggregateOutputType | null
  _sum: DonationSumAggregateOutputType | null
  _min: DonationMinAggregateOutputType | null
  _max: DonationMaxAggregateOutputType | null
}

export type DonationAvgAggregateOutputType = {
  sequence: number | null
  event_id: number | null
  amount: number | null
  goods_quantity: number | null
}

export type DonationSumAggregateOutputType = {
  sequence: number | null
  event_id: number | null
  amount: number | null
  goods_quantity: number | null
}

export type DonationMinAggregateOutputType = {
  donation_id: string | null
  sequence: number | null
  user_id: string | null
  event_id: number | null
  kind: $Enums.DonationKind | null
  status: $Enums.DonationStatus | null
  amount: number | null
  payment_id: string | null
  goods_type: string | null
  goods_item: string | null
  goods_quantity: number | null
  donor_contact: string | null
  delivery_date: Date | null
  confirmed_at: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DonationMaxAggregateOutputType = {
  donation_id: string | null
  sequence: number | null
  user_id: string | null
  event_id: number | null
  kind: $Enums.DonationKind | null
  status: $Enums.DonationStatus | null
  amount: number | null
  payment_id: string | null
  goods_type: string | null
  goods_item: string | null
  goods_quantity: number | null
  donor_contact: string | null
  delivery_date: Date | null
  confirmed_at: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DonationCountAggregateOutputType = {
  donation_id: number
  sequence: number
  user_id: number
  event_id: number
  kind: number
  status: number
  amount: number
  payment_id: number
  goods_type: number
  goods_item: number
  goods_quantity: number
  donor_contact: number
  delivery_date: number
  confirmed_at: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type DonationAvgAggregateInputType = {
  sequence?: true
  event_id?: true
  amount?: true
  goods_quantity?: true
}

export type DonationSumAggregateInputType = {
  sequence?: true
  event_id?: true
  amount?: true
  goods_quantity?: true
}

export type DonationMinAggregateInputType = {
  donation_id?: true
  sequence?: true
  user_id?: true
  event_id?: true
  kind?: true
  status?: true
  amount?: true
  payment_id?: true
  goods_type?: true
  goods_item?: true
  goods_quantity?: true
  donor_contact?: true
  delivery_date?: true
  confirmed_at?: true
  createdAt?: true
  updatedAt?: true
}

export type DonationMaxAggregateInputType = {
  donation_id?: true
  sequence?: true
  user_id?: true
  event_id?: true
  kind?: true
  status?: true
  amount?: true
  payment_id?: true
  goods_type?: true
  goods_item?: true
  goods_quantity?: true
  donor_contact?: true
  delivery_date?: true
  confirmed_at?: true
  createdAt?: true
  updatedAt?: true
}

export type DonationCountAggregateInputType = {
  donation_id?: true
  sequence?: true
  user_id?: true
  event_id?: true
  kind?: true
  status?: true
  amount?: true
  payment_id?: true
  goods_type?: true
  goods_item?: true
  goods_quantity?: true
  donor_contact?: true
  delivery_date?: true
  confirmed_at?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type DonationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Donation to aggregate.
   */
  where?: Prisma.DonationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Donations to fetch.
   */
  orderBy?: Prisma.DonationOrderByWithRelationInput | Prisma.DonationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DonationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Donations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Donations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Donations
  **/
  _count?: true | DonationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DonationAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DonationSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DonationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DonationMaxAggregateInputType
}

export type GetDonationAggregateType<T extends DonationAggregateArgs> = {
      [P in keyof T & keyof AggregateDonation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDonation[P]>
    : Prisma.GetScalarType<T[P], AggregateDonation[P]>
}




export type DonationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DonationWhereInput
  orderBy?: Prisma.DonationOrderByWithAggregationInput | Prisma.DonationOrderByWithAggregationInput[]
  by: Prisma.DonationScalarFieldEnum[] | Prisma.DonationScalarFieldEnum
  having?: Prisma.DonationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DonationCountAggregateInputType | true
  _avg?: DonationAvgAggregateInputType
  _sum?: DonationSumAggregateInputType
  _min?: DonationMinAggregateInputType
  _max?: DonationMaxAggregateInputType
}

export type DonationGroupByOutputType = {
  donation_id: string
  sequence: number
  user_id: string
  event_id: number
  kind: $Enums.DonationKind
  status: $Enums.DonationStatus
  amount: number
  payment_id: string | null
  goods_type: string | null
  goods_item: string | null
  goods_quantity: number | null
  donor_contact: string | null
  delivery_date: Date | null
  confirmed_at: Date | null
  createdAt: Date
  updatedAt: Date
  _count: DonationCountAggregateOutputType | null
  _avg: DonationAvgAggregateOutputType | null
  _sum: DonationSumAggregateOutputType | null
  _min: DonationMinAggregateOutputType | null
  _max: DonationMaxAggregateOutputType | null
}

export type GetDonationGroupByPayload<T extends DonationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DonationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DonationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DonationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DonationGroupByOutputType[P]>
      }
    >
  >



export type DonationWhereInput = {
  AND?: Prisma.DonationWhereInput | Prisma.DonationWhereInput[]
  OR?: Prisma.DonationWhereInput[]
  NOT?: Prisma.DonationWhereInput | Prisma.DonationWhereInput[]
  donation_id?: Prisma.StringFilter<"Donation"> | string
  sequence?: Prisma.IntFilter<"Donation"> | number
  user_id?: Prisma.StringFilter<"Donation"> | string
  event_id?: Prisma.IntFilter<"Donation"> | number
  kind?: Prisma.EnumDonationKindFilter<"Donation"> | $Enums.DonationKind
  status?: Prisma.EnumDonationStatusFilter<"Donation"> | $Enums.DonationStatus
  amount?: Prisma.IntFilter<"Donation"> | number
  payment_id?: Prisma.StringNullableFilter<"Donation"> | string | null
  goods_type?: Prisma.StringNullableFilter<"Donation"> | string | null
  goods_item?: Prisma.StringNullableFilter<"Donation"> | string | null
  goods_quantity?: Prisma.IntNullableFilter<"Donation"> | number | null
  donor_contact?: Prisma.StringNullableFilter<"Donation"> | string | null
  delivery_date?: Prisma.DateTimeNullableFilter<"Donation"> | Date | string | null
  confirmed_at?: Prisma.DateTimeNullableFilter<"Donation"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Donation"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Donation"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
  payment?: Prisma.XOR<Prisma.DonationPaymentNullableScalarRelationFilter, Prisma.DonationPaymentWhereInput> | null
  trail?: Prisma.DonationTrailEntryListRelationFilter
}

export type DonationOrderByWithRelationInput = {
  donation_id?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  event_id?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  payment_id?: Prisma.SortOrderInput | Prisma.SortOrder
  goods_type?: Prisma.SortOrderInput | Prisma.SortOrder
  goods_item?: Prisma.SortOrderInput | Prisma.SortOrder
  goods_quantity?: Prisma.SortOrderInput | Prisma.SortOrder
  donor_contact?: Prisma.SortOrderInput | Prisma.SortOrder
  delivery_date?: Prisma.SortOrderInput | Prisma.SortOrder
  confirmed_at?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  event?: Prisma.EventOrderByWithRelationInput
  payment?: Prisma.DonationPaymentOrderByWithRelationInput
  trail?: Prisma.DonationTrailEntryOrderByRelationAggregateInput
}

export type DonationWhereUniqueInput = Prisma.AtLeast<{
  donation_id?: string
  sequence?: number
  payment_id?: string
  AND?: Prisma.DonationWhereInput | Prisma.DonationWhereInput[]
  OR?: Prisma.DonationWhereInput[]
  NOT?: Prisma.DonationWhereInput | Prisma.DonationWhereInput[]
  user_id?: Prisma.StringFilter<"Donation"> | string
  event_id?: Prisma.IntFilter<"Donation"> | number
  kind?: Prisma.EnumDonationKindFilter<"Donation"> | $Enums.DonationKind
  status?: Prisma.EnumDonationStatusFilter<"Donation"> | $Enums.DonationStatus
  amount?: Prisma.IntFilter<"Donation"> | number
  goods_type?: Prisma.StringNullableFilter<"Donation"> | string | null
  goods_item?: Prisma.StringNullableFilter<"Donation"> | string | null
  goods_quantity?: Prisma.IntNullableFilter<"Donation"> | number | null
  donor_contact?: Prisma.StringNullableFilter<"Donation"> | string | null
  delivery_date?: Prisma.DateTimeNullableFilter<"Donation"> | Date | string | null
  confirmed_at?: Prisma.DateTimeNullableFilter<"Donation"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Donation"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Donation"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
  payment?: Prisma.XOR<Prisma.DonationPaymentNullableScalarRelationFilter, Prisma.DonationPaymentWhereInput> | null
  trail?: Prisma.DonationTrailEntryListRelationFilter
}, "donation_id" | "sequence" | "payment_id">

export type DonationOrderByWithAggregationInput = {
  donation_id?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  event_id?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  payment_id?: Prisma.SortOrderInput | Prisma.SortOrder
  goods_type?: Prisma.SortOrderInput | Prisma.SortOrder
  goods_item?: Prisma.SortOrderInput | Prisma.SortOrder
  goods_quantity?: Prisma.SortOrderInput | Prisma.SortOrder
  donor_contact?: Prisma.SortOrderInput | Prisma.SortOrder
  delivery_date?: Prisma.SortOrderInput | Prisma.SortOrder
  confirmed_at?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.DonationCountOrderByAggregateInput
  _avg?: Prisma.DonationAvgOrderByAggregateInput
  _max?: Prisma.DonationMaxOrderByAggregateInput
  _min?: Prisma.DonationMinOrderByAggregateInput
  _sum?: Prisma.DonationSumOrderByAggregateInput
}

export type DonationScalarWhereWithAggregatesInput = {
  AND?: Prisma.DonationScalarWhereWithAggregatesInput | Prisma.DonationScalarWhereWithAggregatesInput[]
  OR?: Prisma.DonationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DonationScalarWhereWithAggregatesInput | Prisma.DonationScalarWhereWithAggregatesInput[]
  donation_id?: Prisma.StringWithAggregatesFilter<"Donation"> | string
  sequence?: Prisma.IntWithAggregatesFilter<"Donation"> | number
  user_id?: Prisma.StringWithAggregatesFilter<"Donation"> | string
  event_id?: Prisma.IntWithAggregatesFilter<"Donation"> | number
  kind?: Prisma.EnumDonationKindWithAggregatesFilter<"Donation"> | $Enums.DonationKind
  status?: Prisma.EnumDonationStatusWithAggregatesFilter<"Donation"> | $Enums.DonationStatus
  amount?: Prisma.IntWithAggregatesFilter<"Donation"> | number
  payment_id?: Prisma.StringNullableWithAggregatesFilter<"Donation"> | string | null
  goods_type?: Prisma.StringNullableWithAggregatesFilter<"Donation"> | string | null
  goods_item?: Prisma.StringNullableWithAggregatesFilter<"Donation"> | string | null
  goods_quantity?: Prisma.IntNullableWithAggregatesFilter<"Donation"> | number | null
  donor_contact?: Prisma.StringNullableWithAggregatesFilter<"Donation"> | string | null
  delivery_date?: Prisma.DateTimeNullableWithAggregatesFilter<"Donation"> | Date | string | null
  confirmed_at?: Prisma.DateTimeNullableWithAggregatesFilter<"Donation"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Donation"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Donation"> | Date | string
}

export type DonationCreateInput = {
  donation_id?: string
  sequence?: number
  kind: $Enums.DonationKind
  status?: $Enums.DonationStatus
  amount: number
  goods_type?: string | null
  goods_item?: string | null
  goods_quantity?: number | null
  donor_contact?: string | null
  delivery_date?: Date | string | null
  confirmed_at?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutDonationsInput
  event: Prisma.EventCreateNestedOneWithoutDonationsInput
  payment?: Prisma.DonationPaymentCreateNestedOneWithoutDonationInput
  trail?: Prisma.DonationTrailEntryCreateNestedManyWithoutDonationInput
}

export type DonationUncheckedCreateInput = {
  donation_id?: string
  sequence?: number
  user_id: string
  event_id: number
  kind: $Enums.DonationKind
  status?: $Enums.DonationStatus
  amount: number
  payment_id?: string | null
  goods_type?: string | null
  goods_item?: string | null
  goods_quantity?: number | null
  donor_contact?: string | null
  delivery_date?: Date | string | null
  confirmed_at?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  trail?: Prisma.DonationTrailEntryUncheckedCreateNestedManyWithoutDonationInput
}

export type DonationUpdateInput = {
  donation_id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumDonationKindFieldUpdateOperationsInput | $Enums.DonationKind
  status?: Prisma.EnumDonationStatusFieldUpdateOperationsInput | $Enums.DonationStatus
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  goods_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_item?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_quantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  donor_contact?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutDonationsNestedInput
  event?: Prisma.EventUpdateOneRequiredWithoutDonationsNestedInput
  payment?: Prisma.DonationPaymentUpdateOneWithoutDonationNestedInput
  trail?: Prisma.DonationTrailEntryUpdateManyWithoutDonationNestedInput
}

export type DonationUncheckedUpdateInput = {
  donation_id?: Prisma.StringFieldUpdateOperationsInput | string
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  event_id?: Prisma.IntFieldUpdateOperationsInput | number
  kind?: Prisma.EnumDonationKindFieldUpdateOperationsInput | $Enums.DonationKind
  status?: Prisma.EnumDonationStatusFieldUpdateOperationsInput | $Enums.DonationStatus
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  payment_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_item?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_quantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  donor_contact?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  trail?: Prisma.DonationTrailEntryUncheckedUpdateManyWithoutDonationNestedInput
}

export type DonationCreateManyInput = {
  donation_id?: string
  sequence?: number
  user_id: string
  event_id: number
  kind: $Enums.DonationKind
  status?: $Enums.DonationStatus
  amount: number
  payment_id?: string | null
  goods_type?: string | null
  goods_item?: string | null
  goods_quantity?: number | null
  donor_contact?: string | null
  delivery_date?: Date | string | null
  confirmed_at?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DonationUpdateManyMutationInput = {
  donation_id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumDonationKindFieldUpdateOperationsInput | $Enums.DonationKind
  status?: Prisma.EnumDonationStatusFieldUpdateOperationsInput | $Enums.DonationStatus
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  goods_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_item?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_quantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  donor_contact?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DonationUncheckedUpdateManyInput = {
  donation_id?: Prisma.StringFieldUpdateOperationsInput | string
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  event_id?: Prisma.IntFieldUpdateOperationsInput | number
  kind?: Prisma.EnumDonationKindFieldUpdateOperationsInput | $Enums.DonationKind
  status?: Prisma.EnumDonationStatusFieldUpdateOperationsInput | $Enums.DonationStatus
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  payment_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_item?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_quantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  donor_contact?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DonationListRelationFilter = {
  every?: Prisma.DonationWhereInput
  some?: Prisma.DonationWhereInput
  none?: Prisma.DonationWhereInput
}

export type DonationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DonationNullableScalarRelationFilter = {
  is?: Prisma.DonationWhereInput | null
  isNot?: Prisma.DonationWhereInput | null
}

export type DonationCountOrderByAggregateInput = {
  donation_id?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  event_id?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  payment_id?: Prisma.SortOrder
  goods_type?: Prisma.SortOrder
  goods_item?: Prisma.SortOrder
  goods_quantity?: Prisma.SortOrder
  donor_contact?: Prisma.SortOrder
  delivery_date?: Prisma.SortOrder
  confirmed_at?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DonationAvgOrderByAggregateInput = {
  sequence?: Prisma.SortOrder
  event_id?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  goods_quantity?: Prisma.SortOrder
}

export type DonationMaxOrderByAggregateInput = {
  donation_id?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  event_id?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  payment_id?: Prisma.SortOrder
  goods_type?: Prisma.SortOrder
  goods_item?: Prisma.SortOrder
  goods_quantity?: Prisma.SortOrder
  donor_contact?: Prisma.SortOrder
  delivery_date?: Prisma.SortOrder
  confirmed_at?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DonationMinOrderByAggregateInput = {
  donation_id?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  event_id?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  payment_id?: Prisma.SortOrder
  goods_type?: Prisma.SortOrder
  goods_item?: Prisma.SortOrder
  goods_quantity?: Prisma.SortOrder
  donor_contact?: Prisma.SortOrder
  delivery_date?: Prisma.SortOrder
  confirmed_at?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DonationSumOrderByAggregateInput = {
  sequence?: Prisma.SortOrder
  event_id?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  goods_quantity?: Prisma.SortOrder
}

export type DonationScalarRelationFilter = {
  is?: Prisma.DonationWhereInput
  isNot?: Prisma.DonationWhereInput
}

export type DonationCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.DonationCreateWithoutUserInput, Prisma.DonationUncheckedCreateWithoutUserInput> | Prisma.DonationCreateWithoutUserInput[] | Prisma.DonationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DonationCreateOrConnectWithoutUserInput | Prisma.DonationCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.DonationCreateManyUserInputEnvelope
  connect?: Prisma.DonationWhereUniqueInput | Prisma.DonationWhereUniqueInput[]
}

export type DonationUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.DonationCreateWithoutUserInput, Prisma.DonationUncheckedCreateWithoutUserInput> | Prisma.DonationCreateWithoutUserInput[] | Prisma.DonationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DonationCreateOrConnectWithoutUserInput | Prisma.DonationCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.DonationCreateManyUserInputEnvelope
  connect?: Prisma.DonationWhereUniqueInput | Prisma.DonationWhereUniqueInput[]
}

export type DonationUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.DonationCreateWithoutUserInput, Prisma.DonationUncheckedCreateWithoutUserInput> | Prisma.DonationCreateWithoutUserInput[] | Prisma.DonationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DonationCreateOrConnectWithoutUserInput | Prisma.DonationCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.DonationUpsertWithWhereUniqueWithoutUserInput | Prisma.DonationUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.DonationCreateManyUserInputEnvelope
  set?: Prisma.DonationWhereUniqueInput | Prisma.DonationWhereUniqueInput[]
  disconnect?: Prisma.DonationWhereUniqueInput | Prisma.DonationWhereUniqueInput[]
  delete?: Prisma.DonationWhereUniqueInput | Prisma.DonationWhereUniqueInput[]
  connect?: Prisma.DonationWhereUniqueInput | Prisma.DonationWhereUniqueInput[]
  update?: Prisma.DonationUpdateWithWhereUniqueWithoutUserInput | Prisma.DonationUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.DonationUpdateManyWithWhereWithoutUserInput | Prisma.DonationUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.DonationScalarWhereInput | Prisma.DonationScalarWhereInput[]
}

export type DonationUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.DonationCreateWithoutUserInput, Prisma.DonationUncheckedCreateWithoutUserInput> | Prisma.DonationCreateWithoutUserInput[] | Prisma.DonationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DonationCreateOrConnectWithoutUserInput | Prisma.DonationCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.DonationUpsertWithWhereUniqueWithoutUserInput | Prisma.DonationUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.DonationCreateManyUserInputEnvelope
  set?: Prisma.DonationWhereUniqueInput | Prisma.DonationWhereUniqueInput[]
  disconnect?: Prisma.DonationWhereUniqueInput | Prisma.DonationWhereUniqueInput[]
  delete?: Prisma.DonationWhereUniqueInput | Prisma.DonationWhereUniqueInput[]
  connect?: Prisma.DonationWhereUniqueInput | Prisma.DonationWhereUniqueInput[]
  update?: Prisma.DonationUpdateWithWhereUniqueWithoutUserInput | Prisma.DonationUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.DonationUpdateManyWithWhereWithoutUserInput | Prisma.DonationUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.DonationScalarWhereInput | Prisma.DonationScalarWhereInput[]
}

export type DonationCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.DonationCreateWithoutEventInput, Prisma.DonationUncheckedCreateWithoutEventInput> | Prisma.DonationCreateWithoutEventInput[] | Prisma.DonationUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.DonationCreateOrConnectWithoutEventInput | Prisma.DonationCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.DonationCreateManyEventInputEnvelope
  connect?: Prisma.DonationWhereUniqueInput | Prisma.DonationWhereUniqueInput[]
}

export type DonationUncheckedCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.DonationCreateWithoutEventInput, Prisma.DonationUncheckedCreateWithoutEventInput> | Prisma.DonationCreateWithoutEventInput[] | Prisma.DonationUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.DonationCreateOrConnectWithoutEventInput | Prisma.DonationCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.DonationCreateManyEventInputEnvelope
  connect?: Prisma.DonationWhereUniqueInput | Prisma.DonationWhereUniqueInput[]
}

export type DonationUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.DonationCreateWithoutEventInput, Prisma.DonationUncheckedCreateWithoutEventInput> | Prisma.DonationCreateWithoutEventInput[] | Prisma.DonationUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.DonationCreateOrConnectWithoutEventInput | Prisma.DonationCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.DonationUpsertWithWhereUniqueWithoutEventInput | Prisma.DonationUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.DonationCreateManyEventInputEnvelope
  set?: Prisma.DonationWhereUniqueInput | Prisma.DonationWhereUniqueInput[]
  disconnect?: Prisma.DonationWhereUniqueInput | Prisma.DonationWhereUniqueInput[]
  delete?: Prisma.DonationWhereUniqueInput | Prisma.DonationWhereUniqueInput[]
  connect?: Prisma.DonationWhereUniqueInput | Prisma.DonationWhereUniqueInput[]
  update?: Prisma.DonationUpdateWithWhereUniqueWithoutEventInput | Prisma.DonationUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.DonationUpdateManyWithWhereWithoutEventInput | Prisma.DonationUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.DonationScalarWhereInput | Prisma.DonationScalarWhereInput[]
}

export type DonationUncheckedUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.DonationCreateWithoutEventInput, Prisma.DonationUncheckedCreateWithoutEventInput> | Prisma.DonationCreateWithoutEventInput[] | Prisma.DonationUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.DonationCreateOrConnectWithoutEventInput | Prisma.DonationCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.DonationUpsertWithWhereUniqueWithoutEventInput | Prisma.DonationUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.DonationCreateManyEventInputEnvelope
  set?: Prisma.DonationWhereUniqueInput | Prisma.DonationWhereUniqueInput[]
  disconnect?: Prisma.DonationWhereUniqueInput | Prisma.DonationWhereUniqueInput[]
  delete?: Prisma.DonationWhereUniqueInput | Prisma.DonationWhereUniqueInput[]
  connect?: Prisma.DonationWhereUniqueInput | Prisma.DonationWhereUniqueInput[]
  update?: Prisma.DonationUpdateWithWhereUniqueWithoutEventInput | Prisma.DonationUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.DonationUpdateManyWithWhereWithoutEventInput | Prisma.DonationUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.DonationScalarWhereInput | Prisma.DonationScalarWhereInput[]
}

export type DonationCreateNestedOneWithoutPaymentInput = {
  create?: Prisma.XOR<Prisma.DonationCreateWithoutPaymentInput, Prisma.DonationUncheckedCreateWithoutPaymentInput>
  connectOrCreate?: Prisma.DonationCreateOrConnectWithoutPaymentInput
  connect?: Prisma.DonationWhereUniqueInput
}

export type DonationUncheckedCreateNestedOneWithoutPaymentInput = {
  create?: Prisma.XOR<Prisma.DonationCreateWithoutPaymentInput, Prisma.DonationUncheckedCreateWithoutPaymentInput>
  connectOrCreate?: Prisma.DonationCreateOrConnectWithoutPaymentInput
  connect?: Prisma.DonationWhereUniqueInput
}

export type DonationUpdateOneWithoutPaymentNestedInput = {
  create?: Prisma.XOR<Prisma.DonationCreateWithoutPaymentInput, Prisma.DonationUncheckedCreateWithoutPaymentInput>
  connectOrCreate?: Prisma.DonationCreateOrConnectWithoutPaymentInput
  upsert?: Prisma.DonationUpsertWithoutPaymentInput
  disconnect?: Prisma.DonationWhereInput | boolean
  delete?: Prisma.DonationWhereInput | boolean
  connect?: Prisma.DonationWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DonationUpdateToOneWithWhereWithoutPaymentInput, Prisma.DonationUpdateWithoutPaymentInput>, Prisma.DonationUncheckedUpdateWithoutPaymentInput>
}

export type DonationUncheckedUpdateOneWithoutPaymentNestedInput = {
  create?: Prisma.XOR<Prisma.DonationCreateWithoutPaymentInput, Prisma.DonationUncheckedCreateWithoutPaymentInput>
  connectOrCreate?: Prisma.DonationCreateOrConnectWithoutPaymentInput
  upsert?: Prisma.DonationUpsertWithoutPaymentInput
  disconnect?: Prisma.DonationWhereInput | boolean
  delete?: Prisma.DonationWhereInput | boolean
  connect?: Prisma.DonationWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DonationUpdateToOneWithWhereWithoutPaymentInput, Prisma.DonationUpdateWithoutPaymentInput>, Prisma.DonationUncheckedUpdateWithoutPaymentInput>
}

export type EnumDonationKindFieldUpdateOperationsInput = {
  set?: $Enums.DonationKind
}

export type EnumDonationStatusFieldUpdateOperationsInput = {
  set?: $Enums.DonationStatus
}

export type DonationCreateNestedOneWithoutTrailInput = {
  create?: Prisma.XOR<Prisma.DonationCreateWithoutTrailInput, Prisma.DonationUncheckedCreateWithoutTrailInput>
  connectOrCreate?: Prisma.DonationCreateOrConnectWithoutTrailInput
  connect?: Prisma.DonationWhereUniqueInput
}

export type DonationUpdateOneRequiredWithoutTrailNestedInput = {
  create?: Prisma.XOR<Prisma.DonationCreateWithoutTrailInput, Prisma.DonationUncheckedCreateWithoutTrailInput>
  connectOrCreate?: Prisma.DonationCreateOrConnectWithoutTrailInput
  upsert?: Prisma.DonationUpsertWithoutTrailInput
  connect?: Prisma.DonationWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DonationUpdateToOneWithWhereWithoutTrailInput, Prisma.DonationUpdateWithoutTrailInput>, Prisma.DonationUncheckedUpdateWithoutTrailInput>
}

export type DonationCreateWithoutUserInput = {
  donation_id?: string
  sequence?: number
  kind: $Enums.DonationKind
  status?: $Enums.DonationStatus
  amount: number
  goods_type?: string | null
  goods_item?: string | null
  goods_quantity?: number | null
  donor_contact?: string | null
  delivery_date?: Date | string | null
  confirmed_at?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  event: Prisma.EventCreateNestedOneWithoutDonationsInput
  payment?: Prisma.DonationPaymentCreateNestedOneWithoutDonationInput
  trail?: Prisma.DonationTrailEntryCreateNestedManyWithoutDonationInput
}

export type DonationUncheckedCreateWithoutUserInput = {
  donation_id?: string
  sequence?: number
  event_id: number
  kind: $Enums.DonationKind
  status?: $Enums.DonationStatus
  amount: number
  payment_id?: string | null
  goods_type?: string | null
  goods_item?: string | null
  goods_quantity?: number | null
  donor_contact?: string | null
  delivery_date?: Date | string | null
  confirmed_at?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  trail?: Prisma.DonationTrailEntryUncheckedCreateNestedManyWithoutDonationInput
}

export type DonationCreateOrConnectWithoutUserInput = {
  where: Prisma.DonationWhereUniqueInput
  create: Prisma.XOR<Prisma.DonationCreateWithoutUserInput, Prisma.DonationUncheckedCreateWithoutUserInput>
}

export type DonationCreateManyUserInputEnvelope = {
  data: Prisma.DonationCreateManyUserInput | Prisma.DonationCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type DonationUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.DonationWhereUniqueInput
  update: Prisma.XOR<Prisma.DonationUpdateWithoutUserInput, Prisma.DonationUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.DonationCreateWithoutUserInput, Prisma.DonationUncheckedCreateWithoutUserInput>
}

export type DonationUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.DonationWhereUniqueInput
  data: Prisma.XOR<Prisma.DonationUpdateWithoutUserInput, Prisma.DonationUncheckedUpdateWithoutUserInput>
}

export type DonationUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.DonationScalarWhereInput
  data: Prisma.XOR<Prisma.DonationUpdateManyMutationInput, Prisma.DonationUncheckedUpdateManyWithoutUserInput>
}

export type DonationScalarWhereInput = {
  AND?: Prisma.DonationScalarWhereInput | Prisma.DonationScalarWhereInput[]
  OR?: Prisma.DonationScalarWhereInput[]
  NOT?: Prisma.DonationScalarWhereInput | Prisma.DonationScalarWhereInput[]
  donation_id?: Prisma.StringFilter<"Donation"> | string
  sequence?: Prisma.IntFilter<"Donation"> | number
  user_id?: Prisma.StringFilter<"Donation"> | string
  event_id?: Prisma.IntFilter<"Donation"> | number
  kind?: Prisma.EnumDonationKindFilter<"Donation"> | $Enums.DonationKind
  status?: Prisma.EnumDonationStatusFilter<"Donation"> | $Enums.DonationStatus
  amount?: Prisma.IntFilter<"Donation"> | number
  payment_id?: Prisma.StringNullableFilter<"Donation"> | string | null
  goods_type?: Prisma.StringNullableFilter<"Donation"> | string | null
  goods_item?: Prisma.StringNullableFilter<"Donation"> | string | null
  goods_quantity?: Prisma.IntNullableFilter<"Donation"> | number | null
  donor_contact?: Prisma.StringNullableFilter<"Donation"> | string | null
  delivery_date?: Prisma.DateTimeNullableFilter<"Donation"> | Date | string | null
  confirmed_at?: Prisma.DateTimeNullableFilter<"Donation"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Donation"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Donation"> | Date | string
}

export type DonationCreateWithoutEventInput = {
  donation_id?: string
  sequence?: number
  kind: $Enums.DonationKind
  status?: $Enums.DonationStatus
  amount: number
  goods_type?: string | null
  goods_item?: string | null
  goods_quantity?: number | null
  donor_contact?: string | null
  delivery_date?: Date | string | null
  confirmed_at?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutDonationsInput
  payment?: Prisma.DonationPaymentCreateNestedOneWithoutDonationInput
  trail?: Prisma.DonationTrailEntryCreateNestedManyWithoutDonationInput
}

export type DonationUncheckedCreateWithoutEventInput = {
  donation_id?: string
  sequence?: number
  user_id: string
  kind: $Enums.DonationKind
  status?: $Enums.DonationStatus
  amount: number
  payment_id?: string | null
  goods_type?: string | null
  goods_item?: string | null
  goods_quantity?: number | null
  donor_contact?: string | null
  delivery_date?: Date | string | null
  confirmed_at?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  trail?: Prisma.DonationTrailEntryUncheckedCreateNestedManyWithoutDonationInput
}

export type DonationCreateOrConnectWithoutEventInput = {
  where: Prisma.DonationWhereUniqueInput
  create: Prisma.XOR<Prisma.DonationCreateWithoutEventInput, Prisma.DonationUncheckedCreateWithoutEventInput>
}

export type DonationCreateManyEventInputEnvelope = {
  data: Prisma.DonationCreateManyEventInput | Prisma.DonationCreateManyEventInput[]
  skipDuplicates?: boolean
}

export type DonationUpsertWithWhereUniqueWithoutEventInput = {
  where: Prisma.DonationWhereUniqueInput
  update: Prisma.XOR<Prisma.DonationUpdateWithoutEventInput, Prisma.DonationUncheckedUpdateWithoutEventInput>
  create: Prisma.XOR<Prisma.DonationCreateWithoutEventInput, Prisma.DonationUncheckedCreateWithoutEventInput>
}

export type DonationUpdateWithWhereUniqueWithoutEventInput = {
  where: Prisma.DonationWhereUniqueInput
  data: Prisma.XOR<Prisma.DonationUpdateWithoutEventInput, Prisma.DonationUncheckedUpdateWithoutEventInput>
}

export type DonationUpdateManyWithWhereWithoutEventInput = {
  where: Prisma.DonationScalarWhereInput
  data: Prisma.XOR<Prisma.DonationUpdateManyMutationInput, Prisma.DonationUncheckedUpdateManyWithoutEventInput>
}

export type DonationCreateWithoutPaymentInput = {
  donation_id?: string
  sequence?: number
  kind: $Enums.DonationKind
  status?: $Enums.DonationStatus
  amount: number
  goods_type?: string | null
  goods_item?: string | null
  goods_quantity?: number | null
  donor_contact?: string | null
  delivery_date?: Date | string | null
  confirmed_at?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutDonationsInput
  event: Prisma.EventCreateNestedOneWithoutDonationsInput
  trail?: Prisma.DonationTrailEntryCreateNestedManyWithoutDonationInput
}

export type DonationUncheckedCreateWithoutPaymentInput = {
  donation_id?: string
  sequence?: number
  user_id: string
  event_id: number
  kind: $Enums.DonationKind
  status?: $Enums.DonationStatus
  amount: number
  goods_type?: string | null
  goods_item?: string | null
  goods_quantity?: number | null
  donor_contact?: string | null
  delivery_date?: Date | string | null
  confirmed_at?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  trail?: Prisma.DonationTrailEntryUncheckedCreateNestedManyWithoutDonationInput
}

export type DonationCreateOrConnectWithoutPaymentInput = {
  where: Prisma.DonationWhereUniqueInput
  create: Prisma.XOR<Prisma.DonationCreateWithoutPaymentInput, Prisma.DonationUncheckedCreateWithoutPaymentInput>
}

export type DonationUpsertWithoutPaymentInput = {
  update: Prisma.XOR<Prisma.DonationUpdateWithoutPaymentInput, Prisma.DonationUncheckedUpdateWithoutPaymentInput>
  create: Prisma.XOR<Prisma.DonationCreateWithoutPaymentInput, Prisma.DonationUncheckedCreateWithoutPaymentInput>
  where?: Prisma.DonationWhereInput
}

export type DonationUpdateToOneWithWhereWithoutPaymentInput = {
  where?: Prisma.DonationWhereInput
  data: Prisma.XOR<Prisma.DonationUpdateWithoutPaymentInput, Prisma.DonationUncheckedUpdateWithoutPaymentInput>
}

export type DonationUpdateWithoutPaymentInput = {
  donation_id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumDonationKindFieldUpdateOperationsInput | $Enums.DonationKind
  status?: Prisma.EnumDonationStatusFieldUpdateOperationsInput | $Enums.DonationStatus
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  goods_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_item?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_quantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  donor_contact?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutDonationsNestedInput
  event?: Prisma.EventUpdateOneRequiredWithoutDonationsNestedInput
  trail?: Prisma.DonationTrailEntryUpdateManyWithoutDonationNestedInput
}

export type DonationUncheckedUpdateWithoutPaymentInput = {
  donation_id?: Prisma.StringFieldUpdateOperationsInput | string
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  event_id?: Prisma.IntFieldUpdateOperationsInput | number
  kind?: Prisma.EnumDonationKindFieldUpdateOperationsInput | $Enums.DonationKind
  status?: Prisma.EnumDonationStatusFieldUpdateOperationsInput | $Enums.DonationStatus
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  goods_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_item?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_quantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  donor_contact?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  trail?: Prisma.DonationTrailEntryUncheckedUpdateManyWithoutDonationNestedInput
}

export type DonationCreateWithoutTrailInput = {
  donation_id?: string
  sequence?: number
  kind: $Enums.DonationKind
  status?: $Enums.DonationStatus
  amount: number
  goods_type?: string | null
  goods_item?: string | null
  goods_quantity?: number | null
  donor_contact?: string | null
  delivery_date?: Date | string | null
  confirmed_at?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutDonationsInput
  event: Prisma.EventCreateNestedOneWithoutDonationsInput
  payment?: Prisma.DonationPaymentCreateNestedOneWithoutDonationInput
}

export type DonationUncheckedCreateWithoutTrailInput = {
  donation_id?: string
  sequence?: number
  user_id: string
  event_id: number
  kind: $Enums.DonationKind
  status?: $Enums.DonationStatus
  amount: number
  payment_id?: string | null
  goods_type?: string | null
  goods_item?: string | null
  goods_quantity?: number | null
  donor_contact?: string | null
  delivery_date?: Date | string | null
  confirmed_at?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DonationCreateOrConnectWithoutTrailInput = {
  where: Prisma.DonationWhereUniqueInput
  create: Prisma.XOR<Prisma.DonationCreateWithoutTrailInput, Prisma.DonationUncheckedCreateWithoutTrailInput>
}

export type DonationUpsertWithoutTrailInput = {
  update: Prisma.XOR<Prisma.DonationUpdateWithoutTrailInput, Prisma.DonationUncheckedUpdateWithoutTrailInput>
  create: Prisma.XOR<Prisma.DonationCreateWithoutTrailInput, Prisma.DonationUncheckedCreateWithoutTrailInput>
  where?: Prisma.DonationWhereInput
}

export type DonationUpdateToOneWithWhereWithoutTrailInput = {
  where?: Prisma.DonationWhereInput
  data: Prisma.XOR<Prisma.DonationUpdateWithoutTrailInput, Prisma.DonationUncheckedUpdateWithoutTrailInput>
}

export type DonationUpdateWithoutTrailInput = {
  donation_id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumDonationKindFieldUpdateOperationsInput | $Enums.DonationKind
  status?: Prisma.EnumDonationStatusFieldUpdateOperationsInput | $Enums.DonationStatus
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  goods_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_item?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_quantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  donor_contact?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutDonationsNestedInput
  event?: Prisma.EventUpdateOneRequiredWithoutDonationsNestedInput
  payment?: Prisma.DonationPaymentUpdateOneWithoutDonationNestedInput
}

export type DonationUncheckedUpdateWithoutTrailInput = {
  donation_id?: Prisma.StringFieldUpdateOperationsInput | string
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  event_id?: Prisma.IntFieldUpdateOperationsInput | number
  kind?: Prisma.EnumDonationKindFieldUpdateOperationsInput | $Enums.DonationKind
  status?: Prisma.EnumDonationStatusFieldUpdateOperationsInput | $Enums.DonationStatus
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  payment_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_item?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_quantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  donor_contact?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DonationCreateManyUserInput = {
  donation_id?: string
  sequence?: number
  event_id: number
  kind: $Enums.DonationKind
  status?: $Enums.DonationStatus
  amount: number
  payment_id?: string | null
  goods_type?: string | null
  goods_item?: string | null
  goods_quantity?: number | null
  donor_contact?: string | null
  delivery_date?: Date | string | null
  confirmed_at?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DonationUpdateWithoutUserInput = {
  donation_id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumDonationKindFieldUpdateOperationsInput | $Enums.DonationKind
  status?: Prisma.EnumDonationStatusFieldUpdateOperationsInput | $Enums.DonationStatus
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  goods_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_item?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_quantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  donor_contact?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  event?: Prisma.EventUpdateOneRequiredWithoutDonationsNestedInput
  payment?: Prisma.DonationPaymentUpdateOneWithoutDonationNestedInput
  trail?: Prisma.DonationTrailEntryUpdateManyWithoutDonationNestedInput
}

export type DonationUncheckedUpdateWithoutUserInput = {
  donation_id?: Prisma.StringFieldUpdateOperationsInput | string
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  event_id?: Prisma.IntFieldUpdateOperationsInput | number
  kind?: Prisma.EnumDonationKindFieldUpdateOperationsInput | $Enums.DonationKind
  status?: Prisma.EnumDonationStatusFieldUpdateOperationsInput | $Enums.DonationStatus
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  payment_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_item?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_quantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  donor_contact?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  trail?: Prisma.DonationTrailEntryUncheckedUpdateManyWithoutDonationNestedInput
}

export type DonationUncheckedUpdateManyWithoutUserInput = {
  donation_id?: Prisma.StringFieldUpdateOperationsInput | string
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  event_id?: Prisma.IntFieldUpdateOperationsInput | number
  kind?: Prisma.EnumDonationKindFieldUpdateOperationsInput | $Enums.DonationKind
  status?: Prisma.EnumDonationStatusFieldUpdateOperationsInput | $Enums.DonationStatus
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  payment_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_item?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_quantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  donor_contact?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DonationCreateManyEventInput = {
  donation_id?: string
  sequence?: number
  user_id: string
  kind: $Enums.DonationKind
  status?: $Enums.DonationStatus
  amount: number
  payment_id?: string | null
  goods_type?: string | null
  goods_item?: string | null
  goods_quantity?: number | null
  donor_contact?: string | null
  delivery_date?: Date | string | null
  confirmed_at?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DonationUpdateWithoutEventInput = {
  donation_id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumDonationKindFieldUpdateOperationsInput | $Enums.DonationKind
  status?: Prisma.EnumDonationStatusFieldUpdateOperationsInput | $Enums.DonationStatus
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  goods_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_item?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_quantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  donor_contact?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutDonationsNestedInput
  payment?: Prisma.DonationPaymentUpdateOneWithoutDonationNestedInput
  trail?: Prisma.DonationTrailEntryUpdateManyWithoutDonationNestedInput
}

export type DonationUncheckedUpdateWithoutEventInput = {
  donation_id?: Prisma.StringFieldUpdateOperationsInput | string
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumDonationKindFieldUpdateOperationsInput | $Enums.DonationKind
  status?: Prisma.EnumDonationStatusFieldUpdateOperationsInput | $Enums.DonationStatus
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  payment_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_item?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_quantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  donor_contact?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  trail?: Prisma.DonationTrailEntryUncheckedUpdateManyWithoutDonationNestedInput
}

export type DonationUncheckedUpdateManyWithoutEventInput = {
  donation_id?: Prisma.StringFieldUpdateOperationsInput | string
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumDonationKindFieldUpdateOperationsInput | $Enums.DonationKind
  status?: Prisma.EnumDonationStatusFieldUpdateOperationsInput | $Enums.DonationStatus
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  payment_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_item?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  goods_quantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  donor_contact?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delivery_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  confirmed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type DonationCountOutputType
 */

export type DonationCountOutputType = {
  trail: number
}

export type DonationCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  trail?: boolean | DonationCountOutputTypeCountTrailArgs
}

/**
 * DonationCountOutputType without action
 */
export type DonationCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DonationCountOutputType
   */
  select?: Prisma.DonationCountOutputTypeSelect<ExtArgs> | null
}

/**
 * DonationCountOutputType without action
 */
export type DonationCountOutputTypeCountTrailArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DonationTrailEntryWhereInput
}


export type DonationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  donation_id?: boolean
  sequence?: boolean
  user_id?: boolean
  event_id?: boolean
  kind?: boolean
  status?: boolean
  amount?: boolean
  payment_id?: boolean
  goods_type?: boolean
  goods_item?: boolean
  goods_quantity?: boolean
  donor_contact?: boolean
  delivery_date?: boolean
  confirmed_at?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  payment?: boolean | Prisma.Donation$paymentArgs<ExtArgs>
  trail?: boolean | Prisma.Donation$trailArgs<ExtArgs>
  _count?: boolean | Prisma.DonationCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["donation"]>

export type DonationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  donation_id?: boolean
  sequence?: boolean
  user_id?: boolean
  event_id?: boolean
  kind?: boolean
  status?: boolean
  amount?: boolean
  payment_id?: boolean
  goods_type?: boolean
  goods_item?: boolean
  goods_quantity?: boolean
  donor_contact?: boolean
  delivery_date?: boolean
  confirmed_at?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  payment?: boolean | Prisma.Donation$paymentArgs<ExtArgs>
}, ExtArgs["result"]["donation"]>

export type DonationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  donation_id?: boolean
  sequence?: boolean
  user_id?: boolean
  event_id?: boolean
  kind?: boolean
  status?: boolean
  amount?: boolean
  payment_id?: boolean
  goods_type?: boolean
  goods_item?: boolean
  goods_quantity?: boolean
  donor_contact?: boolean
  delivery_date?: boolean
  confirmed_at?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  payment?: boolean | Prisma.Donation$paymentArgs<ExtArgs>
}, ExtArgs["result"]["donation"]>

export type DonationSelectScalar = {
  donation_id?: boolean
  sequence?: boolean
  user_id?: boolean
  event_id?: boolean
  kind?: boolean
  status?: boolean
  amount?: boolean
  payment_id?: boolean
  goods_type?: boolean
  goods_item?: boolean
  goods_quantity?: boolean
  donor_contact?: boolean
  delivery_date?: boolean
  confirmed_at?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type DonationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"donation_id" | "sequence" | "user_id" | "event_id" | "kind" | "status" | "amount" | "payment_id" | "goods_type" | "goods_item" | "goods_quantity" | "donor_contact" | "delivery_date" | "confirmed_at" | "createdAt" | "updatedAt", ExtArgs["result"]["donation"]>
export type DonationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  payment?: boolean | Prisma.Donation$paymentArgs<ExtArgs>
  trail?: boolean | Prisma.Donation$trailArgs<ExtArgs>
  _count?: boolean | Prisma.DonationCountOutputTypeDefaultArgs<ExtArgs>
}
export type DonationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  payment?: boolean | Prisma.Donation$paymentArgs<ExtArgs>
}
export type DonationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  payment?: boolean | Prisma.Donation$paymentArgs<ExtArgs>
}

export type $DonationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Donation"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    event: Prisma.$EventPayload<ExtArgs>
    payment: Prisma.$DonationPaymentPayload<ExtArgs> | null
    trail: Prisma.$DonationTrailEntryPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    donation_id: string
    /**
     * Human tracking number — `DN-0007` is sequence 7.
     */
    sequence: number
    user_id: string
    event_id: number
    kind: $Enums.DonationKind
    status: $Enums.DonationStatus
    /**
     * Whole pesos: what was paid for money; the credited value of the goods
     * (goods-type value × quantity, snapshotted at pledge time) for goods.
     */
    amount: number
    payment_id: string | null
    /**
     * Goods only — the `goods_types` id on the event (`food`, `clothing`, …) or `other`.
     */
    goods_type: string | null
    /**
     * Goods only — what the donor said they are giving.
     */
    goods_item: string | null
    goods_quantity: number | null
    /**
     * Goods only — the number CARES can reach the donor on about the drop-off.
     */
    donor_contact: string | null
    /**
     * Goods only — the day the donor plans to hand the goods in at the CARES office.
     */
    delivery_date: Date | null
    confirmed_at: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["donation"]>
  composites: {}
}

export type DonationGetPayload<S extends boolean | null | undefined | DonationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DonationPayload, S>

export type DonationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DonationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DonationCountAggregateInputType | true
  }

export interface DonationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Donation'], meta: { name: 'Donation' } }
  /**
   * Find zero or one Donation that matches the filter.
   * @param {DonationFindUniqueArgs} args - Arguments to find a Donation
   * @example
   * // Get one Donation
   * const donation = await prisma.donation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DonationFindUniqueArgs>(args: Prisma.SelectSubset<T, DonationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DonationClient<runtime.Types.Result.GetResult<Prisma.$DonationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Donation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DonationFindUniqueOrThrowArgs} args - Arguments to find a Donation
   * @example
   * // Get one Donation
   * const donation = await prisma.donation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DonationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DonationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DonationClient<runtime.Types.Result.GetResult<Prisma.$DonationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Donation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DonationFindFirstArgs} args - Arguments to find a Donation
   * @example
   * // Get one Donation
   * const donation = await prisma.donation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DonationFindFirstArgs>(args?: Prisma.SelectSubset<T, DonationFindFirstArgs<ExtArgs>>): Prisma.Prisma__DonationClient<runtime.Types.Result.GetResult<Prisma.$DonationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Donation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DonationFindFirstOrThrowArgs} args - Arguments to find a Donation
   * @example
   * // Get one Donation
   * const donation = await prisma.donation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DonationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DonationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DonationClient<runtime.Types.Result.GetResult<Prisma.$DonationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Donations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DonationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Donations
   * const donations = await prisma.donation.findMany()
   * 
   * // Get first 10 Donations
   * const donations = await prisma.donation.findMany({ take: 10 })
   * 
   * // Only select the `donation_id`
   * const donationWithDonation_idOnly = await prisma.donation.findMany({ select: { donation_id: true } })
   * 
   */
  findMany<T extends DonationFindManyArgs>(args?: Prisma.SelectSubset<T, DonationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DonationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Donation.
   * @param {DonationCreateArgs} args - Arguments to create a Donation.
   * @example
   * // Create one Donation
   * const Donation = await prisma.donation.create({
   *   data: {
   *     // ... data to create a Donation
   *   }
   * })
   * 
   */
  create<T extends DonationCreateArgs>(args: Prisma.SelectSubset<T, DonationCreateArgs<ExtArgs>>): Prisma.Prisma__DonationClient<runtime.Types.Result.GetResult<Prisma.$DonationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Donations.
   * @param {DonationCreateManyArgs} args - Arguments to create many Donations.
   * @example
   * // Create many Donations
   * const donation = await prisma.donation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DonationCreateManyArgs>(args?: Prisma.SelectSubset<T, DonationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Donations and returns the data saved in the database.
   * @param {DonationCreateManyAndReturnArgs} args - Arguments to create many Donations.
   * @example
   * // Create many Donations
   * const donation = await prisma.donation.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Donations and only return the `donation_id`
   * const donationWithDonation_idOnly = await prisma.donation.createManyAndReturn({
   *   select: { donation_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DonationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DonationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DonationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Donation.
   * @param {DonationDeleteArgs} args - Arguments to delete one Donation.
   * @example
   * // Delete one Donation
   * const Donation = await prisma.donation.delete({
   *   where: {
   *     // ... filter to delete one Donation
   *   }
   * })
   * 
   */
  delete<T extends DonationDeleteArgs>(args: Prisma.SelectSubset<T, DonationDeleteArgs<ExtArgs>>): Prisma.Prisma__DonationClient<runtime.Types.Result.GetResult<Prisma.$DonationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Donation.
   * @param {DonationUpdateArgs} args - Arguments to update one Donation.
   * @example
   * // Update one Donation
   * const donation = await prisma.donation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DonationUpdateArgs>(args: Prisma.SelectSubset<T, DonationUpdateArgs<ExtArgs>>): Prisma.Prisma__DonationClient<runtime.Types.Result.GetResult<Prisma.$DonationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Donations.
   * @param {DonationDeleteManyArgs} args - Arguments to filter Donations to delete.
   * @example
   * // Delete a few Donations
   * const { count } = await prisma.donation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DonationDeleteManyArgs>(args?: Prisma.SelectSubset<T, DonationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Donations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DonationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Donations
   * const donation = await prisma.donation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DonationUpdateManyArgs>(args: Prisma.SelectSubset<T, DonationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Donations and returns the data updated in the database.
   * @param {DonationUpdateManyAndReturnArgs} args - Arguments to update many Donations.
   * @example
   * // Update many Donations
   * const donation = await prisma.donation.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Donations and only return the `donation_id`
   * const donationWithDonation_idOnly = await prisma.donation.updateManyAndReturn({
   *   select: { donation_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DonationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DonationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DonationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Donation.
   * @param {DonationUpsertArgs} args - Arguments to update or create a Donation.
   * @example
   * // Update or create a Donation
   * const donation = await prisma.donation.upsert({
   *   create: {
   *     // ... data to create a Donation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Donation we want to update
   *   }
   * })
   */
  upsert<T extends DonationUpsertArgs>(args: Prisma.SelectSubset<T, DonationUpsertArgs<ExtArgs>>): Prisma.Prisma__DonationClient<runtime.Types.Result.GetResult<Prisma.$DonationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Donations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DonationCountArgs} args - Arguments to filter Donations to count.
   * @example
   * // Count the number of Donations
   * const count = await prisma.donation.count({
   *   where: {
   *     // ... the filter for the Donations we want to count
   *   }
   * })
  **/
  count<T extends DonationCountArgs>(
    args?: Prisma.Subset<T, DonationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DonationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Donation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DonationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DonationAggregateArgs>(args: Prisma.Subset<T, DonationAggregateArgs>): Prisma.PrismaPromise<GetDonationAggregateType<T>>

  /**
   * Group by Donation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DonationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DonationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DonationGroupByArgs['orderBy'] }
      : { orderBy?: DonationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DonationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDonationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Donation model
 */
readonly fields: DonationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Donation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DonationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  event<T extends Prisma.EventDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventDefaultArgs<ExtArgs>>): Prisma.Prisma__EventClient<runtime.Types.Result.GetResult<Prisma.$EventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  payment<T extends Prisma.Donation$paymentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Donation$paymentArgs<ExtArgs>>): Prisma.Prisma__DonationPaymentClient<runtime.Types.Result.GetResult<Prisma.$DonationPaymentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  trail<T extends Prisma.Donation$trailArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Donation$trailArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DonationTrailEntryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Donation model
 */
export interface DonationFieldRefs {
  readonly donation_id: Prisma.FieldRef<"Donation", 'String'>
  readonly sequence: Prisma.FieldRef<"Donation", 'Int'>
  readonly user_id: Prisma.FieldRef<"Donation", 'String'>
  readonly event_id: Prisma.FieldRef<"Donation", 'Int'>
  readonly kind: Prisma.FieldRef<"Donation", 'DonationKind'>
  readonly status: Prisma.FieldRef<"Donation", 'DonationStatus'>
  readonly amount: Prisma.FieldRef<"Donation", 'Int'>
  readonly payment_id: Prisma.FieldRef<"Donation", 'String'>
  readonly goods_type: Prisma.FieldRef<"Donation", 'String'>
  readonly goods_item: Prisma.FieldRef<"Donation", 'String'>
  readonly goods_quantity: Prisma.FieldRef<"Donation", 'Int'>
  readonly donor_contact: Prisma.FieldRef<"Donation", 'String'>
  readonly delivery_date: Prisma.FieldRef<"Donation", 'DateTime'>
  readonly confirmed_at: Prisma.FieldRef<"Donation", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Donation", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Donation", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Donation findUnique
 */
export type DonationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donation
   */
  select?: Prisma.DonationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Donation
   */
  omit?: Prisma.DonationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonationInclude<ExtArgs> | null
  /**
   * Filter, which Donation to fetch.
   */
  where: Prisma.DonationWhereUniqueInput
}

/**
 * Donation findUniqueOrThrow
 */
export type DonationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donation
   */
  select?: Prisma.DonationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Donation
   */
  omit?: Prisma.DonationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonationInclude<ExtArgs> | null
  /**
   * Filter, which Donation to fetch.
   */
  where: Prisma.DonationWhereUniqueInput
}

/**
 * Donation findFirst
 */
export type DonationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donation
   */
  select?: Prisma.DonationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Donation
   */
  omit?: Prisma.DonationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonationInclude<ExtArgs> | null
  /**
   * Filter, which Donation to fetch.
   */
  where?: Prisma.DonationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Donations to fetch.
   */
  orderBy?: Prisma.DonationOrderByWithRelationInput | Prisma.DonationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Donations.
   */
  cursor?: Prisma.DonationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Donations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Donations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Donations.
   */
  distinct?: Prisma.DonationScalarFieldEnum | Prisma.DonationScalarFieldEnum[]
}

/**
 * Donation findFirstOrThrow
 */
export type DonationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donation
   */
  select?: Prisma.DonationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Donation
   */
  omit?: Prisma.DonationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonationInclude<ExtArgs> | null
  /**
   * Filter, which Donation to fetch.
   */
  where?: Prisma.DonationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Donations to fetch.
   */
  orderBy?: Prisma.DonationOrderByWithRelationInput | Prisma.DonationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Donations.
   */
  cursor?: Prisma.DonationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Donations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Donations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Donations.
   */
  distinct?: Prisma.DonationScalarFieldEnum | Prisma.DonationScalarFieldEnum[]
}

/**
 * Donation findMany
 */
export type DonationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donation
   */
  select?: Prisma.DonationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Donation
   */
  omit?: Prisma.DonationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonationInclude<ExtArgs> | null
  /**
   * Filter, which Donations to fetch.
   */
  where?: Prisma.DonationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Donations to fetch.
   */
  orderBy?: Prisma.DonationOrderByWithRelationInput | Prisma.DonationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Donations.
   */
  cursor?: Prisma.DonationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Donations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Donations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Donations.
   */
  distinct?: Prisma.DonationScalarFieldEnum | Prisma.DonationScalarFieldEnum[]
}

/**
 * Donation create
 */
export type DonationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donation
   */
  select?: Prisma.DonationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Donation
   */
  omit?: Prisma.DonationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonationInclude<ExtArgs> | null
  /**
   * The data needed to create a Donation.
   */
  data: Prisma.XOR<Prisma.DonationCreateInput, Prisma.DonationUncheckedCreateInput>
}

/**
 * Donation createMany
 */
export type DonationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Donations.
   */
  data: Prisma.DonationCreateManyInput | Prisma.DonationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Donation createManyAndReturn
 */
export type DonationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donation
   */
  select?: Prisma.DonationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Donation
   */
  omit?: Prisma.DonationOmit<ExtArgs> | null
  /**
   * The data used to create many Donations.
   */
  data: Prisma.DonationCreateManyInput | Prisma.DonationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Donation update
 */
export type DonationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donation
   */
  select?: Prisma.DonationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Donation
   */
  omit?: Prisma.DonationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonationInclude<ExtArgs> | null
  /**
   * The data needed to update a Donation.
   */
  data: Prisma.XOR<Prisma.DonationUpdateInput, Prisma.DonationUncheckedUpdateInput>
  /**
   * Choose, which Donation to update.
   */
  where: Prisma.DonationWhereUniqueInput
}

/**
 * Donation updateMany
 */
export type DonationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Donations.
   */
  data: Prisma.XOR<Prisma.DonationUpdateManyMutationInput, Prisma.DonationUncheckedUpdateManyInput>
  /**
   * Filter which Donations to update
   */
  where?: Prisma.DonationWhereInput
  /**
   * Limit how many Donations to update.
   */
  limit?: number
}

/**
 * Donation updateManyAndReturn
 */
export type DonationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donation
   */
  select?: Prisma.DonationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Donation
   */
  omit?: Prisma.DonationOmit<ExtArgs> | null
  /**
   * The data used to update Donations.
   */
  data: Prisma.XOR<Prisma.DonationUpdateManyMutationInput, Prisma.DonationUncheckedUpdateManyInput>
  /**
   * Filter which Donations to update
   */
  where?: Prisma.DonationWhereInput
  /**
   * Limit how many Donations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Donation upsert
 */
export type DonationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donation
   */
  select?: Prisma.DonationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Donation
   */
  omit?: Prisma.DonationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonationInclude<ExtArgs> | null
  /**
   * The filter to search for the Donation to update in case it exists.
   */
  where: Prisma.DonationWhereUniqueInput
  /**
   * In case the Donation found by the `where` argument doesn't exist, create a new Donation with this data.
   */
  create: Prisma.XOR<Prisma.DonationCreateInput, Prisma.DonationUncheckedCreateInput>
  /**
   * In case the Donation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DonationUpdateInput, Prisma.DonationUncheckedUpdateInput>
}

/**
 * Donation delete
 */
export type DonationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donation
   */
  select?: Prisma.DonationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Donation
   */
  omit?: Prisma.DonationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonationInclude<ExtArgs> | null
  /**
   * Filter which Donation to delete.
   */
  where: Prisma.DonationWhereUniqueInput
}

/**
 * Donation deleteMany
 */
export type DonationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Donations to delete
   */
  where?: Prisma.DonationWhereInput
  /**
   * Limit how many Donations to delete.
   */
  limit?: number
}

/**
 * Donation.payment
 */
export type Donation$paymentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DonationPayment
   */
  select?: Prisma.DonationPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DonationPayment
   */
  omit?: Prisma.DonationPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonationPaymentInclude<ExtArgs> | null
  where?: Prisma.DonationPaymentWhereInput
}

/**
 * Donation.trail
 */
export type Donation$trailArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DonationTrailEntry
   */
  select?: Prisma.DonationTrailEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the DonationTrailEntry
   */
  omit?: Prisma.DonationTrailEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonationTrailEntryInclude<ExtArgs> | null
  where?: Prisma.DonationTrailEntryWhereInput
  orderBy?: Prisma.DonationTrailEntryOrderByWithRelationInput | Prisma.DonationTrailEntryOrderByWithRelationInput[]
  cursor?: Prisma.DonationTrailEntryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DonationTrailEntryScalarFieldEnum | Prisma.DonationTrailEntryScalarFieldEnum[]
}

/**
 * Donation without action
 */
export type DonationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donation
   */
  select?: Prisma.DonationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Donation
   */
  omit?: Prisma.DonationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonationInclude<ExtArgs> | null
}
