
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MonthlyReportTrailEntry` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model MonthlyReportTrailEntry
 * Append-only history of the submission: who submitted, who decided, and the note
 * that came with it. This is the report's own record, kept beside the entry rather
 * than in the global audit log because the coordinator reads it too.
 */
export type MonthlyReportTrailEntryModel = runtime.Types.Result.DefaultSelection<Prisma.$MonthlyReportTrailEntryPayload>

export type AggregateMonthlyReportTrailEntry = {
  _count: MonthlyReportTrailEntryCountAggregateOutputType | null
  _min: MonthlyReportTrailEntryMinAggregateOutputType | null
  _max: MonthlyReportTrailEntryMaxAggregateOutputType | null
}

export type MonthlyReportTrailEntryMinAggregateOutputType = {
  monthly_report_trail_entry_id: string | null
  monthly_report_id: string | null
  action: $Enums.MonthlyReportTrailAction | null
  actor_name: string | null
  note: string | null
  createdAt: Date | null
}

export type MonthlyReportTrailEntryMaxAggregateOutputType = {
  monthly_report_trail_entry_id: string | null
  monthly_report_id: string | null
  action: $Enums.MonthlyReportTrailAction | null
  actor_name: string | null
  note: string | null
  createdAt: Date | null
}

export type MonthlyReportTrailEntryCountAggregateOutputType = {
  monthly_report_trail_entry_id: number
  monthly_report_id: number
  action: number
  actor_name: number
  note: number
  createdAt: number
  _all: number
}


export type MonthlyReportTrailEntryMinAggregateInputType = {
  monthly_report_trail_entry_id?: true
  monthly_report_id?: true
  action?: true
  actor_name?: true
  note?: true
  createdAt?: true
}

export type MonthlyReportTrailEntryMaxAggregateInputType = {
  monthly_report_trail_entry_id?: true
  monthly_report_id?: true
  action?: true
  actor_name?: true
  note?: true
  createdAt?: true
}

export type MonthlyReportTrailEntryCountAggregateInputType = {
  monthly_report_trail_entry_id?: true
  monthly_report_id?: true
  action?: true
  actor_name?: true
  note?: true
  createdAt?: true
  _all?: true
}

export type MonthlyReportTrailEntryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MonthlyReportTrailEntry to aggregate.
   */
  where?: Prisma.MonthlyReportTrailEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MonthlyReportTrailEntries to fetch.
   */
  orderBy?: Prisma.MonthlyReportTrailEntryOrderByWithRelationInput | Prisma.MonthlyReportTrailEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MonthlyReportTrailEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MonthlyReportTrailEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MonthlyReportTrailEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MonthlyReportTrailEntries
  **/
  _count?: true | MonthlyReportTrailEntryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MonthlyReportTrailEntryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MonthlyReportTrailEntryMaxAggregateInputType
}

export type GetMonthlyReportTrailEntryAggregateType<T extends MonthlyReportTrailEntryAggregateArgs> = {
      [P in keyof T & keyof AggregateMonthlyReportTrailEntry]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMonthlyReportTrailEntry[P]>
    : Prisma.GetScalarType<T[P], AggregateMonthlyReportTrailEntry[P]>
}




export type MonthlyReportTrailEntryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MonthlyReportTrailEntryWhereInput
  orderBy?: Prisma.MonthlyReportTrailEntryOrderByWithAggregationInput | Prisma.MonthlyReportTrailEntryOrderByWithAggregationInput[]
  by: Prisma.MonthlyReportTrailEntryScalarFieldEnum[] | Prisma.MonthlyReportTrailEntryScalarFieldEnum
  having?: Prisma.MonthlyReportTrailEntryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MonthlyReportTrailEntryCountAggregateInputType | true
  _min?: MonthlyReportTrailEntryMinAggregateInputType
  _max?: MonthlyReportTrailEntryMaxAggregateInputType
}

export type MonthlyReportTrailEntryGroupByOutputType = {
  monthly_report_trail_entry_id: string
  monthly_report_id: string
  action: $Enums.MonthlyReportTrailAction
  actor_name: string
  note: string | null
  createdAt: Date
  _count: MonthlyReportTrailEntryCountAggregateOutputType | null
  _min: MonthlyReportTrailEntryMinAggregateOutputType | null
  _max: MonthlyReportTrailEntryMaxAggregateOutputType | null
}

export type GetMonthlyReportTrailEntryGroupByPayload<T extends MonthlyReportTrailEntryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MonthlyReportTrailEntryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MonthlyReportTrailEntryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MonthlyReportTrailEntryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MonthlyReportTrailEntryGroupByOutputType[P]>
      }
    >
  >



export type MonthlyReportTrailEntryWhereInput = {
  AND?: Prisma.MonthlyReportTrailEntryWhereInput | Prisma.MonthlyReportTrailEntryWhereInput[]
  OR?: Prisma.MonthlyReportTrailEntryWhereInput[]
  NOT?: Prisma.MonthlyReportTrailEntryWhereInput | Prisma.MonthlyReportTrailEntryWhereInput[]
  monthly_report_trail_entry_id?: Prisma.StringFilter<"MonthlyReportTrailEntry"> | string
  monthly_report_id?: Prisma.StringFilter<"MonthlyReportTrailEntry"> | string
  action?: Prisma.EnumMonthlyReportTrailActionFilter<"MonthlyReportTrailEntry"> | $Enums.MonthlyReportTrailAction
  actor_name?: Prisma.StringFilter<"MonthlyReportTrailEntry"> | string
  note?: Prisma.StringNullableFilter<"MonthlyReportTrailEntry"> | string | null
  createdAt?: Prisma.DateTimeFilter<"MonthlyReportTrailEntry"> | Date | string
  report?: Prisma.XOR<Prisma.MonthlyReportScalarRelationFilter, Prisma.MonthlyReportWhereInput>
}

export type MonthlyReportTrailEntryOrderByWithRelationInput = {
  monthly_report_trail_entry_id?: Prisma.SortOrder
  monthly_report_id?: Prisma.SortOrder
  action?: Prisma.SortOrder
  actor_name?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  report?: Prisma.MonthlyReportOrderByWithRelationInput
}

export type MonthlyReportTrailEntryWhereUniqueInput = Prisma.AtLeast<{
  monthly_report_trail_entry_id?: string
  AND?: Prisma.MonthlyReportTrailEntryWhereInput | Prisma.MonthlyReportTrailEntryWhereInput[]
  OR?: Prisma.MonthlyReportTrailEntryWhereInput[]
  NOT?: Prisma.MonthlyReportTrailEntryWhereInput | Prisma.MonthlyReportTrailEntryWhereInput[]
  monthly_report_id?: Prisma.StringFilter<"MonthlyReportTrailEntry"> | string
  action?: Prisma.EnumMonthlyReportTrailActionFilter<"MonthlyReportTrailEntry"> | $Enums.MonthlyReportTrailAction
  actor_name?: Prisma.StringFilter<"MonthlyReportTrailEntry"> | string
  note?: Prisma.StringNullableFilter<"MonthlyReportTrailEntry"> | string | null
  createdAt?: Prisma.DateTimeFilter<"MonthlyReportTrailEntry"> | Date | string
  report?: Prisma.XOR<Prisma.MonthlyReportScalarRelationFilter, Prisma.MonthlyReportWhereInput>
}, "monthly_report_trail_entry_id">

export type MonthlyReportTrailEntryOrderByWithAggregationInput = {
  monthly_report_trail_entry_id?: Prisma.SortOrder
  monthly_report_id?: Prisma.SortOrder
  action?: Prisma.SortOrder
  actor_name?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.MonthlyReportTrailEntryCountOrderByAggregateInput
  _max?: Prisma.MonthlyReportTrailEntryMaxOrderByAggregateInput
  _min?: Prisma.MonthlyReportTrailEntryMinOrderByAggregateInput
}

export type MonthlyReportTrailEntryScalarWhereWithAggregatesInput = {
  AND?: Prisma.MonthlyReportTrailEntryScalarWhereWithAggregatesInput | Prisma.MonthlyReportTrailEntryScalarWhereWithAggregatesInput[]
  OR?: Prisma.MonthlyReportTrailEntryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MonthlyReportTrailEntryScalarWhereWithAggregatesInput | Prisma.MonthlyReportTrailEntryScalarWhereWithAggregatesInput[]
  monthly_report_trail_entry_id?: Prisma.StringWithAggregatesFilter<"MonthlyReportTrailEntry"> | string
  monthly_report_id?: Prisma.StringWithAggregatesFilter<"MonthlyReportTrailEntry"> | string
  action?: Prisma.EnumMonthlyReportTrailActionWithAggregatesFilter<"MonthlyReportTrailEntry"> | $Enums.MonthlyReportTrailAction
  actor_name?: Prisma.StringWithAggregatesFilter<"MonthlyReportTrailEntry"> | string
  note?: Prisma.StringNullableWithAggregatesFilter<"MonthlyReportTrailEntry"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MonthlyReportTrailEntry"> | Date | string
}

export type MonthlyReportTrailEntryCreateInput = {
  monthly_report_trail_entry_id?: string
  action: $Enums.MonthlyReportTrailAction
  actor_name: string
  note?: string | null
  createdAt?: Date | string
  report: Prisma.MonthlyReportCreateNestedOneWithoutTrailInput
}

export type MonthlyReportTrailEntryUncheckedCreateInput = {
  monthly_report_trail_entry_id?: string
  monthly_report_id: string
  action: $Enums.MonthlyReportTrailAction
  actor_name: string
  note?: string | null
  createdAt?: Date | string
}

export type MonthlyReportTrailEntryUpdateInput = {
  monthly_report_trail_entry_id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumMonthlyReportTrailActionFieldUpdateOperationsInput | $Enums.MonthlyReportTrailAction
  actor_name?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  report?: Prisma.MonthlyReportUpdateOneRequiredWithoutTrailNestedInput
}

export type MonthlyReportTrailEntryUncheckedUpdateInput = {
  monthly_report_trail_entry_id?: Prisma.StringFieldUpdateOperationsInput | string
  monthly_report_id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumMonthlyReportTrailActionFieldUpdateOperationsInput | $Enums.MonthlyReportTrailAction
  actor_name?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MonthlyReportTrailEntryCreateManyInput = {
  monthly_report_trail_entry_id?: string
  monthly_report_id: string
  action: $Enums.MonthlyReportTrailAction
  actor_name: string
  note?: string | null
  createdAt?: Date | string
}

export type MonthlyReportTrailEntryUpdateManyMutationInput = {
  monthly_report_trail_entry_id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumMonthlyReportTrailActionFieldUpdateOperationsInput | $Enums.MonthlyReportTrailAction
  actor_name?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MonthlyReportTrailEntryUncheckedUpdateManyInput = {
  monthly_report_trail_entry_id?: Prisma.StringFieldUpdateOperationsInput | string
  monthly_report_id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumMonthlyReportTrailActionFieldUpdateOperationsInput | $Enums.MonthlyReportTrailAction
  actor_name?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MonthlyReportTrailEntryListRelationFilter = {
  every?: Prisma.MonthlyReportTrailEntryWhereInput
  some?: Prisma.MonthlyReportTrailEntryWhereInput
  none?: Prisma.MonthlyReportTrailEntryWhereInput
}

export type MonthlyReportTrailEntryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MonthlyReportTrailEntryCountOrderByAggregateInput = {
  monthly_report_trail_entry_id?: Prisma.SortOrder
  monthly_report_id?: Prisma.SortOrder
  action?: Prisma.SortOrder
  actor_name?: Prisma.SortOrder
  note?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MonthlyReportTrailEntryMaxOrderByAggregateInput = {
  monthly_report_trail_entry_id?: Prisma.SortOrder
  monthly_report_id?: Prisma.SortOrder
  action?: Prisma.SortOrder
  actor_name?: Prisma.SortOrder
  note?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MonthlyReportTrailEntryMinOrderByAggregateInput = {
  monthly_report_trail_entry_id?: Prisma.SortOrder
  monthly_report_id?: Prisma.SortOrder
  action?: Prisma.SortOrder
  actor_name?: Prisma.SortOrder
  note?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MonthlyReportTrailEntryCreateNestedManyWithoutReportInput = {
  create?: Prisma.XOR<Prisma.MonthlyReportTrailEntryCreateWithoutReportInput, Prisma.MonthlyReportTrailEntryUncheckedCreateWithoutReportInput> | Prisma.MonthlyReportTrailEntryCreateWithoutReportInput[] | Prisma.MonthlyReportTrailEntryUncheckedCreateWithoutReportInput[]
  connectOrCreate?: Prisma.MonthlyReportTrailEntryCreateOrConnectWithoutReportInput | Prisma.MonthlyReportTrailEntryCreateOrConnectWithoutReportInput[]
  createMany?: Prisma.MonthlyReportTrailEntryCreateManyReportInputEnvelope
  connect?: Prisma.MonthlyReportTrailEntryWhereUniqueInput | Prisma.MonthlyReportTrailEntryWhereUniqueInput[]
}

export type MonthlyReportTrailEntryUncheckedCreateNestedManyWithoutReportInput = {
  create?: Prisma.XOR<Prisma.MonthlyReportTrailEntryCreateWithoutReportInput, Prisma.MonthlyReportTrailEntryUncheckedCreateWithoutReportInput> | Prisma.MonthlyReportTrailEntryCreateWithoutReportInput[] | Prisma.MonthlyReportTrailEntryUncheckedCreateWithoutReportInput[]
  connectOrCreate?: Prisma.MonthlyReportTrailEntryCreateOrConnectWithoutReportInput | Prisma.MonthlyReportTrailEntryCreateOrConnectWithoutReportInput[]
  createMany?: Prisma.MonthlyReportTrailEntryCreateManyReportInputEnvelope
  connect?: Prisma.MonthlyReportTrailEntryWhereUniqueInput | Prisma.MonthlyReportTrailEntryWhereUniqueInput[]
}

export type MonthlyReportTrailEntryUpdateManyWithoutReportNestedInput = {
  create?: Prisma.XOR<Prisma.MonthlyReportTrailEntryCreateWithoutReportInput, Prisma.MonthlyReportTrailEntryUncheckedCreateWithoutReportInput> | Prisma.MonthlyReportTrailEntryCreateWithoutReportInput[] | Prisma.MonthlyReportTrailEntryUncheckedCreateWithoutReportInput[]
  connectOrCreate?: Prisma.MonthlyReportTrailEntryCreateOrConnectWithoutReportInput | Prisma.MonthlyReportTrailEntryCreateOrConnectWithoutReportInput[]
  upsert?: Prisma.MonthlyReportTrailEntryUpsertWithWhereUniqueWithoutReportInput | Prisma.MonthlyReportTrailEntryUpsertWithWhereUniqueWithoutReportInput[]
  createMany?: Prisma.MonthlyReportTrailEntryCreateManyReportInputEnvelope
  set?: Prisma.MonthlyReportTrailEntryWhereUniqueInput | Prisma.MonthlyReportTrailEntryWhereUniqueInput[]
  disconnect?: Prisma.MonthlyReportTrailEntryWhereUniqueInput | Prisma.MonthlyReportTrailEntryWhereUniqueInput[]
  delete?: Prisma.MonthlyReportTrailEntryWhereUniqueInput | Prisma.MonthlyReportTrailEntryWhereUniqueInput[]
  connect?: Prisma.MonthlyReportTrailEntryWhereUniqueInput | Prisma.MonthlyReportTrailEntryWhereUniqueInput[]
  update?: Prisma.MonthlyReportTrailEntryUpdateWithWhereUniqueWithoutReportInput | Prisma.MonthlyReportTrailEntryUpdateWithWhereUniqueWithoutReportInput[]
  updateMany?: Prisma.MonthlyReportTrailEntryUpdateManyWithWhereWithoutReportInput | Prisma.MonthlyReportTrailEntryUpdateManyWithWhereWithoutReportInput[]
  deleteMany?: Prisma.MonthlyReportTrailEntryScalarWhereInput | Prisma.MonthlyReportTrailEntryScalarWhereInput[]
}

export type MonthlyReportTrailEntryUncheckedUpdateManyWithoutReportNestedInput = {
  create?: Prisma.XOR<Prisma.MonthlyReportTrailEntryCreateWithoutReportInput, Prisma.MonthlyReportTrailEntryUncheckedCreateWithoutReportInput> | Prisma.MonthlyReportTrailEntryCreateWithoutReportInput[] | Prisma.MonthlyReportTrailEntryUncheckedCreateWithoutReportInput[]
  connectOrCreate?: Prisma.MonthlyReportTrailEntryCreateOrConnectWithoutReportInput | Prisma.MonthlyReportTrailEntryCreateOrConnectWithoutReportInput[]
  upsert?: Prisma.MonthlyReportTrailEntryUpsertWithWhereUniqueWithoutReportInput | Prisma.MonthlyReportTrailEntryUpsertWithWhereUniqueWithoutReportInput[]
  createMany?: Prisma.MonthlyReportTrailEntryCreateManyReportInputEnvelope
  set?: Prisma.MonthlyReportTrailEntryWhereUniqueInput | Prisma.MonthlyReportTrailEntryWhereUniqueInput[]
  disconnect?: Prisma.MonthlyReportTrailEntryWhereUniqueInput | Prisma.MonthlyReportTrailEntryWhereUniqueInput[]
  delete?: Prisma.MonthlyReportTrailEntryWhereUniqueInput | Prisma.MonthlyReportTrailEntryWhereUniqueInput[]
  connect?: Prisma.MonthlyReportTrailEntryWhereUniqueInput | Prisma.MonthlyReportTrailEntryWhereUniqueInput[]
  update?: Prisma.MonthlyReportTrailEntryUpdateWithWhereUniqueWithoutReportInput | Prisma.MonthlyReportTrailEntryUpdateWithWhereUniqueWithoutReportInput[]
  updateMany?: Prisma.MonthlyReportTrailEntryUpdateManyWithWhereWithoutReportInput | Prisma.MonthlyReportTrailEntryUpdateManyWithWhereWithoutReportInput[]
  deleteMany?: Prisma.MonthlyReportTrailEntryScalarWhereInput | Prisma.MonthlyReportTrailEntryScalarWhereInput[]
}

export type EnumMonthlyReportTrailActionFieldUpdateOperationsInput = {
  set?: $Enums.MonthlyReportTrailAction
}

export type MonthlyReportTrailEntryCreateWithoutReportInput = {
  monthly_report_trail_entry_id?: string
  action: $Enums.MonthlyReportTrailAction
  actor_name: string
  note?: string | null
  createdAt?: Date | string
}

export type MonthlyReportTrailEntryUncheckedCreateWithoutReportInput = {
  monthly_report_trail_entry_id?: string
  action: $Enums.MonthlyReportTrailAction
  actor_name: string
  note?: string | null
  createdAt?: Date | string
}

export type MonthlyReportTrailEntryCreateOrConnectWithoutReportInput = {
  where: Prisma.MonthlyReportTrailEntryWhereUniqueInput
  create: Prisma.XOR<Prisma.MonthlyReportTrailEntryCreateWithoutReportInput, Prisma.MonthlyReportTrailEntryUncheckedCreateWithoutReportInput>
}

export type MonthlyReportTrailEntryCreateManyReportInputEnvelope = {
  data: Prisma.MonthlyReportTrailEntryCreateManyReportInput | Prisma.MonthlyReportTrailEntryCreateManyReportInput[]
  skipDuplicates?: boolean
}

export type MonthlyReportTrailEntryUpsertWithWhereUniqueWithoutReportInput = {
  where: Prisma.MonthlyReportTrailEntryWhereUniqueInput
  update: Prisma.XOR<Prisma.MonthlyReportTrailEntryUpdateWithoutReportInput, Prisma.MonthlyReportTrailEntryUncheckedUpdateWithoutReportInput>
  create: Prisma.XOR<Prisma.MonthlyReportTrailEntryCreateWithoutReportInput, Prisma.MonthlyReportTrailEntryUncheckedCreateWithoutReportInput>
}

export type MonthlyReportTrailEntryUpdateWithWhereUniqueWithoutReportInput = {
  where: Prisma.MonthlyReportTrailEntryWhereUniqueInput
  data: Prisma.XOR<Prisma.MonthlyReportTrailEntryUpdateWithoutReportInput, Prisma.MonthlyReportTrailEntryUncheckedUpdateWithoutReportInput>
}

export type MonthlyReportTrailEntryUpdateManyWithWhereWithoutReportInput = {
  where: Prisma.MonthlyReportTrailEntryScalarWhereInput
  data: Prisma.XOR<Prisma.MonthlyReportTrailEntryUpdateManyMutationInput, Prisma.MonthlyReportTrailEntryUncheckedUpdateManyWithoutReportInput>
}

export type MonthlyReportTrailEntryScalarWhereInput = {
  AND?: Prisma.MonthlyReportTrailEntryScalarWhereInput | Prisma.MonthlyReportTrailEntryScalarWhereInput[]
  OR?: Prisma.MonthlyReportTrailEntryScalarWhereInput[]
  NOT?: Prisma.MonthlyReportTrailEntryScalarWhereInput | Prisma.MonthlyReportTrailEntryScalarWhereInput[]
  monthly_report_trail_entry_id?: Prisma.StringFilter<"MonthlyReportTrailEntry"> | string
  monthly_report_id?: Prisma.StringFilter<"MonthlyReportTrailEntry"> | string
  action?: Prisma.EnumMonthlyReportTrailActionFilter<"MonthlyReportTrailEntry"> | $Enums.MonthlyReportTrailAction
  actor_name?: Prisma.StringFilter<"MonthlyReportTrailEntry"> | string
  note?: Prisma.StringNullableFilter<"MonthlyReportTrailEntry"> | string | null
  createdAt?: Prisma.DateTimeFilter<"MonthlyReportTrailEntry"> | Date | string
}

export type MonthlyReportTrailEntryCreateManyReportInput = {
  monthly_report_trail_entry_id?: string
  action: $Enums.MonthlyReportTrailAction
  actor_name: string
  note?: string | null
  createdAt?: Date | string
}

export type MonthlyReportTrailEntryUpdateWithoutReportInput = {
  monthly_report_trail_entry_id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumMonthlyReportTrailActionFieldUpdateOperationsInput | $Enums.MonthlyReportTrailAction
  actor_name?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MonthlyReportTrailEntryUncheckedUpdateWithoutReportInput = {
  monthly_report_trail_entry_id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumMonthlyReportTrailActionFieldUpdateOperationsInput | $Enums.MonthlyReportTrailAction
  actor_name?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MonthlyReportTrailEntryUncheckedUpdateManyWithoutReportInput = {
  monthly_report_trail_entry_id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumMonthlyReportTrailActionFieldUpdateOperationsInput | $Enums.MonthlyReportTrailAction
  actor_name?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type MonthlyReportTrailEntrySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  monthly_report_trail_entry_id?: boolean
  monthly_report_id?: boolean
  action?: boolean
  actor_name?: boolean
  note?: boolean
  createdAt?: boolean
  report?: boolean | Prisma.MonthlyReportDefaultArgs<ExtArgs>
}, ExtArgs["result"]["monthlyReportTrailEntry"]>

export type MonthlyReportTrailEntrySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  monthly_report_trail_entry_id?: boolean
  monthly_report_id?: boolean
  action?: boolean
  actor_name?: boolean
  note?: boolean
  createdAt?: boolean
  report?: boolean | Prisma.MonthlyReportDefaultArgs<ExtArgs>
}, ExtArgs["result"]["monthlyReportTrailEntry"]>

export type MonthlyReportTrailEntrySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  monthly_report_trail_entry_id?: boolean
  monthly_report_id?: boolean
  action?: boolean
  actor_name?: boolean
  note?: boolean
  createdAt?: boolean
  report?: boolean | Prisma.MonthlyReportDefaultArgs<ExtArgs>
}, ExtArgs["result"]["monthlyReportTrailEntry"]>

export type MonthlyReportTrailEntrySelectScalar = {
  monthly_report_trail_entry_id?: boolean
  monthly_report_id?: boolean
  action?: boolean
  actor_name?: boolean
  note?: boolean
  createdAt?: boolean
}

export type MonthlyReportTrailEntryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"monthly_report_trail_entry_id" | "monthly_report_id" | "action" | "actor_name" | "note" | "createdAt", ExtArgs["result"]["monthlyReportTrailEntry"]>
export type MonthlyReportTrailEntryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  report?: boolean | Prisma.MonthlyReportDefaultArgs<ExtArgs>
}
export type MonthlyReportTrailEntryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  report?: boolean | Prisma.MonthlyReportDefaultArgs<ExtArgs>
}
export type MonthlyReportTrailEntryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  report?: boolean | Prisma.MonthlyReportDefaultArgs<ExtArgs>
}

export type $MonthlyReportTrailEntryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MonthlyReportTrailEntry"
  objects: {
    report: Prisma.$MonthlyReportPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    monthly_report_trail_entry_id: string
    monthly_report_id: string
    action: $Enums.MonthlyReportTrailAction
    /**
     * Snapshot of the actor's name, so a rename cannot rewrite the trail.
     */
    actor_name: string
    note: string | null
    createdAt: Date
  }, ExtArgs["result"]["monthlyReportTrailEntry"]>
  composites: {}
}

export type MonthlyReportTrailEntryGetPayload<S extends boolean | null | undefined | MonthlyReportTrailEntryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MonthlyReportTrailEntryPayload, S>

export type MonthlyReportTrailEntryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MonthlyReportTrailEntryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MonthlyReportTrailEntryCountAggregateInputType | true
  }

export interface MonthlyReportTrailEntryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MonthlyReportTrailEntry'], meta: { name: 'MonthlyReportTrailEntry' } }
  /**
   * Find zero or one MonthlyReportTrailEntry that matches the filter.
   * @param {MonthlyReportTrailEntryFindUniqueArgs} args - Arguments to find a MonthlyReportTrailEntry
   * @example
   * // Get one MonthlyReportTrailEntry
   * const monthlyReportTrailEntry = await prisma.monthlyReportTrailEntry.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MonthlyReportTrailEntryFindUniqueArgs>(args: Prisma.SelectSubset<T, MonthlyReportTrailEntryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MonthlyReportTrailEntryClient<runtime.Types.Result.GetResult<Prisma.$MonthlyReportTrailEntryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MonthlyReportTrailEntry that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MonthlyReportTrailEntryFindUniqueOrThrowArgs} args - Arguments to find a MonthlyReportTrailEntry
   * @example
   * // Get one MonthlyReportTrailEntry
   * const monthlyReportTrailEntry = await prisma.monthlyReportTrailEntry.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MonthlyReportTrailEntryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MonthlyReportTrailEntryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MonthlyReportTrailEntryClient<runtime.Types.Result.GetResult<Prisma.$MonthlyReportTrailEntryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MonthlyReportTrailEntry that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MonthlyReportTrailEntryFindFirstArgs} args - Arguments to find a MonthlyReportTrailEntry
   * @example
   * // Get one MonthlyReportTrailEntry
   * const monthlyReportTrailEntry = await prisma.monthlyReportTrailEntry.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MonthlyReportTrailEntryFindFirstArgs>(args?: Prisma.SelectSubset<T, MonthlyReportTrailEntryFindFirstArgs<ExtArgs>>): Prisma.Prisma__MonthlyReportTrailEntryClient<runtime.Types.Result.GetResult<Prisma.$MonthlyReportTrailEntryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MonthlyReportTrailEntry that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MonthlyReportTrailEntryFindFirstOrThrowArgs} args - Arguments to find a MonthlyReportTrailEntry
   * @example
   * // Get one MonthlyReportTrailEntry
   * const monthlyReportTrailEntry = await prisma.monthlyReportTrailEntry.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MonthlyReportTrailEntryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MonthlyReportTrailEntryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MonthlyReportTrailEntryClient<runtime.Types.Result.GetResult<Prisma.$MonthlyReportTrailEntryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MonthlyReportTrailEntries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MonthlyReportTrailEntryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MonthlyReportTrailEntries
   * const monthlyReportTrailEntries = await prisma.monthlyReportTrailEntry.findMany()
   * 
   * // Get first 10 MonthlyReportTrailEntries
   * const monthlyReportTrailEntries = await prisma.monthlyReportTrailEntry.findMany({ take: 10 })
   * 
   * // Only select the `monthly_report_trail_entry_id`
   * const monthlyReportTrailEntryWithMonthly_report_trail_entry_idOnly = await prisma.monthlyReportTrailEntry.findMany({ select: { monthly_report_trail_entry_id: true } })
   * 
   */
  findMany<T extends MonthlyReportTrailEntryFindManyArgs>(args?: Prisma.SelectSubset<T, MonthlyReportTrailEntryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MonthlyReportTrailEntryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MonthlyReportTrailEntry.
   * @param {MonthlyReportTrailEntryCreateArgs} args - Arguments to create a MonthlyReportTrailEntry.
   * @example
   * // Create one MonthlyReportTrailEntry
   * const MonthlyReportTrailEntry = await prisma.monthlyReportTrailEntry.create({
   *   data: {
   *     // ... data to create a MonthlyReportTrailEntry
   *   }
   * })
   * 
   */
  create<T extends MonthlyReportTrailEntryCreateArgs>(args: Prisma.SelectSubset<T, MonthlyReportTrailEntryCreateArgs<ExtArgs>>): Prisma.Prisma__MonthlyReportTrailEntryClient<runtime.Types.Result.GetResult<Prisma.$MonthlyReportTrailEntryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MonthlyReportTrailEntries.
   * @param {MonthlyReportTrailEntryCreateManyArgs} args - Arguments to create many MonthlyReportTrailEntries.
   * @example
   * // Create many MonthlyReportTrailEntries
   * const monthlyReportTrailEntry = await prisma.monthlyReportTrailEntry.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MonthlyReportTrailEntryCreateManyArgs>(args?: Prisma.SelectSubset<T, MonthlyReportTrailEntryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MonthlyReportTrailEntries and returns the data saved in the database.
   * @param {MonthlyReportTrailEntryCreateManyAndReturnArgs} args - Arguments to create many MonthlyReportTrailEntries.
   * @example
   * // Create many MonthlyReportTrailEntries
   * const monthlyReportTrailEntry = await prisma.monthlyReportTrailEntry.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MonthlyReportTrailEntries and only return the `monthly_report_trail_entry_id`
   * const monthlyReportTrailEntryWithMonthly_report_trail_entry_idOnly = await prisma.monthlyReportTrailEntry.createManyAndReturn({
   *   select: { monthly_report_trail_entry_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MonthlyReportTrailEntryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MonthlyReportTrailEntryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MonthlyReportTrailEntryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MonthlyReportTrailEntry.
   * @param {MonthlyReportTrailEntryDeleteArgs} args - Arguments to delete one MonthlyReportTrailEntry.
   * @example
   * // Delete one MonthlyReportTrailEntry
   * const MonthlyReportTrailEntry = await prisma.monthlyReportTrailEntry.delete({
   *   where: {
   *     // ... filter to delete one MonthlyReportTrailEntry
   *   }
   * })
   * 
   */
  delete<T extends MonthlyReportTrailEntryDeleteArgs>(args: Prisma.SelectSubset<T, MonthlyReportTrailEntryDeleteArgs<ExtArgs>>): Prisma.Prisma__MonthlyReportTrailEntryClient<runtime.Types.Result.GetResult<Prisma.$MonthlyReportTrailEntryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MonthlyReportTrailEntry.
   * @param {MonthlyReportTrailEntryUpdateArgs} args - Arguments to update one MonthlyReportTrailEntry.
   * @example
   * // Update one MonthlyReportTrailEntry
   * const monthlyReportTrailEntry = await prisma.monthlyReportTrailEntry.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MonthlyReportTrailEntryUpdateArgs>(args: Prisma.SelectSubset<T, MonthlyReportTrailEntryUpdateArgs<ExtArgs>>): Prisma.Prisma__MonthlyReportTrailEntryClient<runtime.Types.Result.GetResult<Prisma.$MonthlyReportTrailEntryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MonthlyReportTrailEntries.
   * @param {MonthlyReportTrailEntryDeleteManyArgs} args - Arguments to filter MonthlyReportTrailEntries to delete.
   * @example
   * // Delete a few MonthlyReportTrailEntries
   * const { count } = await prisma.monthlyReportTrailEntry.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MonthlyReportTrailEntryDeleteManyArgs>(args?: Prisma.SelectSubset<T, MonthlyReportTrailEntryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MonthlyReportTrailEntries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MonthlyReportTrailEntryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MonthlyReportTrailEntries
   * const monthlyReportTrailEntry = await prisma.monthlyReportTrailEntry.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MonthlyReportTrailEntryUpdateManyArgs>(args: Prisma.SelectSubset<T, MonthlyReportTrailEntryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MonthlyReportTrailEntries and returns the data updated in the database.
   * @param {MonthlyReportTrailEntryUpdateManyAndReturnArgs} args - Arguments to update many MonthlyReportTrailEntries.
   * @example
   * // Update many MonthlyReportTrailEntries
   * const monthlyReportTrailEntry = await prisma.monthlyReportTrailEntry.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MonthlyReportTrailEntries and only return the `monthly_report_trail_entry_id`
   * const monthlyReportTrailEntryWithMonthly_report_trail_entry_idOnly = await prisma.monthlyReportTrailEntry.updateManyAndReturn({
   *   select: { monthly_report_trail_entry_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MonthlyReportTrailEntryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MonthlyReportTrailEntryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MonthlyReportTrailEntryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MonthlyReportTrailEntry.
   * @param {MonthlyReportTrailEntryUpsertArgs} args - Arguments to update or create a MonthlyReportTrailEntry.
   * @example
   * // Update or create a MonthlyReportTrailEntry
   * const monthlyReportTrailEntry = await prisma.monthlyReportTrailEntry.upsert({
   *   create: {
   *     // ... data to create a MonthlyReportTrailEntry
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MonthlyReportTrailEntry we want to update
   *   }
   * })
   */
  upsert<T extends MonthlyReportTrailEntryUpsertArgs>(args: Prisma.SelectSubset<T, MonthlyReportTrailEntryUpsertArgs<ExtArgs>>): Prisma.Prisma__MonthlyReportTrailEntryClient<runtime.Types.Result.GetResult<Prisma.$MonthlyReportTrailEntryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MonthlyReportTrailEntries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MonthlyReportTrailEntryCountArgs} args - Arguments to filter MonthlyReportTrailEntries to count.
   * @example
   * // Count the number of MonthlyReportTrailEntries
   * const count = await prisma.monthlyReportTrailEntry.count({
   *   where: {
   *     // ... the filter for the MonthlyReportTrailEntries we want to count
   *   }
   * })
  **/
  count<T extends MonthlyReportTrailEntryCountArgs>(
    args?: Prisma.Subset<T, MonthlyReportTrailEntryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MonthlyReportTrailEntryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MonthlyReportTrailEntry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MonthlyReportTrailEntryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MonthlyReportTrailEntryAggregateArgs>(args: Prisma.Subset<T, MonthlyReportTrailEntryAggregateArgs>): Prisma.PrismaPromise<GetMonthlyReportTrailEntryAggregateType<T>>

  /**
   * Group by MonthlyReportTrailEntry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MonthlyReportTrailEntryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MonthlyReportTrailEntryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MonthlyReportTrailEntryGroupByArgs['orderBy'] }
      : { orderBy?: MonthlyReportTrailEntryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MonthlyReportTrailEntryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMonthlyReportTrailEntryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MonthlyReportTrailEntry model
 */
readonly fields: MonthlyReportTrailEntryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MonthlyReportTrailEntry.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MonthlyReportTrailEntryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  report<T extends Prisma.MonthlyReportDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MonthlyReportDefaultArgs<ExtArgs>>): Prisma.Prisma__MonthlyReportClient<runtime.Types.Result.GetResult<Prisma.$MonthlyReportPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MonthlyReportTrailEntry model
 */
export interface MonthlyReportTrailEntryFieldRefs {
  readonly monthly_report_trail_entry_id: Prisma.FieldRef<"MonthlyReportTrailEntry", 'String'>
  readonly monthly_report_id: Prisma.FieldRef<"MonthlyReportTrailEntry", 'String'>
  readonly action: Prisma.FieldRef<"MonthlyReportTrailEntry", 'MonthlyReportTrailAction'>
  readonly actor_name: Prisma.FieldRef<"MonthlyReportTrailEntry", 'String'>
  readonly note: Prisma.FieldRef<"MonthlyReportTrailEntry", 'String'>
  readonly createdAt: Prisma.FieldRef<"MonthlyReportTrailEntry", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MonthlyReportTrailEntry findUnique
 */
export type MonthlyReportTrailEntryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyReportTrailEntry
   */
  select?: Prisma.MonthlyReportTrailEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyReportTrailEntry
   */
  omit?: Prisma.MonthlyReportTrailEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyReportTrailEntryInclude<ExtArgs> | null
  /**
   * Filter, which MonthlyReportTrailEntry to fetch.
   */
  where: Prisma.MonthlyReportTrailEntryWhereUniqueInput
}

/**
 * MonthlyReportTrailEntry findUniqueOrThrow
 */
export type MonthlyReportTrailEntryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyReportTrailEntry
   */
  select?: Prisma.MonthlyReportTrailEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyReportTrailEntry
   */
  omit?: Prisma.MonthlyReportTrailEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyReportTrailEntryInclude<ExtArgs> | null
  /**
   * Filter, which MonthlyReportTrailEntry to fetch.
   */
  where: Prisma.MonthlyReportTrailEntryWhereUniqueInput
}

/**
 * MonthlyReportTrailEntry findFirst
 */
export type MonthlyReportTrailEntryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyReportTrailEntry
   */
  select?: Prisma.MonthlyReportTrailEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyReportTrailEntry
   */
  omit?: Prisma.MonthlyReportTrailEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyReportTrailEntryInclude<ExtArgs> | null
  /**
   * Filter, which MonthlyReportTrailEntry to fetch.
   */
  where?: Prisma.MonthlyReportTrailEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MonthlyReportTrailEntries to fetch.
   */
  orderBy?: Prisma.MonthlyReportTrailEntryOrderByWithRelationInput | Prisma.MonthlyReportTrailEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MonthlyReportTrailEntries.
   */
  cursor?: Prisma.MonthlyReportTrailEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MonthlyReportTrailEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MonthlyReportTrailEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MonthlyReportTrailEntries.
   */
  distinct?: Prisma.MonthlyReportTrailEntryScalarFieldEnum | Prisma.MonthlyReportTrailEntryScalarFieldEnum[]
}

/**
 * MonthlyReportTrailEntry findFirstOrThrow
 */
export type MonthlyReportTrailEntryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyReportTrailEntry
   */
  select?: Prisma.MonthlyReportTrailEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyReportTrailEntry
   */
  omit?: Prisma.MonthlyReportTrailEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyReportTrailEntryInclude<ExtArgs> | null
  /**
   * Filter, which MonthlyReportTrailEntry to fetch.
   */
  where?: Prisma.MonthlyReportTrailEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MonthlyReportTrailEntries to fetch.
   */
  orderBy?: Prisma.MonthlyReportTrailEntryOrderByWithRelationInput | Prisma.MonthlyReportTrailEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MonthlyReportTrailEntries.
   */
  cursor?: Prisma.MonthlyReportTrailEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MonthlyReportTrailEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MonthlyReportTrailEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MonthlyReportTrailEntries.
   */
  distinct?: Prisma.MonthlyReportTrailEntryScalarFieldEnum | Prisma.MonthlyReportTrailEntryScalarFieldEnum[]
}

/**
 * MonthlyReportTrailEntry findMany
 */
export type MonthlyReportTrailEntryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyReportTrailEntry
   */
  select?: Prisma.MonthlyReportTrailEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyReportTrailEntry
   */
  omit?: Prisma.MonthlyReportTrailEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyReportTrailEntryInclude<ExtArgs> | null
  /**
   * Filter, which MonthlyReportTrailEntries to fetch.
   */
  where?: Prisma.MonthlyReportTrailEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MonthlyReportTrailEntries to fetch.
   */
  orderBy?: Prisma.MonthlyReportTrailEntryOrderByWithRelationInput | Prisma.MonthlyReportTrailEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MonthlyReportTrailEntries.
   */
  cursor?: Prisma.MonthlyReportTrailEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MonthlyReportTrailEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MonthlyReportTrailEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MonthlyReportTrailEntries.
   */
  distinct?: Prisma.MonthlyReportTrailEntryScalarFieldEnum | Prisma.MonthlyReportTrailEntryScalarFieldEnum[]
}

/**
 * MonthlyReportTrailEntry create
 */
export type MonthlyReportTrailEntryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyReportTrailEntry
   */
  select?: Prisma.MonthlyReportTrailEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyReportTrailEntry
   */
  omit?: Prisma.MonthlyReportTrailEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyReportTrailEntryInclude<ExtArgs> | null
  /**
   * The data needed to create a MonthlyReportTrailEntry.
   */
  data: Prisma.XOR<Prisma.MonthlyReportTrailEntryCreateInput, Prisma.MonthlyReportTrailEntryUncheckedCreateInput>
}

/**
 * MonthlyReportTrailEntry createMany
 */
export type MonthlyReportTrailEntryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MonthlyReportTrailEntries.
   */
  data: Prisma.MonthlyReportTrailEntryCreateManyInput | Prisma.MonthlyReportTrailEntryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MonthlyReportTrailEntry createManyAndReturn
 */
export type MonthlyReportTrailEntryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyReportTrailEntry
   */
  select?: Prisma.MonthlyReportTrailEntrySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyReportTrailEntry
   */
  omit?: Prisma.MonthlyReportTrailEntryOmit<ExtArgs> | null
  /**
   * The data used to create many MonthlyReportTrailEntries.
   */
  data: Prisma.MonthlyReportTrailEntryCreateManyInput | Prisma.MonthlyReportTrailEntryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyReportTrailEntryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MonthlyReportTrailEntry update
 */
export type MonthlyReportTrailEntryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyReportTrailEntry
   */
  select?: Prisma.MonthlyReportTrailEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyReportTrailEntry
   */
  omit?: Prisma.MonthlyReportTrailEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyReportTrailEntryInclude<ExtArgs> | null
  /**
   * The data needed to update a MonthlyReportTrailEntry.
   */
  data: Prisma.XOR<Prisma.MonthlyReportTrailEntryUpdateInput, Prisma.MonthlyReportTrailEntryUncheckedUpdateInput>
  /**
   * Choose, which MonthlyReportTrailEntry to update.
   */
  where: Prisma.MonthlyReportTrailEntryWhereUniqueInput
}

/**
 * MonthlyReportTrailEntry updateMany
 */
export type MonthlyReportTrailEntryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MonthlyReportTrailEntries.
   */
  data: Prisma.XOR<Prisma.MonthlyReportTrailEntryUpdateManyMutationInput, Prisma.MonthlyReportTrailEntryUncheckedUpdateManyInput>
  /**
   * Filter which MonthlyReportTrailEntries to update
   */
  where?: Prisma.MonthlyReportTrailEntryWhereInput
  /**
   * Limit how many MonthlyReportTrailEntries to update.
   */
  limit?: number
}

/**
 * MonthlyReportTrailEntry updateManyAndReturn
 */
export type MonthlyReportTrailEntryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyReportTrailEntry
   */
  select?: Prisma.MonthlyReportTrailEntrySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyReportTrailEntry
   */
  omit?: Prisma.MonthlyReportTrailEntryOmit<ExtArgs> | null
  /**
   * The data used to update MonthlyReportTrailEntries.
   */
  data: Prisma.XOR<Prisma.MonthlyReportTrailEntryUpdateManyMutationInput, Prisma.MonthlyReportTrailEntryUncheckedUpdateManyInput>
  /**
   * Filter which MonthlyReportTrailEntries to update
   */
  where?: Prisma.MonthlyReportTrailEntryWhereInput
  /**
   * Limit how many MonthlyReportTrailEntries to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyReportTrailEntryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MonthlyReportTrailEntry upsert
 */
export type MonthlyReportTrailEntryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyReportTrailEntry
   */
  select?: Prisma.MonthlyReportTrailEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyReportTrailEntry
   */
  omit?: Prisma.MonthlyReportTrailEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyReportTrailEntryInclude<ExtArgs> | null
  /**
   * The filter to search for the MonthlyReportTrailEntry to update in case it exists.
   */
  where: Prisma.MonthlyReportTrailEntryWhereUniqueInput
  /**
   * In case the MonthlyReportTrailEntry found by the `where` argument doesn't exist, create a new MonthlyReportTrailEntry with this data.
   */
  create: Prisma.XOR<Prisma.MonthlyReportTrailEntryCreateInput, Prisma.MonthlyReportTrailEntryUncheckedCreateInput>
  /**
   * In case the MonthlyReportTrailEntry was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MonthlyReportTrailEntryUpdateInput, Prisma.MonthlyReportTrailEntryUncheckedUpdateInput>
}

/**
 * MonthlyReportTrailEntry delete
 */
export type MonthlyReportTrailEntryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyReportTrailEntry
   */
  select?: Prisma.MonthlyReportTrailEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyReportTrailEntry
   */
  omit?: Prisma.MonthlyReportTrailEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyReportTrailEntryInclude<ExtArgs> | null
  /**
   * Filter which MonthlyReportTrailEntry to delete.
   */
  where: Prisma.MonthlyReportTrailEntryWhereUniqueInput
}

/**
 * MonthlyReportTrailEntry deleteMany
 */
export type MonthlyReportTrailEntryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MonthlyReportTrailEntries to delete
   */
  where?: Prisma.MonthlyReportTrailEntryWhereInput
  /**
   * Limit how many MonthlyReportTrailEntries to delete.
   */
  limit?: number
}

/**
 * MonthlyReportTrailEntry without action
 */
export type MonthlyReportTrailEntryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyReportTrailEntry
   */
  select?: Prisma.MonthlyReportTrailEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyReportTrailEntry
   */
  omit?: Prisma.MonthlyReportTrailEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyReportTrailEntryInclude<ExtArgs> | null
}
