
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserActionSuspension` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model UserActionSuspension
 * A violation-driven suspension of one action. Layers *over* the granted rights: the
 * grant is preserved so lifting the suspension restores the original scope.
 */
export type UserActionSuspensionModel = runtime.Types.Result.DefaultSelection<Prisma.$UserActionSuspensionPayload>

export type AggregateUserActionSuspension = {
  _count: UserActionSuspensionCountAggregateOutputType | null
  _min: UserActionSuspensionMinAggregateOutputType | null
  _max: UserActionSuspensionMaxAggregateOutputType | null
}

export type UserActionSuspensionMinAggregateOutputType = {
  user_action_suspension_id: string | null
  user_id: string | null
  permission: $Enums.PermissionKey | null
  reason: string | null
  issued_by_user_id: string | null
  expires_at: Date | null
  lifted_at: Date | null
  lifted_by_user_id: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserActionSuspensionMaxAggregateOutputType = {
  user_action_suspension_id: string | null
  user_id: string | null
  permission: $Enums.PermissionKey | null
  reason: string | null
  issued_by_user_id: string | null
  expires_at: Date | null
  lifted_at: Date | null
  lifted_by_user_id: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserActionSuspensionCountAggregateOutputType = {
  user_action_suspension_id: number
  user_id: number
  permission: number
  reason: number
  issued_by_user_id: number
  expires_at: number
  lifted_at: number
  lifted_by_user_id: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type UserActionSuspensionMinAggregateInputType = {
  user_action_suspension_id?: true
  user_id?: true
  permission?: true
  reason?: true
  issued_by_user_id?: true
  expires_at?: true
  lifted_at?: true
  lifted_by_user_id?: true
  createdAt?: true
  updatedAt?: true
}

export type UserActionSuspensionMaxAggregateInputType = {
  user_action_suspension_id?: true
  user_id?: true
  permission?: true
  reason?: true
  issued_by_user_id?: true
  expires_at?: true
  lifted_at?: true
  lifted_by_user_id?: true
  createdAt?: true
  updatedAt?: true
}

export type UserActionSuspensionCountAggregateInputType = {
  user_action_suspension_id?: true
  user_id?: true
  permission?: true
  reason?: true
  issued_by_user_id?: true
  expires_at?: true
  lifted_at?: true
  lifted_by_user_id?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type UserActionSuspensionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserActionSuspension to aggregate.
   */
  where?: Prisma.UserActionSuspensionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserActionSuspensions to fetch.
   */
  orderBy?: Prisma.UserActionSuspensionOrderByWithRelationInput | Prisma.UserActionSuspensionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserActionSuspensionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserActionSuspensions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserActionSuspensions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserActionSuspensions
  **/
  _count?: true | UserActionSuspensionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserActionSuspensionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserActionSuspensionMaxAggregateInputType
}

export type GetUserActionSuspensionAggregateType<T extends UserActionSuspensionAggregateArgs> = {
      [P in keyof T & keyof AggregateUserActionSuspension]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserActionSuspension[P]>
    : Prisma.GetScalarType<T[P], AggregateUserActionSuspension[P]>
}




export type UserActionSuspensionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserActionSuspensionWhereInput
  orderBy?: Prisma.UserActionSuspensionOrderByWithAggregationInput | Prisma.UserActionSuspensionOrderByWithAggregationInput[]
  by: Prisma.UserActionSuspensionScalarFieldEnum[] | Prisma.UserActionSuspensionScalarFieldEnum
  having?: Prisma.UserActionSuspensionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserActionSuspensionCountAggregateInputType | true
  _min?: UserActionSuspensionMinAggregateInputType
  _max?: UserActionSuspensionMaxAggregateInputType
}

export type UserActionSuspensionGroupByOutputType = {
  user_action_suspension_id: string
  user_id: string
  permission: $Enums.PermissionKey
  reason: string
  issued_by_user_id: string
  expires_at: Date | null
  lifted_at: Date | null
  lifted_by_user_id: string | null
  createdAt: Date
  updatedAt: Date
  _count: UserActionSuspensionCountAggregateOutputType | null
  _min: UserActionSuspensionMinAggregateOutputType | null
  _max: UserActionSuspensionMaxAggregateOutputType | null
}

export type GetUserActionSuspensionGroupByPayload<T extends UserActionSuspensionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserActionSuspensionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserActionSuspensionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserActionSuspensionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserActionSuspensionGroupByOutputType[P]>
      }
    >
  >



export type UserActionSuspensionWhereInput = {
  AND?: Prisma.UserActionSuspensionWhereInput | Prisma.UserActionSuspensionWhereInput[]
  OR?: Prisma.UserActionSuspensionWhereInput[]
  NOT?: Prisma.UserActionSuspensionWhereInput | Prisma.UserActionSuspensionWhereInput[]
  user_action_suspension_id?: Prisma.StringFilter<"UserActionSuspension"> | string
  user_id?: Prisma.StringFilter<"UserActionSuspension"> | string
  permission?: Prisma.EnumPermissionKeyFilter<"UserActionSuspension"> | $Enums.PermissionKey
  reason?: Prisma.StringFilter<"UserActionSuspension"> | string
  issued_by_user_id?: Prisma.StringFilter<"UserActionSuspension"> | string
  expires_at?: Prisma.DateTimeNullableFilter<"UserActionSuspension"> | Date | string | null
  lifted_at?: Prisma.DateTimeNullableFilter<"UserActionSuspension"> | Date | string | null
  lifted_by_user_id?: Prisma.StringNullableFilter<"UserActionSuspension"> | string | null
  createdAt?: Prisma.DateTimeFilter<"UserActionSuspension"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UserActionSuspension"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type UserActionSuspensionOrderByWithRelationInput = {
  user_action_suspension_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  permission?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  issued_by_user_id?: Prisma.SortOrder
  expires_at?: Prisma.SortOrderInput | Prisma.SortOrder
  lifted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  lifted_by_user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type UserActionSuspensionWhereUniqueInput = Prisma.AtLeast<{
  user_action_suspension_id?: string
  AND?: Prisma.UserActionSuspensionWhereInput | Prisma.UserActionSuspensionWhereInput[]
  OR?: Prisma.UserActionSuspensionWhereInput[]
  NOT?: Prisma.UserActionSuspensionWhereInput | Prisma.UserActionSuspensionWhereInput[]
  user_id?: Prisma.StringFilter<"UserActionSuspension"> | string
  permission?: Prisma.EnumPermissionKeyFilter<"UserActionSuspension"> | $Enums.PermissionKey
  reason?: Prisma.StringFilter<"UserActionSuspension"> | string
  issued_by_user_id?: Prisma.StringFilter<"UserActionSuspension"> | string
  expires_at?: Prisma.DateTimeNullableFilter<"UserActionSuspension"> | Date | string | null
  lifted_at?: Prisma.DateTimeNullableFilter<"UserActionSuspension"> | Date | string | null
  lifted_by_user_id?: Prisma.StringNullableFilter<"UserActionSuspension"> | string | null
  createdAt?: Prisma.DateTimeFilter<"UserActionSuspension"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UserActionSuspension"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "user_action_suspension_id">

export type UserActionSuspensionOrderByWithAggregationInput = {
  user_action_suspension_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  permission?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  issued_by_user_id?: Prisma.SortOrder
  expires_at?: Prisma.SortOrderInput | Prisma.SortOrder
  lifted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  lifted_by_user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.UserActionSuspensionCountOrderByAggregateInput
  _max?: Prisma.UserActionSuspensionMaxOrderByAggregateInput
  _min?: Prisma.UserActionSuspensionMinOrderByAggregateInput
}

export type UserActionSuspensionScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserActionSuspensionScalarWhereWithAggregatesInput | Prisma.UserActionSuspensionScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserActionSuspensionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserActionSuspensionScalarWhereWithAggregatesInput | Prisma.UserActionSuspensionScalarWhereWithAggregatesInput[]
  user_action_suspension_id?: Prisma.StringWithAggregatesFilter<"UserActionSuspension"> | string
  user_id?: Prisma.StringWithAggregatesFilter<"UserActionSuspension"> | string
  permission?: Prisma.EnumPermissionKeyWithAggregatesFilter<"UserActionSuspension"> | $Enums.PermissionKey
  reason?: Prisma.StringWithAggregatesFilter<"UserActionSuspension"> | string
  issued_by_user_id?: Prisma.StringWithAggregatesFilter<"UserActionSuspension"> | string
  expires_at?: Prisma.DateTimeNullableWithAggregatesFilter<"UserActionSuspension"> | Date | string | null
  lifted_at?: Prisma.DateTimeNullableWithAggregatesFilter<"UserActionSuspension"> | Date | string | null
  lifted_by_user_id?: Prisma.StringNullableWithAggregatesFilter<"UserActionSuspension"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UserActionSuspension"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"UserActionSuspension"> | Date | string
}

export type UserActionSuspensionCreateInput = {
  user_action_suspension_id?: string
  permission: $Enums.PermissionKey
  reason: string
  issued_by_user_id: string
  expires_at?: Date | string | null
  lifted_at?: Date | string | null
  lifted_by_user_id?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutAction_suspensionsInput
}

export type UserActionSuspensionUncheckedCreateInput = {
  user_action_suspension_id?: string
  user_id: string
  permission: $Enums.PermissionKey
  reason: string
  issued_by_user_id: string
  expires_at?: Date | string | null
  lifted_at?: Date | string | null
  lifted_by_user_id?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserActionSuspensionUpdateInput = {
  user_action_suspension_id?: Prisma.StringFieldUpdateOperationsInput | string
  permission?: Prisma.EnumPermissionKeyFieldUpdateOperationsInput | $Enums.PermissionKey
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  issued_by_user_id?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lifted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lifted_by_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutAction_suspensionsNestedInput
}

export type UserActionSuspensionUncheckedUpdateInput = {
  user_action_suspension_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  permission?: Prisma.EnumPermissionKeyFieldUpdateOperationsInput | $Enums.PermissionKey
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  issued_by_user_id?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lifted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lifted_by_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserActionSuspensionCreateManyInput = {
  user_action_suspension_id?: string
  user_id: string
  permission: $Enums.PermissionKey
  reason: string
  issued_by_user_id: string
  expires_at?: Date | string | null
  lifted_at?: Date | string | null
  lifted_by_user_id?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserActionSuspensionUpdateManyMutationInput = {
  user_action_suspension_id?: Prisma.StringFieldUpdateOperationsInput | string
  permission?: Prisma.EnumPermissionKeyFieldUpdateOperationsInput | $Enums.PermissionKey
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  issued_by_user_id?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lifted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lifted_by_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserActionSuspensionUncheckedUpdateManyInput = {
  user_action_suspension_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  permission?: Prisma.EnumPermissionKeyFieldUpdateOperationsInput | $Enums.PermissionKey
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  issued_by_user_id?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lifted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lifted_by_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserActionSuspensionListRelationFilter = {
  every?: Prisma.UserActionSuspensionWhereInput
  some?: Prisma.UserActionSuspensionWhereInput
  none?: Prisma.UserActionSuspensionWhereInput
}

export type UserActionSuspensionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserActionSuspensionCountOrderByAggregateInput = {
  user_action_suspension_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  permission?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  issued_by_user_id?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  lifted_at?: Prisma.SortOrder
  lifted_by_user_id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserActionSuspensionMaxOrderByAggregateInput = {
  user_action_suspension_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  permission?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  issued_by_user_id?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  lifted_at?: Prisma.SortOrder
  lifted_by_user_id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserActionSuspensionMinOrderByAggregateInput = {
  user_action_suspension_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  permission?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  issued_by_user_id?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  lifted_at?: Prisma.SortOrder
  lifted_by_user_id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserActionSuspensionCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserActionSuspensionCreateWithoutUserInput, Prisma.UserActionSuspensionUncheckedCreateWithoutUserInput> | Prisma.UserActionSuspensionCreateWithoutUserInput[] | Prisma.UserActionSuspensionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserActionSuspensionCreateOrConnectWithoutUserInput | Prisma.UserActionSuspensionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserActionSuspensionCreateManyUserInputEnvelope
  connect?: Prisma.UserActionSuspensionWhereUniqueInput | Prisma.UserActionSuspensionWhereUniqueInput[]
}

export type UserActionSuspensionUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserActionSuspensionCreateWithoutUserInput, Prisma.UserActionSuspensionUncheckedCreateWithoutUserInput> | Prisma.UserActionSuspensionCreateWithoutUserInput[] | Prisma.UserActionSuspensionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserActionSuspensionCreateOrConnectWithoutUserInput | Prisma.UserActionSuspensionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserActionSuspensionCreateManyUserInputEnvelope
  connect?: Prisma.UserActionSuspensionWhereUniqueInput | Prisma.UserActionSuspensionWhereUniqueInput[]
}

export type UserActionSuspensionUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserActionSuspensionCreateWithoutUserInput, Prisma.UserActionSuspensionUncheckedCreateWithoutUserInput> | Prisma.UserActionSuspensionCreateWithoutUserInput[] | Prisma.UserActionSuspensionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserActionSuspensionCreateOrConnectWithoutUserInput | Prisma.UserActionSuspensionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserActionSuspensionUpsertWithWhereUniqueWithoutUserInput | Prisma.UserActionSuspensionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserActionSuspensionCreateManyUserInputEnvelope
  set?: Prisma.UserActionSuspensionWhereUniqueInput | Prisma.UserActionSuspensionWhereUniqueInput[]
  disconnect?: Prisma.UserActionSuspensionWhereUniqueInput | Prisma.UserActionSuspensionWhereUniqueInput[]
  delete?: Prisma.UserActionSuspensionWhereUniqueInput | Prisma.UserActionSuspensionWhereUniqueInput[]
  connect?: Prisma.UserActionSuspensionWhereUniqueInput | Prisma.UserActionSuspensionWhereUniqueInput[]
  update?: Prisma.UserActionSuspensionUpdateWithWhereUniqueWithoutUserInput | Prisma.UserActionSuspensionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserActionSuspensionUpdateManyWithWhereWithoutUserInput | Prisma.UserActionSuspensionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserActionSuspensionScalarWhereInput | Prisma.UserActionSuspensionScalarWhereInput[]
}

export type UserActionSuspensionUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserActionSuspensionCreateWithoutUserInput, Prisma.UserActionSuspensionUncheckedCreateWithoutUserInput> | Prisma.UserActionSuspensionCreateWithoutUserInput[] | Prisma.UserActionSuspensionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserActionSuspensionCreateOrConnectWithoutUserInput | Prisma.UserActionSuspensionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserActionSuspensionUpsertWithWhereUniqueWithoutUserInput | Prisma.UserActionSuspensionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserActionSuspensionCreateManyUserInputEnvelope
  set?: Prisma.UserActionSuspensionWhereUniqueInput | Prisma.UserActionSuspensionWhereUniqueInput[]
  disconnect?: Prisma.UserActionSuspensionWhereUniqueInput | Prisma.UserActionSuspensionWhereUniqueInput[]
  delete?: Prisma.UserActionSuspensionWhereUniqueInput | Prisma.UserActionSuspensionWhereUniqueInput[]
  connect?: Prisma.UserActionSuspensionWhereUniqueInput | Prisma.UserActionSuspensionWhereUniqueInput[]
  update?: Prisma.UserActionSuspensionUpdateWithWhereUniqueWithoutUserInput | Prisma.UserActionSuspensionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserActionSuspensionUpdateManyWithWhereWithoutUserInput | Prisma.UserActionSuspensionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserActionSuspensionScalarWhereInput | Prisma.UserActionSuspensionScalarWhereInput[]
}

export type UserActionSuspensionCreateWithoutUserInput = {
  user_action_suspension_id?: string
  permission: $Enums.PermissionKey
  reason: string
  issued_by_user_id: string
  expires_at?: Date | string | null
  lifted_at?: Date | string | null
  lifted_by_user_id?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserActionSuspensionUncheckedCreateWithoutUserInput = {
  user_action_suspension_id?: string
  permission: $Enums.PermissionKey
  reason: string
  issued_by_user_id: string
  expires_at?: Date | string | null
  lifted_at?: Date | string | null
  lifted_by_user_id?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserActionSuspensionCreateOrConnectWithoutUserInput = {
  where: Prisma.UserActionSuspensionWhereUniqueInput
  create: Prisma.XOR<Prisma.UserActionSuspensionCreateWithoutUserInput, Prisma.UserActionSuspensionUncheckedCreateWithoutUserInput>
}

export type UserActionSuspensionCreateManyUserInputEnvelope = {
  data: Prisma.UserActionSuspensionCreateManyUserInput | Prisma.UserActionSuspensionCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserActionSuspensionUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserActionSuspensionWhereUniqueInput
  update: Prisma.XOR<Prisma.UserActionSuspensionUpdateWithoutUserInput, Prisma.UserActionSuspensionUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserActionSuspensionCreateWithoutUserInput, Prisma.UserActionSuspensionUncheckedCreateWithoutUserInput>
}

export type UserActionSuspensionUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserActionSuspensionWhereUniqueInput
  data: Prisma.XOR<Prisma.UserActionSuspensionUpdateWithoutUserInput, Prisma.UserActionSuspensionUncheckedUpdateWithoutUserInput>
}

export type UserActionSuspensionUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserActionSuspensionScalarWhereInput
  data: Prisma.XOR<Prisma.UserActionSuspensionUpdateManyMutationInput, Prisma.UserActionSuspensionUncheckedUpdateManyWithoutUserInput>
}

export type UserActionSuspensionScalarWhereInput = {
  AND?: Prisma.UserActionSuspensionScalarWhereInput | Prisma.UserActionSuspensionScalarWhereInput[]
  OR?: Prisma.UserActionSuspensionScalarWhereInput[]
  NOT?: Prisma.UserActionSuspensionScalarWhereInput | Prisma.UserActionSuspensionScalarWhereInput[]
  user_action_suspension_id?: Prisma.StringFilter<"UserActionSuspension"> | string
  user_id?: Prisma.StringFilter<"UserActionSuspension"> | string
  permission?: Prisma.EnumPermissionKeyFilter<"UserActionSuspension"> | $Enums.PermissionKey
  reason?: Prisma.StringFilter<"UserActionSuspension"> | string
  issued_by_user_id?: Prisma.StringFilter<"UserActionSuspension"> | string
  expires_at?: Prisma.DateTimeNullableFilter<"UserActionSuspension"> | Date | string | null
  lifted_at?: Prisma.DateTimeNullableFilter<"UserActionSuspension"> | Date | string | null
  lifted_by_user_id?: Prisma.StringNullableFilter<"UserActionSuspension"> | string | null
  createdAt?: Prisma.DateTimeFilter<"UserActionSuspension"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UserActionSuspension"> | Date | string
}

export type UserActionSuspensionCreateManyUserInput = {
  user_action_suspension_id?: string
  permission: $Enums.PermissionKey
  reason: string
  issued_by_user_id: string
  expires_at?: Date | string | null
  lifted_at?: Date | string | null
  lifted_by_user_id?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserActionSuspensionUpdateWithoutUserInput = {
  user_action_suspension_id?: Prisma.StringFieldUpdateOperationsInput | string
  permission?: Prisma.EnumPermissionKeyFieldUpdateOperationsInput | $Enums.PermissionKey
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  issued_by_user_id?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lifted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lifted_by_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserActionSuspensionUncheckedUpdateWithoutUserInput = {
  user_action_suspension_id?: Prisma.StringFieldUpdateOperationsInput | string
  permission?: Prisma.EnumPermissionKeyFieldUpdateOperationsInput | $Enums.PermissionKey
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  issued_by_user_id?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lifted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lifted_by_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserActionSuspensionUncheckedUpdateManyWithoutUserInput = {
  user_action_suspension_id?: Prisma.StringFieldUpdateOperationsInput | string
  permission?: Prisma.EnumPermissionKeyFieldUpdateOperationsInput | $Enums.PermissionKey
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  issued_by_user_id?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lifted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lifted_by_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type UserActionSuspensionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_action_suspension_id?: boolean
  user_id?: boolean
  permission?: boolean
  reason?: boolean
  issued_by_user_id?: boolean
  expires_at?: boolean
  lifted_at?: boolean
  lifted_by_user_id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userActionSuspension"]>

export type UserActionSuspensionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_action_suspension_id?: boolean
  user_id?: boolean
  permission?: boolean
  reason?: boolean
  issued_by_user_id?: boolean
  expires_at?: boolean
  lifted_at?: boolean
  lifted_by_user_id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userActionSuspension"]>

export type UserActionSuspensionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_action_suspension_id?: boolean
  user_id?: boolean
  permission?: boolean
  reason?: boolean
  issued_by_user_id?: boolean
  expires_at?: boolean
  lifted_at?: boolean
  lifted_by_user_id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userActionSuspension"]>

export type UserActionSuspensionSelectScalar = {
  user_action_suspension_id?: boolean
  user_id?: boolean
  permission?: boolean
  reason?: boolean
  issued_by_user_id?: boolean
  expires_at?: boolean
  lifted_at?: boolean
  lifted_by_user_id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type UserActionSuspensionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"user_action_suspension_id" | "user_id" | "permission" | "reason" | "issued_by_user_id" | "expires_at" | "lifted_at" | "lifted_by_user_id" | "createdAt" | "updatedAt", ExtArgs["result"]["userActionSuspension"]>
export type UserActionSuspensionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserActionSuspensionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserActionSuspensionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $UserActionSuspensionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserActionSuspension"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    user_action_suspension_id: string
    user_id: string
    permission: $Enums.PermissionKey
    reason: string
    issued_by_user_id: string
    /**
     * Null means indefinite — it stays in force until an admin lifts it.
     */
    expires_at: Date | null
    lifted_at: Date | null
    lifted_by_user_id: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["userActionSuspension"]>
  composites: {}
}

export type UserActionSuspensionGetPayload<S extends boolean | null | undefined | UserActionSuspensionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserActionSuspensionPayload, S>

export type UserActionSuspensionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserActionSuspensionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserActionSuspensionCountAggregateInputType | true
  }

export interface UserActionSuspensionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserActionSuspension'], meta: { name: 'UserActionSuspension' } }
  /**
   * Find zero or one UserActionSuspension that matches the filter.
   * @param {UserActionSuspensionFindUniqueArgs} args - Arguments to find a UserActionSuspension
   * @example
   * // Get one UserActionSuspension
   * const userActionSuspension = await prisma.userActionSuspension.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserActionSuspensionFindUniqueArgs>(args: Prisma.SelectSubset<T, UserActionSuspensionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserActionSuspensionClient<runtime.Types.Result.GetResult<Prisma.$UserActionSuspensionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserActionSuspension that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserActionSuspensionFindUniqueOrThrowArgs} args - Arguments to find a UserActionSuspension
   * @example
   * // Get one UserActionSuspension
   * const userActionSuspension = await prisma.userActionSuspension.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserActionSuspensionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserActionSuspensionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserActionSuspensionClient<runtime.Types.Result.GetResult<Prisma.$UserActionSuspensionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserActionSuspension that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserActionSuspensionFindFirstArgs} args - Arguments to find a UserActionSuspension
   * @example
   * // Get one UserActionSuspension
   * const userActionSuspension = await prisma.userActionSuspension.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserActionSuspensionFindFirstArgs>(args?: Prisma.SelectSubset<T, UserActionSuspensionFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserActionSuspensionClient<runtime.Types.Result.GetResult<Prisma.$UserActionSuspensionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserActionSuspension that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserActionSuspensionFindFirstOrThrowArgs} args - Arguments to find a UserActionSuspension
   * @example
   * // Get one UserActionSuspension
   * const userActionSuspension = await prisma.userActionSuspension.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserActionSuspensionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserActionSuspensionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserActionSuspensionClient<runtime.Types.Result.GetResult<Prisma.$UserActionSuspensionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserActionSuspensions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserActionSuspensionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserActionSuspensions
   * const userActionSuspensions = await prisma.userActionSuspension.findMany()
   * 
   * // Get first 10 UserActionSuspensions
   * const userActionSuspensions = await prisma.userActionSuspension.findMany({ take: 10 })
   * 
   * // Only select the `user_action_suspension_id`
   * const userActionSuspensionWithUser_action_suspension_idOnly = await prisma.userActionSuspension.findMany({ select: { user_action_suspension_id: true } })
   * 
   */
  findMany<T extends UserActionSuspensionFindManyArgs>(args?: Prisma.SelectSubset<T, UserActionSuspensionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserActionSuspensionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserActionSuspension.
   * @param {UserActionSuspensionCreateArgs} args - Arguments to create a UserActionSuspension.
   * @example
   * // Create one UserActionSuspension
   * const UserActionSuspension = await prisma.userActionSuspension.create({
   *   data: {
   *     // ... data to create a UserActionSuspension
   *   }
   * })
   * 
   */
  create<T extends UserActionSuspensionCreateArgs>(args: Prisma.SelectSubset<T, UserActionSuspensionCreateArgs<ExtArgs>>): Prisma.Prisma__UserActionSuspensionClient<runtime.Types.Result.GetResult<Prisma.$UserActionSuspensionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserActionSuspensions.
   * @param {UserActionSuspensionCreateManyArgs} args - Arguments to create many UserActionSuspensions.
   * @example
   * // Create many UserActionSuspensions
   * const userActionSuspension = await prisma.userActionSuspension.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserActionSuspensionCreateManyArgs>(args?: Prisma.SelectSubset<T, UserActionSuspensionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserActionSuspensions and returns the data saved in the database.
   * @param {UserActionSuspensionCreateManyAndReturnArgs} args - Arguments to create many UserActionSuspensions.
   * @example
   * // Create many UserActionSuspensions
   * const userActionSuspension = await prisma.userActionSuspension.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserActionSuspensions and only return the `user_action_suspension_id`
   * const userActionSuspensionWithUser_action_suspension_idOnly = await prisma.userActionSuspension.createManyAndReturn({
   *   select: { user_action_suspension_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserActionSuspensionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserActionSuspensionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserActionSuspensionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserActionSuspension.
   * @param {UserActionSuspensionDeleteArgs} args - Arguments to delete one UserActionSuspension.
   * @example
   * // Delete one UserActionSuspension
   * const UserActionSuspension = await prisma.userActionSuspension.delete({
   *   where: {
   *     // ... filter to delete one UserActionSuspension
   *   }
   * })
   * 
   */
  delete<T extends UserActionSuspensionDeleteArgs>(args: Prisma.SelectSubset<T, UserActionSuspensionDeleteArgs<ExtArgs>>): Prisma.Prisma__UserActionSuspensionClient<runtime.Types.Result.GetResult<Prisma.$UserActionSuspensionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserActionSuspension.
   * @param {UserActionSuspensionUpdateArgs} args - Arguments to update one UserActionSuspension.
   * @example
   * // Update one UserActionSuspension
   * const userActionSuspension = await prisma.userActionSuspension.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserActionSuspensionUpdateArgs>(args: Prisma.SelectSubset<T, UserActionSuspensionUpdateArgs<ExtArgs>>): Prisma.Prisma__UserActionSuspensionClient<runtime.Types.Result.GetResult<Prisma.$UserActionSuspensionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserActionSuspensions.
   * @param {UserActionSuspensionDeleteManyArgs} args - Arguments to filter UserActionSuspensions to delete.
   * @example
   * // Delete a few UserActionSuspensions
   * const { count } = await prisma.userActionSuspension.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserActionSuspensionDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserActionSuspensionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserActionSuspensions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserActionSuspensionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserActionSuspensions
   * const userActionSuspension = await prisma.userActionSuspension.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserActionSuspensionUpdateManyArgs>(args: Prisma.SelectSubset<T, UserActionSuspensionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserActionSuspensions and returns the data updated in the database.
   * @param {UserActionSuspensionUpdateManyAndReturnArgs} args - Arguments to update many UserActionSuspensions.
   * @example
   * // Update many UserActionSuspensions
   * const userActionSuspension = await prisma.userActionSuspension.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserActionSuspensions and only return the `user_action_suspension_id`
   * const userActionSuspensionWithUser_action_suspension_idOnly = await prisma.userActionSuspension.updateManyAndReturn({
   *   select: { user_action_suspension_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserActionSuspensionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserActionSuspensionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserActionSuspensionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserActionSuspension.
   * @param {UserActionSuspensionUpsertArgs} args - Arguments to update or create a UserActionSuspension.
   * @example
   * // Update or create a UserActionSuspension
   * const userActionSuspension = await prisma.userActionSuspension.upsert({
   *   create: {
   *     // ... data to create a UserActionSuspension
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserActionSuspension we want to update
   *   }
   * })
   */
  upsert<T extends UserActionSuspensionUpsertArgs>(args: Prisma.SelectSubset<T, UserActionSuspensionUpsertArgs<ExtArgs>>): Prisma.Prisma__UserActionSuspensionClient<runtime.Types.Result.GetResult<Prisma.$UserActionSuspensionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserActionSuspensions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserActionSuspensionCountArgs} args - Arguments to filter UserActionSuspensions to count.
   * @example
   * // Count the number of UserActionSuspensions
   * const count = await prisma.userActionSuspension.count({
   *   where: {
   *     // ... the filter for the UserActionSuspensions we want to count
   *   }
   * })
  **/
  count<T extends UserActionSuspensionCountArgs>(
    args?: Prisma.Subset<T, UserActionSuspensionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserActionSuspensionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserActionSuspension.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserActionSuspensionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserActionSuspensionAggregateArgs>(args: Prisma.Subset<T, UserActionSuspensionAggregateArgs>): Prisma.PrismaPromise<GetUserActionSuspensionAggregateType<T>>

  /**
   * Group by UserActionSuspension.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserActionSuspensionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserActionSuspensionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserActionSuspensionGroupByArgs['orderBy'] }
      : { orderBy?: UserActionSuspensionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserActionSuspensionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserActionSuspensionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserActionSuspension model
 */
readonly fields: UserActionSuspensionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserActionSuspension.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserActionSuspensionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserActionSuspension model
 */
export interface UserActionSuspensionFieldRefs {
  readonly user_action_suspension_id: Prisma.FieldRef<"UserActionSuspension", 'String'>
  readonly user_id: Prisma.FieldRef<"UserActionSuspension", 'String'>
  readonly permission: Prisma.FieldRef<"UserActionSuspension", 'PermissionKey'>
  readonly reason: Prisma.FieldRef<"UserActionSuspension", 'String'>
  readonly issued_by_user_id: Prisma.FieldRef<"UserActionSuspension", 'String'>
  readonly expires_at: Prisma.FieldRef<"UserActionSuspension", 'DateTime'>
  readonly lifted_at: Prisma.FieldRef<"UserActionSuspension", 'DateTime'>
  readonly lifted_by_user_id: Prisma.FieldRef<"UserActionSuspension", 'String'>
  readonly createdAt: Prisma.FieldRef<"UserActionSuspension", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"UserActionSuspension", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UserActionSuspension findUnique
 */
export type UserActionSuspensionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActionSuspension
   */
  select?: Prisma.UserActionSuspensionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserActionSuspension
   */
  omit?: Prisma.UserActionSuspensionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserActionSuspensionInclude<ExtArgs> | null
  /**
   * Filter, which UserActionSuspension to fetch.
   */
  where: Prisma.UserActionSuspensionWhereUniqueInput
}

/**
 * UserActionSuspension findUniqueOrThrow
 */
export type UserActionSuspensionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActionSuspension
   */
  select?: Prisma.UserActionSuspensionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserActionSuspension
   */
  omit?: Prisma.UserActionSuspensionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserActionSuspensionInclude<ExtArgs> | null
  /**
   * Filter, which UserActionSuspension to fetch.
   */
  where: Prisma.UserActionSuspensionWhereUniqueInput
}

/**
 * UserActionSuspension findFirst
 */
export type UserActionSuspensionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActionSuspension
   */
  select?: Prisma.UserActionSuspensionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserActionSuspension
   */
  omit?: Prisma.UserActionSuspensionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserActionSuspensionInclude<ExtArgs> | null
  /**
   * Filter, which UserActionSuspension to fetch.
   */
  where?: Prisma.UserActionSuspensionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserActionSuspensions to fetch.
   */
  orderBy?: Prisma.UserActionSuspensionOrderByWithRelationInput | Prisma.UserActionSuspensionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserActionSuspensions.
   */
  cursor?: Prisma.UserActionSuspensionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserActionSuspensions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserActionSuspensions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserActionSuspensions.
   */
  distinct?: Prisma.UserActionSuspensionScalarFieldEnum | Prisma.UserActionSuspensionScalarFieldEnum[]
}

/**
 * UserActionSuspension findFirstOrThrow
 */
export type UserActionSuspensionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActionSuspension
   */
  select?: Prisma.UserActionSuspensionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserActionSuspension
   */
  omit?: Prisma.UserActionSuspensionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserActionSuspensionInclude<ExtArgs> | null
  /**
   * Filter, which UserActionSuspension to fetch.
   */
  where?: Prisma.UserActionSuspensionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserActionSuspensions to fetch.
   */
  orderBy?: Prisma.UserActionSuspensionOrderByWithRelationInput | Prisma.UserActionSuspensionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserActionSuspensions.
   */
  cursor?: Prisma.UserActionSuspensionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserActionSuspensions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserActionSuspensions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserActionSuspensions.
   */
  distinct?: Prisma.UserActionSuspensionScalarFieldEnum | Prisma.UserActionSuspensionScalarFieldEnum[]
}

/**
 * UserActionSuspension findMany
 */
export type UserActionSuspensionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActionSuspension
   */
  select?: Prisma.UserActionSuspensionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserActionSuspension
   */
  omit?: Prisma.UserActionSuspensionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserActionSuspensionInclude<ExtArgs> | null
  /**
   * Filter, which UserActionSuspensions to fetch.
   */
  where?: Prisma.UserActionSuspensionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserActionSuspensions to fetch.
   */
  orderBy?: Prisma.UserActionSuspensionOrderByWithRelationInput | Prisma.UserActionSuspensionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserActionSuspensions.
   */
  cursor?: Prisma.UserActionSuspensionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserActionSuspensions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserActionSuspensions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserActionSuspensions.
   */
  distinct?: Prisma.UserActionSuspensionScalarFieldEnum | Prisma.UserActionSuspensionScalarFieldEnum[]
}

/**
 * UserActionSuspension create
 */
export type UserActionSuspensionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActionSuspension
   */
  select?: Prisma.UserActionSuspensionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserActionSuspension
   */
  omit?: Prisma.UserActionSuspensionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserActionSuspensionInclude<ExtArgs> | null
  /**
   * The data needed to create a UserActionSuspension.
   */
  data: Prisma.XOR<Prisma.UserActionSuspensionCreateInput, Prisma.UserActionSuspensionUncheckedCreateInput>
}

/**
 * UserActionSuspension createMany
 */
export type UserActionSuspensionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserActionSuspensions.
   */
  data: Prisma.UserActionSuspensionCreateManyInput | Prisma.UserActionSuspensionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserActionSuspension createManyAndReturn
 */
export type UserActionSuspensionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActionSuspension
   */
  select?: Prisma.UserActionSuspensionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserActionSuspension
   */
  omit?: Prisma.UserActionSuspensionOmit<ExtArgs> | null
  /**
   * The data used to create many UserActionSuspensions.
   */
  data: Prisma.UserActionSuspensionCreateManyInput | Prisma.UserActionSuspensionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserActionSuspensionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserActionSuspension update
 */
export type UserActionSuspensionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActionSuspension
   */
  select?: Prisma.UserActionSuspensionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserActionSuspension
   */
  omit?: Prisma.UserActionSuspensionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserActionSuspensionInclude<ExtArgs> | null
  /**
   * The data needed to update a UserActionSuspension.
   */
  data: Prisma.XOR<Prisma.UserActionSuspensionUpdateInput, Prisma.UserActionSuspensionUncheckedUpdateInput>
  /**
   * Choose, which UserActionSuspension to update.
   */
  where: Prisma.UserActionSuspensionWhereUniqueInput
}

/**
 * UserActionSuspension updateMany
 */
export type UserActionSuspensionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserActionSuspensions.
   */
  data: Prisma.XOR<Prisma.UserActionSuspensionUpdateManyMutationInput, Prisma.UserActionSuspensionUncheckedUpdateManyInput>
  /**
   * Filter which UserActionSuspensions to update
   */
  where?: Prisma.UserActionSuspensionWhereInput
  /**
   * Limit how many UserActionSuspensions to update.
   */
  limit?: number
}

/**
 * UserActionSuspension updateManyAndReturn
 */
export type UserActionSuspensionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActionSuspension
   */
  select?: Prisma.UserActionSuspensionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserActionSuspension
   */
  omit?: Prisma.UserActionSuspensionOmit<ExtArgs> | null
  /**
   * The data used to update UserActionSuspensions.
   */
  data: Prisma.XOR<Prisma.UserActionSuspensionUpdateManyMutationInput, Prisma.UserActionSuspensionUncheckedUpdateManyInput>
  /**
   * Filter which UserActionSuspensions to update
   */
  where?: Prisma.UserActionSuspensionWhereInput
  /**
   * Limit how many UserActionSuspensions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserActionSuspensionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserActionSuspension upsert
 */
export type UserActionSuspensionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActionSuspension
   */
  select?: Prisma.UserActionSuspensionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserActionSuspension
   */
  omit?: Prisma.UserActionSuspensionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserActionSuspensionInclude<ExtArgs> | null
  /**
   * The filter to search for the UserActionSuspension to update in case it exists.
   */
  where: Prisma.UserActionSuspensionWhereUniqueInput
  /**
   * In case the UserActionSuspension found by the `where` argument doesn't exist, create a new UserActionSuspension with this data.
   */
  create: Prisma.XOR<Prisma.UserActionSuspensionCreateInput, Prisma.UserActionSuspensionUncheckedCreateInput>
  /**
   * In case the UserActionSuspension was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserActionSuspensionUpdateInput, Prisma.UserActionSuspensionUncheckedUpdateInput>
}

/**
 * UserActionSuspension delete
 */
export type UserActionSuspensionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActionSuspension
   */
  select?: Prisma.UserActionSuspensionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserActionSuspension
   */
  omit?: Prisma.UserActionSuspensionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserActionSuspensionInclude<ExtArgs> | null
  /**
   * Filter which UserActionSuspension to delete.
   */
  where: Prisma.UserActionSuspensionWhereUniqueInput
}

/**
 * UserActionSuspension deleteMany
 */
export type UserActionSuspensionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserActionSuspensions to delete
   */
  where?: Prisma.UserActionSuspensionWhereInput
  /**
   * Limit how many UserActionSuspensions to delete.
   */
  limit?: number
}

/**
 * UserActionSuspension without action
 */
export type UserActionSuspensionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserActionSuspension
   */
  select?: Prisma.UserActionSuspensionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserActionSuspension
   */
  omit?: Prisma.UserActionSuspensionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserActionSuspensionInclude<ExtArgs> | null
}
