/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User.js'
export type * from './models/UserSchoolInfo.js'
export type * from './models/Department.js'
export type * from './models/Major.js'
export type * from './models/YearLevel.js'
export type * from './models/UserVerification.js'
export type * from './models/UserBiometric.js'
export type * from './models/Role.js'
export type * from './models/RolePermissionDefault.js'
export type * from './models/UserPermissionOverride.js'
export type * from './models/UserActionSuspension.js'
export type * from './models/BlockedIp.js'
export type * from './models/SecurityPolicy.js'
export type * from './models/LoginActivity.js'
export type * from './models/AuditLog.js'
export type * from './models/Account.js'
export type * from './models/GmailConnection.js'
export type * from './models/Interest.js'
export type * from './models/UserInterest.js'
export type * from './models/Event.js'
export type * from './models/EventAttendance.js'
export type * from './models/Conversation.js'
export type * from './models/ConversationParticipant.js'
export type * from './models/ChatMessage.js'
export type * from './models/ChatAttachment.js'
export type * from './models/SupportTicket.js'
export type * from './models/SupportTicketReply.js'
export type * from './models/CertificateTemplate.js'
export type * from './models/CertificateTemplateSignatory.js'
export type * from './models/CertificateTemplateAsset.js'
export type * from './models/CertificateDeployment.js'
export type * from './models/MonthlyReportFolder.js'
export type * from './models/MonthlyReport.js'
export type * from './models/MonthlyReportDocument.js'
export type * from './models/MonthlyReportTrailEntry.js'
export type * from './commonInputTypes.js'