
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserBiometric` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UserBiometric
 * 
 */
export type UserBiometricModel = runtime.Types.Result.DefaultSelection<Prisma.$UserBiometricPayload>

export type AggregateUserBiometric = {
  _count: UserBiometricCountAggregateOutputType | null
  _min: UserBiometricMinAggregateOutputType | null
  _max: UserBiometricMaxAggregateOutputType | null
}

export type UserBiometricMinAggregateOutputType = {
  user_biometric_id: string | null
  face_url: string | null
  embedding_type: $Enums.EmbeddingType | null
  isActive: boolean | null
  user_id: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserBiometricMaxAggregateOutputType = {
  user_biometric_id: string | null
  face_url: string | null
  embedding_type: $Enums.EmbeddingType | null
  isActive: boolean | null
  user_id: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserBiometricCountAggregateOutputType = {
  user_biometric_id: number
  face_url: number
  embedding: number
  embedding_type: number
  isActive: number
  user_id: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type UserBiometricMinAggregateInputType = {
  user_biometric_id?: true
  face_url?: true
  embedding_type?: true
  isActive?: true
  user_id?: true
  createdAt?: true
  updatedAt?: true
}

export type UserBiometricMaxAggregateInputType = {
  user_biometric_id?: true
  face_url?: true
  embedding_type?: true
  isActive?: true
  user_id?: true
  createdAt?: true
  updatedAt?: true
}

export type UserBiometricCountAggregateInputType = {
  user_biometric_id?: true
  face_url?: true
  embedding?: true
  embedding_type?: true
  isActive?: true
  user_id?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type UserBiometricAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserBiometric to aggregate.
   */
  where?: Prisma.UserBiometricWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserBiometrics to fetch.
   */
  orderBy?: Prisma.UserBiometricOrderByWithRelationInput | Prisma.UserBiometricOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserBiometricWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserBiometrics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserBiometrics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserBiometrics
  **/
  _count?: true | UserBiometricCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserBiometricMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserBiometricMaxAggregateInputType
}

export type GetUserBiometricAggregateType<T extends UserBiometricAggregateArgs> = {
      [P in keyof T & keyof AggregateUserBiometric]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserBiometric[P]>
    : Prisma.GetScalarType<T[P], AggregateUserBiometric[P]>
}




export type UserBiometricGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserBiometricWhereInput
  orderBy?: Prisma.UserBiometricOrderByWithAggregationInput | Prisma.UserBiometricOrderByWithAggregationInput[]
  by: Prisma.UserBiometricScalarFieldEnum[] | Prisma.UserBiometricScalarFieldEnum
  having?: Prisma.UserBiometricScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserBiometricCountAggregateInputType | true
  _min?: UserBiometricMinAggregateInputType
  _max?: UserBiometricMaxAggregateInputType
}

export type UserBiometricGroupByOutputType = {
  user_biometric_id: string
  face_url: string
  embedding: runtime.JsonValue | null
  embedding_type: $Enums.EmbeddingType
  isActive: boolean
  user_id: string
  createdAt: Date
  updatedAt: Date
  _count: UserBiometricCountAggregateOutputType | null
  _min: UserBiometricMinAggregateOutputType | null
  _max: UserBiometricMaxAggregateOutputType | null
}

export type GetUserBiometricGroupByPayload<T extends UserBiometricGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserBiometricGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserBiometricGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserBiometricGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserBiometricGroupByOutputType[P]>
      }
    >
  >



export type UserBiometricWhereInput = {
  AND?: Prisma.UserBiometricWhereInput | Prisma.UserBiometricWhereInput[]
  OR?: Prisma.UserBiometricWhereInput[]
  NOT?: Prisma.UserBiometricWhereInput | Prisma.UserBiometricWhereInput[]
  user_biometric_id?: Prisma.StringFilter<"UserBiometric"> | string
  face_url?: Prisma.StringFilter<"UserBiometric"> | string
  embedding?: Prisma.JsonNullableFilter<"UserBiometric">
  embedding_type?: Prisma.EnumEmbeddingTypeFilter<"UserBiometric"> | $Enums.EmbeddingType
  isActive?: Prisma.BoolFilter<"UserBiometric"> | boolean
  user_id?: Prisma.StringFilter<"UserBiometric"> | string
  createdAt?: Prisma.DateTimeFilter<"UserBiometric"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UserBiometric"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type UserBiometricOrderByWithRelationInput = {
  user_biometric_id?: Prisma.SortOrder
  face_url?: Prisma.SortOrder
  embedding?: Prisma.SortOrderInput | Prisma.SortOrder
  embedding_type?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type UserBiometricWhereUniqueInput = Prisma.AtLeast<{
  user_biometric_id?: string
  AND?: Prisma.UserBiometricWhereInput | Prisma.UserBiometricWhereInput[]
  OR?: Prisma.UserBiometricWhereInput[]
  NOT?: Prisma.UserBiometricWhereInput | Prisma.UserBiometricWhereInput[]
  face_url?: Prisma.StringFilter<"UserBiometric"> | string
  embedding?: Prisma.JsonNullableFilter<"UserBiometric">
  embedding_type?: Prisma.EnumEmbeddingTypeFilter<"UserBiometric"> | $Enums.EmbeddingType
  isActive?: Prisma.BoolFilter<"UserBiometric"> | boolean
  user_id?: Prisma.StringFilter<"UserBiometric"> | string
  createdAt?: Prisma.DateTimeFilter<"UserBiometric"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UserBiometric"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "user_biometric_id">

export type UserBiometricOrderByWithAggregationInput = {
  user_biometric_id?: Prisma.SortOrder
  face_url?: Prisma.SortOrder
  embedding?: Prisma.SortOrderInput | Prisma.SortOrder
  embedding_type?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.UserBiometricCountOrderByAggregateInput
  _max?: Prisma.UserBiometricMaxOrderByAggregateInput
  _min?: Prisma.UserBiometricMinOrderByAggregateInput
}

export type UserBiometricScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserBiometricScalarWhereWithAggregatesInput | Prisma.UserBiometricScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserBiometricScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserBiometricScalarWhereWithAggregatesInput | Prisma.UserBiometricScalarWhereWithAggregatesInput[]
  user_biometric_id?: Prisma.StringWithAggregatesFilter<"UserBiometric"> | string
  face_url?: Prisma.StringWithAggregatesFilter<"UserBiometric"> | string
  embedding?: Prisma.JsonNullableWithAggregatesFilter<"UserBiometric">
  embedding_type?: Prisma.EnumEmbeddingTypeWithAggregatesFilter<"UserBiometric"> | $Enums.EmbeddingType
  isActive?: Prisma.BoolWithAggregatesFilter<"UserBiometric"> | boolean
  user_id?: Prisma.StringWithAggregatesFilter<"UserBiometric"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UserBiometric"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"UserBiometric"> | Date | string
}

export type UserBiometricCreateInput = {
  user_biometric_id?: string
  face_url: string
  embedding?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  embedding_type?: $Enums.EmbeddingType
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutUser_biometricsInput
}

export type UserBiometricUncheckedCreateInput = {
  user_biometric_id?: string
  face_url: string
  embedding?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  embedding_type?: $Enums.EmbeddingType
  isActive?: boolean
  user_id: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserBiometricUpdateInput = {
  user_biometric_id?: Prisma.StringFieldUpdateOperationsInput | string
  face_url?: Prisma.StringFieldUpdateOperationsInput | string
  embedding?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  embedding_type?: Prisma.EnumEmbeddingTypeFieldUpdateOperationsInput | $Enums.EmbeddingType
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutUser_biometricsNestedInput
}

export type UserBiometricUncheckedUpdateInput = {
  user_biometric_id?: Prisma.StringFieldUpdateOperationsInput | string
  face_url?: Prisma.StringFieldUpdateOperationsInput | string
  embedding?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  embedding_type?: Prisma.EnumEmbeddingTypeFieldUpdateOperationsInput | $Enums.EmbeddingType
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserBiometricCreateManyInput = {
  user_biometric_id?: string
  face_url: string
  embedding?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  embedding_type?: $Enums.EmbeddingType
  isActive?: boolean
  user_id: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserBiometricUpdateManyMutationInput = {
  user_biometric_id?: Prisma.StringFieldUpdateOperationsInput | string
  face_url?: Prisma.StringFieldUpdateOperationsInput | string
  embedding?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  embedding_type?: Prisma.EnumEmbeddingTypeFieldUpdateOperationsInput | $Enums.EmbeddingType
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserBiometricUncheckedUpdateManyInput = {
  user_biometric_id?: Prisma.StringFieldUpdateOperationsInput | string
  face_url?: Prisma.StringFieldUpdateOperationsInput | string
  embedding?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  embedding_type?: Prisma.EnumEmbeddingTypeFieldUpdateOperationsInput | $Enums.EmbeddingType
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserBiometricListRelationFilter = {
  every?: Prisma.UserBiometricWhereInput
  some?: Prisma.UserBiometricWhereInput
  none?: Prisma.UserBiometricWhereInput
}

export type UserBiometricOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserBiometricCountOrderByAggregateInput = {
  user_biometric_id?: Prisma.SortOrder
  face_url?: Prisma.SortOrder
  embedding?: Prisma.SortOrder
  embedding_type?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserBiometricMaxOrderByAggregateInput = {
  user_biometric_id?: Prisma.SortOrder
  face_url?: Prisma.SortOrder
  embedding_type?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserBiometricMinOrderByAggregateInput = {
  user_biometric_id?: Prisma.SortOrder
  face_url?: Prisma.SortOrder
  embedding_type?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserBiometricCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserBiometricCreateWithoutUserInput, Prisma.UserBiometricUncheckedCreateWithoutUserInput> | Prisma.UserBiometricCreateWithoutUserInput[] | Prisma.UserBiometricUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserBiometricCreateOrConnectWithoutUserInput | Prisma.UserBiometricCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserBiometricCreateManyUserInputEnvelope
  connect?: Prisma.UserBiometricWhereUniqueInput | Prisma.UserBiometricWhereUniqueInput[]
}

export type UserBiometricUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserBiometricCreateWithoutUserInput, Prisma.UserBiometricUncheckedCreateWithoutUserInput> | Prisma.UserBiometricCreateWithoutUserInput[] | Prisma.UserBiometricUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserBiometricCreateOrConnectWithoutUserInput | Prisma.UserBiometricCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserBiometricCreateManyUserInputEnvelope
  connect?: Prisma.UserBiometricWhereUniqueInput | Prisma.UserBiometricWhereUniqueInput[]
}

export type UserBiometricUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserBiometricCreateWithoutUserInput, Prisma.UserBiometricUncheckedCreateWithoutUserInput> | Prisma.UserBiometricCreateWithoutUserInput[] | Prisma.UserBiometricUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserBiometricCreateOrConnectWithoutUserInput | Prisma.UserBiometricCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserBiometricUpsertWithWhereUniqueWithoutUserInput | Prisma.UserBiometricUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserBiometricCreateManyUserInputEnvelope
  set?: Prisma.UserBiometricWhereUniqueInput | Prisma.UserBiometricWhereUniqueInput[]
  disconnect?: Prisma.UserBiometricWhereUniqueInput | Prisma.UserBiometricWhereUniqueInput[]
  delete?: Prisma.UserBiometricWhereUniqueInput | Prisma.UserBiometricWhereUniqueInput[]
  connect?: Prisma.UserBiometricWhereUniqueInput | Prisma.UserBiometricWhereUniqueInput[]
  update?: Prisma.UserBiometricUpdateWithWhereUniqueWithoutUserInput | Prisma.UserBiometricUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserBiometricUpdateManyWithWhereWithoutUserInput | Prisma.UserBiometricUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserBiometricScalarWhereInput | Prisma.UserBiometricScalarWhereInput[]
}

export type UserBiometricUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserBiometricCreateWithoutUserInput, Prisma.UserBiometricUncheckedCreateWithoutUserInput> | Prisma.UserBiometricCreateWithoutUserInput[] | Prisma.UserBiometricUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserBiometricCreateOrConnectWithoutUserInput | Prisma.UserBiometricCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserBiometricUpsertWithWhereUniqueWithoutUserInput | Prisma.UserBiometricUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserBiometricCreateManyUserInputEnvelope
  set?: Prisma.UserBiometricWhereUniqueInput | Prisma.UserBiometricWhereUniqueInput[]
  disconnect?: Prisma.UserBiometricWhereUniqueInput | Prisma.UserBiometricWhereUniqueInput[]
  delete?: Prisma.UserBiometricWhereUniqueInput | Prisma.UserBiometricWhereUniqueInput[]
  connect?: Prisma.UserBiometricWhereUniqueInput | Prisma.UserBiometricWhereUniqueInput[]
  update?: Prisma.UserBiometricUpdateWithWhereUniqueWithoutUserInput | Prisma.UserBiometricUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserBiometricUpdateManyWithWhereWithoutUserInput | Prisma.UserBiometricUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserBiometricScalarWhereInput | Prisma.UserBiometricScalarWhereInput[]
}

export type EnumEmbeddingTypeFieldUpdateOperationsInput = {
  set?: $Enums.EmbeddingType
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type UserBiometricCreateWithoutUserInput = {
  user_biometric_id?: string
  face_url: string
  embedding?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  embedding_type?: $Enums.EmbeddingType
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserBiometricUncheckedCreateWithoutUserInput = {
  user_biometric_id?: string
  face_url: string
  embedding?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  embedding_type?: $Enums.EmbeddingType
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserBiometricCreateOrConnectWithoutUserInput = {
  where: Prisma.UserBiometricWhereUniqueInput
  create: Prisma.XOR<Prisma.UserBiometricCreateWithoutUserInput, Prisma.UserBiometricUncheckedCreateWithoutUserInput>
}

export type UserBiometricCreateManyUserInputEnvelope = {
  data: Prisma.UserBiometricCreateManyUserInput | Prisma.UserBiometricCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserBiometricUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserBiometricWhereUniqueInput
  update: Prisma.XOR<Prisma.UserBiometricUpdateWithoutUserInput, Prisma.UserBiometricUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserBiometricCreateWithoutUserInput, Prisma.UserBiometricUncheckedCreateWithoutUserInput>
}

export type UserBiometricUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserBiometricWhereUniqueInput
  data: Prisma.XOR<Prisma.UserBiometricUpdateWithoutUserInput, Prisma.UserBiometricUncheckedUpdateWithoutUserInput>
}

export type UserBiometricUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserBiometricScalarWhereInput
  data: Prisma.XOR<Prisma.UserBiometricUpdateManyMutationInput, Prisma.UserBiometricUncheckedUpdateManyWithoutUserInput>
}

export type UserBiometricScalarWhereInput = {
  AND?: Prisma.UserBiometricScalarWhereInput | Prisma.UserBiometricScalarWhereInput[]
  OR?: Prisma.UserBiometricScalarWhereInput[]
  NOT?: Prisma.UserBiometricScalarWhereInput | Prisma.UserBiometricScalarWhereInput[]
  user_biometric_id?: Prisma.StringFilter<"UserBiometric"> | string
  face_url?: Prisma.StringFilter<"UserBiometric"> | string
  embedding?: Prisma.JsonNullableFilter<"UserBiometric">
  embedding_type?: Prisma.EnumEmbeddingTypeFilter<"UserBiometric"> | $Enums.EmbeddingType
  isActive?: Prisma.BoolFilter<"UserBiometric"> | boolean
  user_id?: Prisma.StringFilter<"UserBiometric"> | string
  createdAt?: Prisma.DateTimeFilter<"UserBiometric"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UserBiometric"> | Date | string
}

export type UserBiometricCreateManyUserInput = {
  user_biometric_id?: string
  face_url: string
  embedding?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  embedding_type?: $Enums.EmbeddingType
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserBiometricUpdateWithoutUserInput = {
  user_biometric_id?: Prisma.StringFieldUpdateOperationsInput | string
  face_url?: Prisma.StringFieldUpdateOperationsInput | string
  embedding?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  embedding_type?: Prisma.EnumEmbeddingTypeFieldUpdateOperationsInput | $Enums.EmbeddingType
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserBiometricUncheckedUpdateWithoutUserInput = {
  user_biometric_id?: Prisma.StringFieldUpdateOperationsInput | string
  face_url?: Prisma.StringFieldUpdateOperationsInput | string
  embedding?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  embedding_type?: Prisma.EnumEmbeddingTypeFieldUpdateOperationsInput | $Enums.EmbeddingType
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserBiometricUncheckedUpdateManyWithoutUserInput = {
  user_biometric_id?: Prisma.StringFieldUpdateOperationsInput | string
  face_url?: Prisma.StringFieldUpdateOperationsInput | string
  embedding?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  embedding_type?: Prisma.EnumEmbeddingTypeFieldUpdateOperationsInput | $Enums.EmbeddingType
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type UserBiometricSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_biometric_id?: boolean
  face_url?: boolean
  embedding?: boolean
  embedding_type?: boolean
  isActive?: boolean
  user_id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userBiometric"]>

export type UserBiometricSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_biometric_id?: boolean
  face_url?: boolean
  embedding?: boolean
  embedding_type?: boolean
  isActive?: boolean
  user_id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userBiometric"]>

export type UserBiometricSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_biometric_id?: boolean
  face_url?: boolean
  embedding?: boolean
  embedding_type?: boolean
  isActive?: boolean
  user_id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userBiometric"]>

export type UserBiometricSelectScalar = {
  user_biometric_id?: boolean
  face_url?: boolean
  embedding?: boolean
  embedding_type?: boolean
  isActive?: boolean
  user_id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type UserBiometricOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"user_biometric_id" | "face_url" | "embedding" | "embedding_type" | "isActive" | "user_id" | "createdAt" | "updatedAt", ExtArgs["result"]["userBiometric"]>
export type UserBiometricInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserBiometricIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserBiometricIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $UserBiometricPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserBiometric"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    user_biometric_id: string
    face_url: string
    embedding: runtime.JsonValue | null
    embedding_type: $Enums.EmbeddingType
    isActive: boolean
    user_id: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["userBiometric"]>
  composites: {}
}

export type UserBiometricGetPayload<S extends boolean | null | undefined | UserBiometricDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserBiometricPayload, S>

export type UserBiometricCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserBiometricFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserBiometricCountAggregateInputType | true
  }

export interface UserBiometricDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserBiometric'], meta: { name: 'UserBiometric' } }
  /**
   * Find zero or one UserBiometric that matches the filter.
   * @param {UserBiometricFindUniqueArgs} args - Arguments to find a UserBiometric
   * @example
   * // Get one UserBiometric
   * const userBiometric = await prisma.userBiometric.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserBiometricFindUniqueArgs>(args: Prisma.SelectSubset<T, UserBiometricFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserBiometricClient<runtime.Types.Result.GetResult<Prisma.$UserBiometricPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserBiometric that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserBiometricFindUniqueOrThrowArgs} args - Arguments to find a UserBiometric
   * @example
   * // Get one UserBiometric
   * const userBiometric = await prisma.userBiometric.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserBiometricFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserBiometricFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserBiometricClient<runtime.Types.Result.GetResult<Prisma.$UserBiometricPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserBiometric that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBiometricFindFirstArgs} args - Arguments to find a UserBiometric
   * @example
   * // Get one UserBiometric
   * const userBiometric = await prisma.userBiometric.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserBiometricFindFirstArgs>(args?: Prisma.SelectSubset<T, UserBiometricFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserBiometricClient<runtime.Types.Result.GetResult<Prisma.$UserBiometricPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserBiometric that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBiometricFindFirstOrThrowArgs} args - Arguments to find a UserBiometric
   * @example
   * // Get one UserBiometric
   * const userBiometric = await prisma.userBiometric.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserBiometricFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserBiometricFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserBiometricClient<runtime.Types.Result.GetResult<Prisma.$UserBiometricPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserBiometrics that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBiometricFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserBiometrics
   * const userBiometrics = await prisma.userBiometric.findMany()
   * 
   * // Get first 10 UserBiometrics
   * const userBiometrics = await prisma.userBiometric.findMany({ take: 10 })
   * 
   * // Only select the `user_biometric_id`
   * const userBiometricWithUser_biometric_idOnly = await prisma.userBiometric.findMany({ select: { user_biometric_id: true } })
   * 
   */
  findMany<T extends UserBiometricFindManyArgs>(args?: Prisma.SelectSubset<T, UserBiometricFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserBiometricPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserBiometric.
   * @param {UserBiometricCreateArgs} args - Arguments to create a UserBiometric.
   * @example
   * // Create one UserBiometric
   * const UserBiometric = await prisma.userBiometric.create({
   *   data: {
   *     // ... data to create a UserBiometric
   *   }
   * })
   * 
   */
  create<T extends UserBiometricCreateArgs>(args: Prisma.SelectSubset<T, UserBiometricCreateArgs<ExtArgs>>): Prisma.Prisma__UserBiometricClient<runtime.Types.Result.GetResult<Prisma.$UserBiometricPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserBiometrics.
   * @param {UserBiometricCreateManyArgs} args - Arguments to create many UserBiometrics.
   * @example
   * // Create many UserBiometrics
   * const userBiometric = await prisma.userBiometric.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserBiometricCreateManyArgs>(args?: Prisma.SelectSubset<T, UserBiometricCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserBiometrics and returns the data saved in the database.
   * @param {UserBiometricCreateManyAndReturnArgs} args - Arguments to create many UserBiometrics.
   * @example
   * // Create many UserBiometrics
   * const userBiometric = await prisma.userBiometric.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserBiometrics and only return the `user_biometric_id`
   * const userBiometricWithUser_biometric_idOnly = await prisma.userBiometric.createManyAndReturn({
   *   select: { user_biometric_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserBiometricCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserBiometricCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserBiometricPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserBiometric.
   * @param {UserBiometricDeleteArgs} args - Arguments to delete one UserBiometric.
   * @example
   * // Delete one UserBiometric
   * const UserBiometric = await prisma.userBiometric.delete({
   *   where: {
   *     // ... filter to delete one UserBiometric
   *   }
   * })
   * 
   */
  delete<T extends UserBiometricDeleteArgs>(args: Prisma.SelectSubset<T, UserBiometricDeleteArgs<ExtArgs>>): Prisma.Prisma__UserBiometricClient<runtime.Types.Result.GetResult<Prisma.$UserBiometricPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserBiometric.
   * @param {UserBiometricUpdateArgs} args - Arguments to update one UserBiometric.
   * @example
   * // Update one UserBiometric
   * const userBiometric = await prisma.userBiometric.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserBiometricUpdateArgs>(args: Prisma.SelectSubset<T, UserBiometricUpdateArgs<ExtArgs>>): Prisma.Prisma__UserBiometricClient<runtime.Types.Result.GetResult<Prisma.$UserBiometricPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserBiometrics.
   * @param {UserBiometricDeleteManyArgs} args - Arguments to filter UserBiometrics to delete.
   * @example
   * // Delete a few UserBiometrics
   * const { count } = await prisma.userBiometric.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserBiometricDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserBiometricDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserBiometrics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBiometricUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserBiometrics
   * const userBiometric = await prisma.userBiometric.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserBiometricUpdateManyArgs>(args: Prisma.SelectSubset<T, UserBiometricUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserBiometrics and returns the data updated in the database.
   * @param {UserBiometricUpdateManyAndReturnArgs} args - Arguments to update many UserBiometrics.
   * @example
   * // Update many UserBiometrics
   * const userBiometric = await prisma.userBiometric.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserBiometrics and only return the `user_biometric_id`
   * const userBiometricWithUser_biometric_idOnly = await prisma.userBiometric.updateManyAndReturn({
   *   select: { user_biometric_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserBiometricUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserBiometricUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserBiometricPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserBiometric.
   * @param {UserBiometricUpsertArgs} args - Arguments to update or create a UserBiometric.
   * @example
   * // Update or create a UserBiometric
   * const userBiometric = await prisma.userBiometric.upsert({
   *   create: {
   *     // ... data to create a UserBiometric
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserBiometric we want to update
   *   }
   * })
   */
  upsert<T extends UserBiometricUpsertArgs>(args: Prisma.SelectSubset<T, UserBiometricUpsertArgs<ExtArgs>>): Prisma.Prisma__UserBiometricClient<runtime.Types.Result.GetResult<Prisma.$UserBiometricPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserBiometrics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBiometricCountArgs} args - Arguments to filter UserBiometrics to count.
   * @example
   * // Count the number of UserBiometrics
   * const count = await prisma.userBiometric.count({
   *   where: {
   *     // ... the filter for the UserBiometrics we want to count
   *   }
   * })
  **/
  count<T extends UserBiometricCountArgs>(
    args?: Prisma.Subset<T, UserBiometricCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserBiometricCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserBiometric.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBiometricAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserBiometricAggregateArgs>(args: Prisma.Subset<T, UserBiometricAggregateArgs>): Prisma.PrismaPromise<GetUserBiometricAggregateType<T>>

  /**
   * Group by UserBiometric.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBiometricGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserBiometricGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserBiometricGroupByArgs['orderBy'] }
      : { orderBy?: UserBiometricGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserBiometricGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserBiometricGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserBiometric model
 */
readonly fields: UserBiometricFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserBiometric.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserBiometricClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserBiometric model
 */
export interface UserBiometricFieldRefs {
  readonly user_biometric_id: Prisma.FieldRef<"UserBiometric", 'String'>
  readonly face_url: Prisma.FieldRef<"UserBiometric", 'String'>
  readonly embedding: Prisma.FieldRef<"UserBiometric", 'Json'>
  readonly embedding_type: Prisma.FieldRef<"UserBiometric", 'EmbeddingType'>
  readonly isActive: Prisma.FieldRef<"UserBiometric", 'Boolean'>
  readonly user_id: Prisma.FieldRef<"UserBiometric", 'String'>
  readonly createdAt: Prisma.FieldRef<"UserBiometric", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"UserBiometric", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UserBiometric findUnique
 */
export type UserBiometricFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBiometric
   */
  select?: Prisma.UserBiometricSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBiometric
   */
  omit?: Prisma.UserBiometricOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBiometricInclude<ExtArgs> | null
  /**
   * Filter, which UserBiometric to fetch.
   */
  where: Prisma.UserBiometricWhereUniqueInput
}

/**
 * UserBiometric findUniqueOrThrow
 */
export type UserBiometricFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBiometric
   */
  select?: Prisma.UserBiometricSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBiometric
   */
  omit?: Prisma.UserBiometricOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBiometricInclude<ExtArgs> | null
  /**
   * Filter, which UserBiometric to fetch.
   */
  where: Prisma.UserBiometricWhereUniqueInput
}

/**
 * UserBiometric findFirst
 */
export type UserBiometricFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBiometric
   */
  select?: Prisma.UserBiometricSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBiometric
   */
  omit?: Prisma.UserBiometricOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBiometricInclude<ExtArgs> | null
  /**
   * Filter, which UserBiometric to fetch.
   */
  where?: Prisma.UserBiometricWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserBiometrics to fetch.
   */
  orderBy?: Prisma.UserBiometricOrderByWithRelationInput | Prisma.UserBiometricOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserBiometrics.
   */
  cursor?: Prisma.UserBiometricWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserBiometrics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserBiometrics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserBiometrics.
   */
  distinct?: Prisma.UserBiometricScalarFieldEnum | Prisma.UserBiometricScalarFieldEnum[]
}

/**
 * UserBiometric findFirstOrThrow
 */
export type UserBiometricFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBiometric
   */
  select?: Prisma.UserBiometricSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBiometric
   */
  omit?: Prisma.UserBiometricOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBiometricInclude<ExtArgs> | null
  /**
   * Filter, which UserBiometric to fetch.
   */
  where?: Prisma.UserBiometricWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserBiometrics to fetch.
   */
  orderBy?: Prisma.UserBiometricOrderByWithRelationInput | Prisma.UserBiometricOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserBiometrics.
   */
  cursor?: Prisma.UserBiometricWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserBiometrics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserBiometrics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserBiometrics.
   */
  distinct?: Prisma.UserBiometricScalarFieldEnum | Prisma.UserBiometricScalarFieldEnum[]
}

/**
 * UserBiometric findMany
 */
export type UserBiometricFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBiometric
   */
  select?: Prisma.UserBiometricSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBiometric
   */
  omit?: Prisma.UserBiometricOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBiometricInclude<ExtArgs> | null
  /**
   * Filter, which UserBiometrics to fetch.
   */
  where?: Prisma.UserBiometricWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserBiometrics to fetch.
   */
  orderBy?: Prisma.UserBiometricOrderByWithRelationInput | Prisma.UserBiometricOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserBiometrics.
   */
  cursor?: Prisma.UserBiometricWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserBiometrics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserBiometrics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserBiometrics.
   */
  distinct?: Prisma.UserBiometricScalarFieldEnum | Prisma.UserBiometricScalarFieldEnum[]
}

/**
 * UserBiometric create
 */
export type UserBiometricCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBiometric
   */
  select?: Prisma.UserBiometricSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBiometric
   */
  omit?: Prisma.UserBiometricOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBiometricInclude<ExtArgs> | null
  /**
   * The data needed to create a UserBiometric.
   */
  data: Prisma.XOR<Prisma.UserBiometricCreateInput, Prisma.UserBiometricUncheckedCreateInput>
}

/**
 * UserBiometric createMany
 */
export type UserBiometricCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserBiometrics.
   */
  data: Prisma.UserBiometricCreateManyInput | Prisma.UserBiometricCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserBiometric createManyAndReturn
 */
export type UserBiometricCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBiometric
   */
  select?: Prisma.UserBiometricSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserBiometric
   */
  omit?: Prisma.UserBiometricOmit<ExtArgs> | null
  /**
   * The data used to create many UserBiometrics.
   */
  data: Prisma.UserBiometricCreateManyInput | Prisma.UserBiometricCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBiometricIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserBiometric update
 */
export type UserBiometricUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBiometric
   */
  select?: Prisma.UserBiometricSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBiometric
   */
  omit?: Prisma.UserBiometricOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBiometricInclude<ExtArgs> | null
  /**
   * The data needed to update a UserBiometric.
   */
  data: Prisma.XOR<Prisma.UserBiometricUpdateInput, Prisma.UserBiometricUncheckedUpdateInput>
  /**
   * Choose, which UserBiometric to update.
   */
  where: Prisma.UserBiometricWhereUniqueInput
}

/**
 * UserBiometric updateMany
 */
export type UserBiometricUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserBiometrics.
   */
  data: Prisma.XOR<Prisma.UserBiometricUpdateManyMutationInput, Prisma.UserBiometricUncheckedUpdateManyInput>
  /**
   * Filter which UserBiometrics to update
   */
  where?: Prisma.UserBiometricWhereInput
  /**
   * Limit how many UserBiometrics to update.
   */
  limit?: number
}

/**
 * UserBiometric updateManyAndReturn
 */
export type UserBiometricUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBiometric
   */
  select?: Prisma.UserBiometricSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserBiometric
   */
  omit?: Prisma.UserBiometricOmit<ExtArgs> | null
  /**
   * The data used to update UserBiometrics.
   */
  data: Prisma.XOR<Prisma.UserBiometricUpdateManyMutationInput, Prisma.UserBiometricUncheckedUpdateManyInput>
  /**
   * Filter which UserBiometrics to update
   */
  where?: Prisma.UserBiometricWhereInput
  /**
   * Limit how many UserBiometrics to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBiometricIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserBiometric upsert
 */
export type UserBiometricUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBiometric
   */
  select?: Prisma.UserBiometricSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBiometric
   */
  omit?: Prisma.UserBiometricOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBiometricInclude<ExtArgs> | null
  /**
   * The filter to search for the UserBiometric to update in case it exists.
   */
  where: Prisma.UserBiometricWhereUniqueInput
  /**
   * In case the UserBiometric found by the `where` argument doesn't exist, create a new UserBiometric with this data.
   */
  create: Prisma.XOR<Prisma.UserBiometricCreateInput, Prisma.UserBiometricUncheckedCreateInput>
  /**
   * In case the UserBiometric was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserBiometricUpdateInput, Prisma.UserBiometricUncheckedUpdateInput>
}

/**
 * UserBiometric delete
 */
export type UserBiometricDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBiometric
   */
  select?: Prisma.UserBiometricSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBiometric
   */
  omit?: Prisma.UserBiometricOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBiometricInclude<ExtArgs> | null
  /**
   * Filter which UserBiometric to delete.
   */
  where: Prisma.UserBiometricWhereUniqueInput
}

/**
 * UserBiometric deleteMany
 */
export type UserBiometricDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserBiometrics to delete
   */
  where?: Prisma.UserBiometricWhereInput
  /**
   * Limit how many UserBiometrics to delete.
   */
  limit?: number
}

/**
 * UserBiometric without action
 */
export type UserBiometricDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBiometric
   */
  select?: Prisma.UserBiometricSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBiometric
   */
  omit?: Prisma.UserBiometricOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBiometricInclude<ExtArgs> | null
}
